import GeneratedPartView from '../GeneratedPartView';
import { GENERATED_DEVICE_ART, GENERATED_PART_ART } from '../generated-assets';
import DeviceCourse from '../DeviceCourse';
import {itemAt} from './parameters';
import HouseholdLabPage from "./HouseholdLabPage";
import ConsumerLabPage from "./ConsumerLabPage";
import RoboticsLabPage from "./RoboticsLabPage";
import ControlLabPage from "./ControlLabPage";
import MarineLabPage from "./MarineLabPage";
import { useEffect, useMemo, useState, type ReactNode } from "react";
import { Link } from "react-router-dom";
import { STUDIO_PATH } from "../catalogue";
import { LABS, labPath } from "../labs/data";
import { Waveform } from "../labs/visuals";
import type { Trace } from "../labs/engine";
import { ADVANCED_LABS, advancedPath, initialAdvancedValues, type AdvancedLab } from "./data";
import { simulateAdvanced, type AdvancedResult } from "./engine";
import "./advanced.css";
import { componentFunction } from "./components";
import SecurityLabPage from "./SecurityLabPage";
import SystemsLabPage from "./SystemsLabPage";
import AviationLabPage from "./AviationLabPage";
import { FlightComputerArchitecture } from "./FlightComputerArchitecture";
import { FlyByWireResponse, DeviceResponseTrace } from "./FlyByWireResponse";
import { AirDataConnections, AirDataGauges } from "./AirDataPanels";
import { INSArchitecture } from "./INSArchitecture";
import { GPSStageIcon } from "./GPSStageIcon";

function Panel({name,title,children}:{name:string;title:string;children:ReactNode}) {
  return <section id={`advanced-${name}`} className={`adv-panel adv-${name}`}><h2><span aria-hidden="true">◈</span>{title}</h2>{children}</section>;
}

function CellHistogram({trace}:{trace:Trace}) {
  const peak=Math.max(1,...trace.samples);
  return <figure className="adv-histogram"><figcaption>{trace.label}</figcaption><svg viewBox="0 0 240 200" role="img" aria-label={`${trace.label} measured event distribution`}><path d="M35 20V168H225" fill="none" stroke="#7ca4bf"/>{[0,1,2,3].map(i=><g key={i}><path d={`M35 ${168-i*45}H225`} stroke="#284b65"/><text x="31" y={172-i*45} textAnchor="end" fill="#a6c8df" fontSize="10">{Math.round(peak*i/3)}</text><text x={35+i*63} y="184" textAnchor="middle" fill="#a6c8df" fontSize="10">{Math.round(trace.timeSpan*i/3)}</text></g>)}{trace.samples.filter((_,i)=>i%6===0).map((value,i)=><rect key={i} x={36+i*4.7} y={168-value/peak*140} width="4.5" height={value/peak*140} fill={trace.color}/>)}<text x="130" y="199" textAnchor="middle" fill="#c5e5f8" fontSize="10">Cell volume (fL)</text></svg></figure>;
}

function TimedSignal({trace,time}:{trace:Trace;time:number}) {
  const duration=trace.timeSpan??10;
  const fraction=Math.min(1,time/Math.max(.01,duration));
  const sample=trace.samples[Math.round(fraction*(trace.samples.length-1))]??0;
  return <div className="adv-timed-signal"><Waveform trace={trace}/><svg viewBox="0 0 610 145" aria-hidden="true"><path d={`M${40+fraction*550} 25V112`} stroke="#ffcc57" strokeDasharray="3 3"/><text x="300" y="19" textAnchor="middle" fill="#ffcc57" fontSize="11">t = {Math.min(time,duration).toFixed(1)} · {sample.toFixed(2)} {trace.unit}</text></svg></div>;
}

function CBCResults({result}:{result:AdvancedResult}) {
  const rows=[ ["WBC teaching value","WBC","4.0–10.0"], ["RBC teaching value","RBC","4.0–5.5"], ["Hemoglobin teaching value","Hemoglobin","12.0–16.0"], ["Hematocrit teaching value","Hematocrit","36.0–46.0"], ["MCV teaching value","MCV","80.0–100.0"], ["MCH teaching value","MCH","27.0–33.0"], ["MCHC teaching value","MCHC","32.0–36.0"], ["Platelet teaching value","Platelets","150–400"] ];
  return <><table className="adv-cbc-table"><thead><tr><th>Parameter</th><th>Result</th><th>Units</th><th>Example interval</th></tr></thead><tbody>{rows.map(([key,name,range])=>{const metric=result.metrics.find(m=>m.label===key)!;return <tr key={key}><th>{name}</th><td>{metric.value}</td><td>{metric.unit}</td><td>{range}</td></tr>;})}</tbody></table><p>Sampled RBC events: {result.metrics.find(m=>m.label==="Sampled RBC events")?.value}<br/>Sampling uncertainty: {result.metrics.find(m=>m.label==="Sampling uncertainty")?.value} %</p><small>Teaching data. Example intervals from the supplied reference; actual laboratory intervals vary.</small></>;
}

function Architecture({lab,selected}:{lab:AdvancedLab;selected:number}) {
  if(lab.number===58)return <FlightComputerArchitecture/>;
  if(lab.number===63)return <INSArchitecture/>;
  if(lab.family==="gps")return <svg viewBox="0 0 500 300" role="img" aria-label="GNSS RF acquisition, timing reference, correlation and navigation architecture"><defs><marker id="gnss-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#42baff"/></marker></defs>{[[8,10,95,50,"Antenna"],[120,10,125,50,"LNA + RF filter"],[262,10,108,50,"Downconverter"],[387,10,105,50,"ADC"],[8,105,95,60,"Timing reference"],[120,95,250,85,"Baseband correlator"],[387,105,105,65,"MCU / CPU"],[8,215,95,58,"Memory"],[120,225,125,48,"Power supply"],[262,225,108,48,"Display interface"],[387,225,105,48,"I/O connectors"]].map(([x,y,w,h,label])=><g key={label}><rect x={x} y={y} width={w} height={h} rx="4" fill={label==="Baseband correlator"?"#0b466a":"#10344b"} stroke="#53b7dc"/><text x={Number(x)+Number(w)/2} y={Number(y)+Number(h)/2+4} fill="#d5efff" textAnchor="middle" fontSize="11">{label}</text>{label==="Baseband correlator"&&<text x="245" y="156" fill="#a2cce3" textAnchor="middle" fontSize="10">Code / carrier tracking · pseudoranges</text>}</g>)}<path d="M103 35H117M245 35H259M370 35H384M440 60V80H245V92M103 135H117M370 137H384M440 170V195H317V222M440 195V222M103 244H110V177M183 225V195H245V183" fill="none" stroke="#42baff" markerEnd="url(#gnss-arrow)"/><text x="250" y="294" textAnchor="middle" fill="#9dc4dc" fontSize="11">GNSS receiver signal path and supporting electronics</text></svg>;
  if(lab.family==="cockpit")return <svg viewBox="0 0 700 300" role="img" aria-label="Glass cockpit sensor buses, data processing and display architecture"><defs><marker id="cockpit-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#38bbff"/></marker></defs>{["Air data — ADC","GPS / GNSS","Attitude — AHRS","Engine data — FADEC","Navigation — FMS","Other avionics"].map((name,i)=><g key={name}><rect x="10" y={20+i*34} width="185" height="28" rx="4" fill="#10364f" stroke="#3ca4d7"/><text x="102" y={38+i*34} fill="#d6f0ff" textAnchor="middle" fontSize="12">{name}</text><path d={`M195 ${34+i*34}H225V115H247`} fill="none" stroke="#38bbff"/></g>)}{["Data concentration","Flight-data computer","Graphics processor"].map((name,i)=><g key={name}><rect x="250" y={40+i*62} width="215" height="50" rx="5" fill="#0d4267" stroke="#3ca4d7"/><text x="357" y={69+i*62} fill="#d6f0ff" textAnchor="middle" fontSize="14">{name}</text>{i<2&&<path d={`M357 ${90+i*62}v10`} stroke="#38bbff" markerEnd="url(#cockpit-arrow)"/>}</g>)}{["PFD — primary flight","MFD — navigation / engine"].map((name,i)=><g key={name}><rect x="500" y={45+i*103} width="190" height="80" rx="5" fill="#12364e" stroke="#3ca4d7"/><text x="595" y={89+i*103} textAnchor="middle" fill="#d6f0ff" fontSize="12">{name}</text><path d={`M465 188H480V${85+i*103}H497`} fill="none" stroke="#38bbff" markerEnd="url(#cockpit-arrow)"/></g>)}<rect x="10" y="254" width="455" height="32" rx="5" fill="#11374e" stroke="#3ca4d7"/><text x="237" y="275" fill="#d6f0ff" textAnchor="middle" fontSize="12">Protected power supply · stable references</text><rect x="500" y="254" width="190" height="32" rx="5" fill="#11374e" stroke="#3ca4d7"/><text x="595" y="275" fill="#d6f0ff" textAnchor="middle" fontSize="12">ARINC data buses</text><path d="M235 254V220H350V215M465 270H498M595 254V230" stroke="#f2bb4f" fill="none"/></svg>;
  if(lab.family==="chemistry")return <svg viewBox="0 0 480 280" role="img" aria-label="Chemistry analyzer controller and acquisition electronics"><defs><marker id="chem-control-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#48bfff"/></marker></defs><rect x="140" y="70" width="135" height="140" rx="7" fill="#0d486e" stroke="#42baff"/><text x="207" y="110" textAnchor="middle" fill="#d8f1ff" fontSize="14">Main controller</text><text x="207" y="135" textAnchor="middle" fill="#a3cce5" fontSize="11">Sequence + timing</text><text x="207" y="155" textAnchor="middle" fill="#a3cce5" fontSize="11">ADC acquisition</text><text x="207" y="175" textAnchor="middle" fill="#a3cce5" fontSize="11">Calibration + results</text>{["Motor drivers","Pump / valve drivers","Temperature control","Optical front end","Position / level sensors"].map((name,i)=><g key={name}><rect x="325" y={10+i*53} width="145" height="43" rx="4" fill="#11374f" stroke="#42baff"/><text x="397" y={35+i*53} fill="#d8f1ff" textAnchor="middle" fontSize="11">{name}</text><path d={`M275 140H300V${31+i*53}H322`} fill="none" stroke="#42baff" markerEnd="url(#chem-control-arrow)"/></g>)}{["Touchscreen UI","LIS / HIS interface"].map((name,i)=><g key={name}><rect x="5" y={60+i*110} width="110" height="60" rx="5" fill="#11374f" stroke="#42baff"/><text x="60" y={93+i*110} fill="#d8f1ff" textAnchor="middle" fontSize="11">{name}</text><path d={`M115 ${90+i*110}H137`} stroke="#42baff" markerEnd="url(#chem-control-arrow)"/></g>)}<text x="215" y="265" fill="#f1c264" textAnchor="middle" fontSize="11">Protected power · analog reference · sensor return</text></svg>;
  if(lab.family==="fly-by-wire")return <svg viewBox="0 0 700 350" role="img" aria-label="Redundant fly-by-wire computer channels and servo feedback"><defs><marker id="fbw-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#47baff"/></marker></defs>{[[10,30,160,70,"Pilot control input"],[10,115,160,70,"Air-data sensors"],[10,200,160,70,"Inertial sensors"],[250,70,155,55,"Channel 1 — primary"],[250,135,155,55,"Channel 2 — alternate"],[250,200,155,55,"Channel 3 — standby"],[440,100,115,80,"Actuator electronics"],[580,60,110,85,"Servo actuator"],[580,200,110,70,"Position feedback"],[250,295,155,45,"Data buses"],[450,295,180,45,"Independent power"]].map(([x,y,w,h,label])=><g key={label}><rect x={x} y={y} width={w} height={h} rx="6" stroke={label==="Channel 2 — alternate"?"#88df52":label==="Channel 3 — standby"?"#f2b335":"#5c94be"} fill={String(label).startsWith("Channel")?"#0b4267":"#0c2c43"}/><text x={Number(x)+Number(w)/2} y={Number(y)+Number(h)/2+4} fill="#d9eeff" textAnchor="middle" fontSize="11">{label}</text></g>)}<rect x="235" y="28" width="185" height="245" rx="8" fill="none" stroke="#2881b3"/><text x="327" y="49" fill="#d9eeff" textAnchor="middle" fontSize="12">Flight control computers</text><path d="M170 65H205V160H247M170 150H247M170 235H205V160M405 98H425V140H437M405 163H437M405 228H425V140M555 130H577M635 145V197M580 235H560V180M580 235H430V170H405M327 273V292M540 295V280H635V273" fill="none" stroke="#47baff" markerEnd="url(#fbw-arrow)"/><text x="70" y="310" fill="#47baff" fontSize="11">Command + feedback</text><text x="70" y="330" fill="#f2b335" fontSize="11">Protected power rails</text></svg>;
  if(lab.family==="centrifuge")return <><svg viewBox="0 0 700 290" role="img" aria-label="Centrifuge sensor, MCU, motor-driver and power circuit"><defs><marker id="centrifuge-arrow" markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#35bbff"/></marker></defs>{[[10,10,125,45,"Lid interlock"],[155,10,125,45,"Temperature"],[300,10,125,45,"RPM sensor"],[445,10,125,45,"Imbalance"],[10,120,125,45,"User settings"],[10,200,125,45,"Display"],[180,110,210,115,"Microcontroller"],[420,135,125,60,"Motor driver"],[565,135,125,60,"Brushless motor"],[340,250,210,32,"Power supply"]].map(([x,y,w,h,label])=><g key={label}><rect x={x} y={y} width={w} height={h} rx="5" fill={label==="Microcontroller"?"#0a4c7d":"#10334b"} stroke="#40b9ff"/><text x={Number(x)+Number(w)/2} y={Number(y)+22} textAnchor="middle" fill="#daf2ff" fontSize="13">{label}</text>{label==="Microcontroller"&&["Speed regulation","Safety monitoring","Sensor acquisition","User interface"].map((text,i)=><text key={text} x="285" y={151+i*17} textAnchor="middle" fill="#95cce8" fontSize="11">{text}</text>)}</g>)}{[72,217,362,507].map(x=><path key={x} d={`M${x} 55V80H285V108`} stroke="#35bbff" fill="none" markerEnd="url(#centrifuge-arrow)"/>)}<path d="M135 142H177M180 214H138M390 164H417M545 164H562" fill="none" stroke="#35bbff" strokeWidth="2" markerEnd="url(#centrifuge-arrow)"/><path d="M440 250V215H485V198M548 266H625V199M340 266H285V228" stroke="#f1b64a" fill="none"/><text x="610" y="30" fill="#6cdec1" fontSize="11">Sensor feedback</text><text x="610" y="48" fill="#f1b64a" fontSize="11">Regulated DC</text></svg></>;
  const blocks=lab.family==="centrifuge"?["User settings","Speed controller","Motor driver","Rotor / motor","Tachometer feedback"]:lab.family==="chemistry"?["Sample + reagent","Incubation / reaction","Optical front end","ADC / calibration","Concentration output"]:lab.family==="hematology"?["Metered sample","Dilution / flow cell","Impedance / optics","ADC / classification","CBC + flags"]:lab.family==="fly-by-wire"?["Pilot + sensors","Redundant computers","Actuator electronics","Control surface","Position feedback"]:lab.family==="gps"?["Antenna / RF front end","Correlation / tracking","Pseudoranges","Position + clock solver","Navigation output"]:lab.family==="ins"?["Gyros + accelerometers","Conditioning / ADC","Attitude propagation","Velocity / position","Aiding + validity"]:lab.family==="air-data"?["Pitot / static / OAT","Sensor conditioning","ADC / calibration","Air-data calculation","Avionics output"]:["Validated sensor data","Avionics bus interface","Flight / graphics CPU","Display or guidance","Validity / monitoring"];
  return <><svg viewBox="0 0 700 220" role="img" aria-label={`${lab.device.name} system architecture`}><defs><marker id={`adv-arrow-${lab.number}`} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto"><path d="M0 0L7 3.5L0 7" fill="#40b9ff"/></marker></defs>{blocks.map((block,i)=><g key={block}><rect x={12+i*138} y="57" width="126" height="85" rx="5" fill={selected===i?"#086bbb":"#11364e"} stroke="#48b2eb"/><text x={75+i*138} y="87" fill="#dcf4ff" textAnchor="middle" fontSize="13">{block.split(" ").slice(0,2).join(" ")}</text><text x={75+i*138} y="109" fill="#dcf4ff" textAnchor="middle" fontSize="13">{block.split(" ").slice(2).join(" ")}</text>{i<4&&<path d={`M${138+i*138} 98h10`} stroke="#40b9ff" markerEnd={`url(#adv-arrow-${lab.number})`}/>}</g>)}<path d="M660 143v35H77v-31" fill="none" stroke="#4fd2ad" strokeDasharray="6 3"/><text x="330" y="171" textAnchor="middle" fill="#7ce2c4" fontSize="12">Feedback / validity supervision</text><path d="M77 43H629" stroke="#efbe65"/><text x="350" y="25" textAnchor="middle" fill="#efbe65" fontSize="12">Regulated power • protection • signal reference</text><text x="350" y="208" textAnchor="middle" fill="#9abbd1" fontSize="11">Conceptual functional architecture • independent of physical PCB placement</text></svg><p>{lab.principle}</p></>;
}

function InstrumentVisual({lab,result,values,time,mode}:{lab:AdvancedLab;result:AdvancedResult;values:Record<string,number>;time:number;mode:string}) {
  if(lab.number===59&&result.valid)return <FlyByWireResponse result={result}/>;
  if(!result.valid)return <div className="adv-invalid" role="status"><strong>Output invalid</strong><p>{result.status}</p></div>;
  if(lab.family==="cockpit"&&mode==="Altitude tape")return <svg className="adv-instrument" viewBox="0 0 420 260" role="img" aria-label="Live cockpit altitude tape"><rect x="125" y="10" width="170" height="230" fill="#173246" stroke="#83abc2"/>{[-2,-1,0,1,2].map(i=><g key={i}><path d={`M125 ${125+i*42}h20`} stroke="white"/><text x="220" y={131+i*42} fill="white" textAnchor="middle" fontSize="21">{(values.altitude??0)-i*100}</text></g>)}<rect x="130" y="106" width="160" height="39" fill="#03090e" stroke="white"/><text x="210" y="134" fill="white" textAnchor="middle" fontSize="29">{values.altitude}</text><text x="210" y="257" fill="#95d6ed" textAnchor="middle" fontSize="15">ALTITUDE · ft</text></svg>;
  if(lab.family==="pfd")return <svg className="adv-instrument adv-pfd" viewBox="0 0 420 300" role="img" aria-label="Live attitude, airspeed, altitude, heading and vertical speed indication"><defs><clipPath id="pfd-live-horizon"><rect x="76" y="28" width="254" height="185"/></clipPath></defs><rect width="420" height="300" fill="#060c16"/><text x="210" y="20" textAnchor="middle" fill="#55f647" fontSize="12">HDG · AP · VNAV · ALT</text><g clipPath="url(#pfd-live-horizon)"><g transform={`rotate(${-(values.roll??0)} 203 125) translate(0 ${(values.pitch??0)*4})`}><rect x="-100" y="-180" width="650" height="305" fill="#0758d6"/><rect x="-100" y="125" width="650" height="350" fill="#805825"/><path d="M-100 125H550" stroke="white" strokeWidth="2"/>{[-60,-40,-20,20,40,60].map((y,i)=><g key={y}><path d={`M${i%2?185:170} ${125+y}h${i%2?36:66}`} stroke="white"/><text x="246" y={129+y} fill="white" fontSize="10">{Math.abs(y/2)}</text></g>)}</g></g><path d="M117 125h65l21 8 21-8h64" fill="none" stroke="#f9f72e" strokeWidth="3"/><path d="M95 92Q203 -18 311 92" fill="none" stroke="white"/>{[-60,-40,-20,0,20,40,60].map(a=><path key={a} d="M203 36v12" transform={`rotate(${a} 203 125)`} stroke="white"/>)}<path d="M197 44l6-12 6 12Z" fill="#f547ca" stroke="white"/>{[0,1].map(side=><g key={side}><rect x={side?334:9} y="28" width={side?72:63} height="185" fill="#173245" stroke="#6291a7"/>{[-3,-2,-1,0,1,2,3].map(k=><g key={k}><path d={`M${side?334:61} ${125+k*25}h${side?10:11}`} stroke="white"/><text x={side?347:18} y={129+k*25} fill="white" fontSize="13">{side?Math.round((values.altitude??0)+time*(values.climb??0)/60-k*100):Math.round((values.speed??0)-k*20)}</text></g>)}<rect x={side?332:7} y="112" width={side?76:65} height="27" fill="#050909" stroke="white"/><text x={side?370:39} y="133" fill="white" textAnchor="middle" fontSize="21">{side?Math.round((values.altitude??0)+time*(values.climb??0)/60):values.speed}</text></g>)}<text x="15" y="233" fill="#62e4ff" fontSize="10">TAS {values.speed} KT</text><text x="345" y="234" fill="#62e4ff" fontSize="10">VS {values.climb}</text><path d="M123 289A84 84 0 0 1 287 289" fill="none" stroke="white"/>{[-60,-30,0,30,60].map(a=><g key={a} transform={`rotate(${a} 205 305)`}><path d="M205 221v8" stroke="white"/><text x="205" y="243" fill="white" textAnchor="middle" fontSize="11">{Math.round(((values.heading??0)+a+360)%360)}</text></g>)}<rect x="178" y="213" width="56" height="24" fill="#080e17" stroke="white"/><text x="206" y="231" textAnchor="middle" fill="white" fontSize="18">{values.heading}°</text><text x="206" y="277" textAnchor="middle" fill="#fa47ed" fontSize="12">GPS · LNAV</text></svg>;
  if(lab.family==="air-data")return <div className="adv-airdata"><svg viewBox="0 0 420 180" role="img" aria-label="Pitot and static pressure measurement paths"><path d="M15 65h160v60h100M15 125h115v30h145" fill="none" stroke="#43bdff" strokeWidth="3"/><path d="M10 55l12 10-12 10M10 115l12 10-12 10" fill="none" stroke="#f7cd65"/><rect x="275" y="88" width="120" height="80" rx="7" fill="#10364c" stroke="#4aafe0"/><text x="30" y="50" fill="#e8f5ff">Total pressure = static + dynamic</text><text x="25" y="110" fill="#e8f5ff">Static pressure</text><text x="335" y="120" textAnchor="middle" fill="#e8f5ff">Pressure sensors</text><text x="335" y="145" textAnchor="middle" fill="#e8f5ff">→ ADC → CPU</text></svg><p>Pressure altitude: 44,330 × [1 − (p / 1013.25)^0.1903] metres</p><p>Low-speed model: v = √(2q / ρ). Density: ρ = p / (R × T).</p><p>{mode} · Inputs {values.static} hPa static / {values.dynamic} hPa dynamic</p></div>;
  if(lab.family==="flight-computer")return <svg className="adv-instrument" viewBox="0 0 420 260" role="img" aria-label="Flight guidance command and tracking output"><path d="M50 215H390M50 215V30" fill="none" stroke="#669abb"/><path d="M50 80H390" stroke="#f2c655" strokeDasharray="5 4"/><path d={`M50 190Q150 150 ${Math.min(390,50+time*17)} ${190-Math.min(110,time*8)}`} fill="none" stroke="#35baff" strokeWidth="3"/><text x="70" y="65" fill="#f2c655">Target: {mode.startsWith("Heading")?values.heading:values.target} {mode.startsWith("Heading")?"°":"ft"}</text><text x="210" y="247" textAnchor="middle" fill="#d5f1ff">Guidance: {result.visual[1]?.toFixed(1)} {mode.startsWith("Heading")?"°":"ft"}</text></svg>;
  if(lab.family==="cockpit"&&mode.startsWith("Navigation"))return <svg className="adv-instrument" viewBox="0 0 420 260" role="img" aria-label="Navigation display with heading and range"><circle cx="210" cy="135" r="105" fill="none" stroke="#7fa7bf"/><circle cx="210" cy="135" r="60" fill="none" stroke="#41617a"/><g transform={`rotate(${-(values.heading??0)} 210 135)`}><path d="M210 135L170 85L245 45" transform={`translate(210 135) scale(${100/(values.mapRange??100)}) translate(-210 -135)`} fill="none" stroke="#da5dfa" strokeWidth="3"/>{(values.weather??0)>0&&<g fill={values.weather===2?"#edc856":"#41c87b"} opacity=".7"><ellipse cx="240" cy="90" rx="23" ry="14"/><ellipse cx="255" cy="78" rx="17" ry="12"/><ellipse cx="165" cy="150" rx="18" ry="10"/></g>}<text x="210" y="40" fill="white">N</text><text x="305" y="135" fill="white">E</text><text x="210" y="235" fill="white">S</text><text x="105" y="135" fill="white">W</text></g><path d="M210 120l-9 22 9-5 9 5Z" fill="#fff"/><text x="210" y="257" fill="#d5f1ff" textAnchor="middle">HDG {values.heading}° · {values.mapRange??100} NM · schematic route</text></svg>;
  if(lab.family==="cockpit"&&mode.startsWith("Engine"))return <div className="adv-engine-display"><strong>ENGINE CHANNELS — teaching values</strong>{[["N1",92.1,"%"],["EGT",685,"°C"],["Fuel flow",5120,"kg/h"]].map(([label,value,unit])=><div key={label}><span>{label}</span><meter min="0" max={label==="N1"?100:label==="Fuel flow"?10000:1000} value={Number(value)}/><output>{value} {unit}</output></div>)}<p>Engine channels are fixed teaching inputs; aircraft attitude controls do not represent engine commands.</p></div>;
  if(["cockpit","pfd","fly-by-wire","flight-computer"].includes(lab.family))return <svg className="adv-instrument" viewBox="0 0 420 260" role="img" aria-label={`Virtual ${mode} flight indication`}><defs><clipPath id={`adv-horizon-${lab.number}`}><rect x="85" y="20" width="250" height="190" rx="12"/></clipPath></defs><g clipPath={`url(#adv-horizon-${lab.number})`}><g transform={`rotate(${-(lab.family==="fly-by-wire"?result.visual[0]??0:values.roll??0)} 210 115) translate(0 ${(lab.family==="fly-by-wire"?result.visual[1]??0:values.pitch??0)*3})`}><rect x="-100" y="-180" width="650" height="300" fill="#207aa3"/><rect x="-100" y="120" width="650" height="350" fill="#765032"/><path d="M-100 120H550" stroke="white" strokeWidth="3"/>{[-40,-20,20,40].map(y=><path key={y} d={`M175 ${120+y}h70`} stroke="white"/>)}</g></g><path d="M140 115h55l15 8 15-8h55" fill="none" stroke="#ffd34f" strokeWidth="4"/><text x="12" y="110" fill="#d5f1ff">{values.speed??0} kt</text><text x="342" y="110" fill="#d5f1ff">{values.altitude??0}</text><text x="210" y="235" textAnchor="middle" fill="#d5f1ff">HDG {values.heading??0}° · virtual indication</text></svg>;
  if(lab.family==="gps")return <svg className="adv-instrument" viewBox="0 0 420 260" role="img" aria-label="Virtual GNSS satellite sky geometry"><g fill="none" stroke="#377b9e">{[100,65,30].map(r=><circle key={r} cx="210" cy="125" r={r}/>)}<path d="M110 125H310M210 25v200"/></g>{Array.from({length:values.satellites??0},(_,i)=><g key={i}><circle cx={210+Math.sin(i*2.4)*((i*23)%80+15)} cy={125+Math.cos(i*2.4)*((i*23)%80+15)} r="7" fill={i%3===0?"#f4c84d":"#48daaa"}/><text x={220+Math.sin(i*2.4)*((i*23)%80+15)} y={125+Math.cos(i*2.4)*((i*23)%80+15)} fill="#c6e6fa" fontSize="10">{i+1}</text></g>)}<text x="210" y="20" fill="#d5f1ff" textAnchor="middle">N</text><text x="210" y="253" fill="#d5f1ff" textAnchor="middle">Illustrative satellite distribution</text><text x="12" y="230" fill="#c6e6fa" fontSize="11">Tracked: {values.satellites} · C/N₀: {values.strength} dB-Hz</text><text x="12" y="246" fill="#c6e6fa" fontSize="11">Uncertainty: {result.metrics.find(m=>m.label==="Position uncertainty example")?.value} m</text></svg>;
  if(lab.family==="centrifuge")return <div className="adv-separation"><svg viewBox="0 0 170 220" role="img" aria-label="Illustrative density separation in a sample tube"><defs><clipPath id="adv-tube"><path d="M48 30h74v150a37 37 0 0 1-74 0Z"/></clipPath></defs><g clipPath="url(#adv-tube)"><rect x="48" y="30" width="74" height="190" fill="#913948"/><rect x="48" y="30" width="74" height={result.progress*110} fill="#e7c557"/><rect x="48" y={30+result.progress*110} width="74" height={result.progress*7} fill="#f1e4bd"/></g><path d="M48 30h74v150a37 37 0 0 1-74 0Z" fill="none" stroke="#c6e4f7" strokeWidth="3"/><rect x="43" y="15" width="84" height="25" rx="5" fill="#2886dc"/></svg><div><strong>{(result.progress*100).toFixed(1)}% illustrative separation</strong><p>{mode} · density layers</p><small>Sample-specific kinetics are simplified.</small></div></div>;
  if(lab.family==="chemistry")return <svg className="adv-instrument" viewBox="0 0 420 220" role="img" aria-label="Photometric light path"><circle cx="40" cy="105" r="23" fill="#f7ce58"/><rect x="140" y="40" width="90" height="140" rx="7" fill="#2c7c9b" stroke="#88daf5"/><path d="M65 105H140" stroke="#ffdc63" strokeWidth="8"/><path d="M230 105H350" stroke="#ffdc63" strokeWidth={Math.max(1,8*10**(-(result.visual[0]??0)))}/><rect x="350" y="82" width="35" height="48" fill="#2b584e" stroke="#63d6a8"/><text x="185" y="205" textAnchor="middle" fill="#baddef">Cuvette · absorbance {result.visual[0]?.toFixed(3)}</text></svg>;
  if(lab.family==="hematology")return <svg className="adv-instrument" viewBox="0 0 420 220" role="img" aria-label="Illustrative white-cell scattergram"><path d="M35 15v175h360" fill="none" stroke="#799dbb"/>{["#26adff","#42db7b","#fab748","#d570ed","#ec648a"].map((color,k)=><g key={color}>{Array.from({length:Math.max(1,Math.round((result.visual[1]??6.8)/6.8*225*[.55,.30,.09,.05,.01][k]!))},(_,i)=><circle key={i} cx={85+k*53+Math.cos(i*2.399963+time*.02)*Math.sqrt(((i*37)%101)/100)*23} cy={160-k*22+Math.sin(i*2.399963+time*.02)*Math.sqrt(((i*37)%101)/100)*28} r="1.5" fill={color}/>)}</g>)}<text x="190" y="212" fill="#baddef">Forward scatter →</text><text x="8" y="105" fill="#baddef" transform="rotate(-90 8 105)">Side scatter</text></svg>;
  return <svg className="adv-instrument" viewBox="0 0 420 220" role="img" aria-label="Inertial estimated trajectory"><path d="M35 190H400M35 190V20" fill="none" stroke="#456b83"/><path d={`M35 190Q160 ${160-(values.acceleration??0)*30} 365 ${100-(values.rotation??0)*2}`} fill="none" stroke="#36baff" strokeWidth="3"/><circle cx={35+Math.min(time*8,330)} cy={190-Math.min(time*2,80)} r="7" fill="#efca53"/><text x="190" y="212" fill="#baddef">Illustrative navigation trajectory</text></svg>;
}

function GPSMap({image,values,time,valid,zoom,onZoom}:{image:string;values:Record<string,number>;time:number;valid:boolean;zoom:number;onZoom:(zoom:number)=>void}) {
  const distance=(values.speed??128)*time/3600;
  const radians=(values.heading??267)*Math.PI/180;
  const longitudeDelta=distance/(60*Math.cos(37.6213*Math.PI/180))*Math.sin(radians);
  const latitudeDelta=distance/60*Math.cos(radians);
  return <div className="adv-live-map"><div className="adv-map-viewport"><div style={{transform:`scale(${zoom})`}}><img src={image} alt="San Francisco Bay geographic reference with KSFO and KOAK"/><svg viewBox="0 0 400 180" aria-label="Simulated aircraft position on the reference map"><circle cx="210" cy="96" r="17" fill="#164853"/><path d="M192 107L226 88" stroke="#49dc35" strokeWidth="2"/><g transform={`translate(${102+((values.waypointLongitude??-122.2216)+122.3790)*1353} ${146-((values.waypointLatitude??37.7213)-37.6213)*1210})`}><circle r="5" fill="#42baf5" stroke="white"/><text x="8" y="-8" fill="white" fontSize="9">Waypoint</text></g>{valid&&<g transform={`translate(${102+longitudeDelta*1353} ${146-latitudeDelta*1210}) rotate(${values.heading??267})`}><path d="M0 -14L-5 2l-12 5v4l13-3-1 8 5-3 5 3-1-8 13 3V7L5 2Z" fill="white" stroke="#10436b"/></g>}</svg></div></div><div className="adv-map-zoom"><button aria-label="Map zoom in" disabled={zoom>=2.5} onClick={()=>onZoom(Math.min(2.5,zoom+.25))}>+</button><button aria-label="Map zoom out" disabled={zoom<=1} onClick={()=>onZoom(Math.max(1,zoom-.25))}>−</button></div><small>Illustrative map projection · {zoom.toFixed(2)}×</small></div>;
}

function ChemistryFluidics({values,result}:{values:Record<string,number>;result:AdvancedResult}) {
  return <svg viewBox="0 0 480 280" role="img" aria-label="Sample and reagent pump paths into a reaction cuvette"><circle cx="70" cy="130" r="55" fill="#10354c" stroke="#40b9ff"/>{Array.from({length:8},(_,i)=><circle key={i} cx={70+Math.cos(i*Math.PI/4)*35} cy={130+Math.sin(i*Math.PI/4)*35} r="7" fill="#dd5478"/>)}<text x="70" y="207" textAnchor="middle" fill="#d5efff" fontSize="12">Sample carousel</text><path d="M70 110V40H245V110" fill="none" stroke="#ed756d" strokeWidth="3"/><text x="75" y="25" fill="#ed756d" fontSize="12">Sample probe · {values.volume} µL</text>{[0,1,2,3].map(i=><g key={i}><rect x={140+i*38} y="205" width="25" height="42" rx="4" fill="#cfe2ed"/><rect x={145+i*38} y="194" width="15" height="12" fill="#4387ad"/><text x={153+i*38} y="235" textAnchor="middle" fill="#103449" fontSize="11">R{i+1}</text><path d={`M${153+i*38} 194V173H245V148`} fill="none" stroke="#66c86d"/></g>)}<circle cx="245" cy="130" r="20" fill="#143c56" stroke="#47baff"/><path d="M235 130l17-10v20Z" fill="#47baff"/><text x="245" y="162" textAnchor="middle" fill="#d5efff" fontSize="11">Metering pump</text><path d="M265 130H355" stroke="#f8c458" strokeWidth="3"/><rect x="350" y="82" width="50" height="90" rx="5" fill={result.valid?"#3d7994":"#662433"} stroke="#98d5ee"/><text x="375" y="197" textAnchor="middle" fill="#d5efff" fontSize="12">Reaction cuvette</text><text x="375" y="220" textAnchor="middle" fill="#f8c458" fontSize="11">{values.temperature} °C</text><path d="M400 130H445V55" fill="none" stroke="#5ba5e2" strokeWidth="3"/><rect x="424" y="16" width="42" height="48" rx="5" fill="#315067" stroke="#a5c4d6"/><text x="444" y="81" textAnchor="middle" fill="#d5efff" fontSize="11">Waste</text><text x="210" y="273" textAnchor="middle" fill="#9bbdd5" fontSize="11">Sample • reagent • mixed reaction • controlled waste path</text></svg>;
}

function Quiz({lab}:{lab:AdvancedLab}) {
  const [answers,setAnswers]=useState<Record<number,number>>({}),[questionIndex,setQuestionIndex]=useState(0);
  const questions=[{q:lab.quiz[0],options:lab.quiz.slice(1),correct:0,why:lab.principle},{q:`What follows “${lab.steps[1]?.[0]}”?`,options:[lab.steps[2]?.[0]??"Process input",lab.steps.at(-1)![0],lab.steps[0]![0]],correct:0,why:lab.steps[2]?.[1]??lab.principle},{q:"What should happen when a required input fails?",options:["Flag the affected output as invalid","Keep a valid result without warning","Ignore all validity checks"],correct:0,why:lab.safety[0]!}];
  const shownQuestions=questions;
  return <Panel name="quiz" title="Quick Quiz"><p>Question {questionIndex+1} / {shownQuestions.length} · {Object.values(answers).filter(v=>v===0).length} correct</p>{shownQuestions.map((q,i)=>i===questionIndex&&<fieldset key={i}><legend>{i+1}. {q.q}</legend>{q.options.map((option,j)=><button key={j} aria-pressed={answers[i]===j} className={answers[i]===j?(j===q.correct?"adv-correct":"adv-incorrect"):""} onClick={()=>setAnswers(a=>({...a,[i]:j}))}>{option}</button>)}{answers[i]!==undefined&&<p role="status">{answers[i]===q.correct?"Correct. ":"Try again. "}{q.why}</p>}</fieldset>)}{shownQuestions.length>1&&<div className="adv-quiz-navigation"><button disabled={questionIndex===0} onClick={()=>setQuestionIndex(i=>i-1)}>Previous</button><button disabled={questionIndex>=shownQuestions.length-1||answers[questionIndex]!==0} onClick={()=>setQuestionIndex(i=>i+1)}>Next question</button></div>}<button onClick={()=>{setAnswers({});setQuestionIndex(0);}}>Retry quiz</button></Panel>;
}

function AdvancedFirstBatchPage({lab}:{lab:AdvancedLab}) {
  const [values,setValues]=useState(()=>initialAdvancedValues(lab)),[mode,setMode]=useState(itemAt(lab.modes,0)!),[running,setRunning]=useState(false),[time,setTime]=useState(0),[fault,setFault]=useState(false),[step,setStep]=useState(0),[selected,setSelected]=useState(0),[view,setView]=useState("Internal"),[query,setQuery]=useState(""),[menu,setMenu]=useState(false),[walkthrough,setWalkthrough]=useState(false),[mapZoom,setMapZoom]=useState(1),[waypoint,setWaypoint]=useState("37.7213, -122.2216"),[waypointError,setWaypointError]=useState("");
  useEffect(()=>{if(!running)return;const timer=setInterval(()=>setTime(t=>lab.family==="centrifuge"?Math.min(12,t+.1):t+.1),100);return()=>clearInterval(timer);},[running,lab.family]);
  const result=useMemo(()=>simulateAdvanced(lab,values,mode,time,fault),[lab,values,mode,time,fault]);
  useEffect(()=>{if(running&&(!result.valid||(lab.family==="centrifuge"&&time>=12)))setRunning(false);},[running,result.valid,lab.family,time]);
  const asset=(role:string)=>GENERATED_DEVICE_ART[lab.number]?.[role]??`/device-labs/advanced/${String(lab.number).padStart(3,"0")}-${role}.webp?v=3`;
  const reset=()=>{setValues(initialAdvancedValues(lab));setMode(itemAt(lab.modes,0)!);setTime(0);setRunning(false);setFault(false);setStep(0);setMapZoom(1);setWalkthrough(false);setWaypoint("37.7213, -122.2216");setWaypointError("");};
  useEffect(()=>{if(!walkthrough)return;const timer=setTimeout(()=>{if(step>=lab.steps.length-1)setWalkthrough(false);else setStep(s=>s+1);},1200);return()=>clearTimeout(timer);},[walkthrough,step,lab.steps.length]);
  const activeStep=lab.family==="centrifuge"&&time>0&&!walkthrough?Math.min(lab.steps.length-1,Math.floor(time*.6)):running?Math.floor(time*1.5)%lab.steps.length:step;
  const links=[...LABS.map(l=>({number:l.number,name:l.device.name,path:labPath(l)})),...ADVANCED_LABS.map(l=>({number:l.number,name:l.device.name,path:advancedPath(l)}))].filter(l=>`${l.number} ${l.name}`.toLowerCase().includes(query.toLowerCase()));
  const hasSidebar=[55,56,60,61,63].includes(lab.number);
  const device=<Panel name="device" title={lab.number===56?"The Instrument":"External Parts / Real Device"}><img src={asset(view==="External"?"external":"device")} alt={`${lab.device.name} real equipment and external parts`}/><p>{lab.device.shortDescription}</p><button onClick={()=>{setView("External");document.getElementById("advanced-internal")?.scrollIntoView({behavior:"smooth"});}}>Explore external parts →</button></Panel>;
  const external=lab.number===55?<Panel name="external" title="External Parts"><img src={asset("external")} alt="Centrifuge lid, rotor chamber and control panel"/><p>Lid interlock • rotor chamber • control panel • power connection</p></Panel>:null;
  const internal=<Panel name="internal" title="Internal Components (Exploded View)">{lab.number===59&&<p>Inspect actuator and circuit components</p>}<div className="adv-tabs">{["External","Internal","Circuit"].map(v=><button key={v} aria-pressed={view===v} onClick={()=>setView(v)}>{v}</button>)}</div>{view==="Circuit"?<Architecture lab={lab} selected={selected}/>:lab.number===57&&view==="Internal"?<div className="adv-chem-hardware"><img src={asset("internal")} alt="Chemistry analyzer carousel, reagent and electronics assemblies"/><aside><h3>Optical System (Close-up)</h3><img src={asset("optical")} alt="Lamp, lenses, filter, cuvette and detector optical path"/></aside></div>:<img src={asset(view==="External"?"external":"internal")} alt={`${lab.device.name} ${view.toLowerCase()} hardware`}/>}<details><summary>Inspect component functions</summary><div className="adv-part-list">{lab.parts.map((part,i)=><button key={part} aria-pressed={selected===i} onClick={()=>setSelected(i)}>{i+1}. {part}</button>)}</div>{GENERATED_PART_ART[lab.number]?.[lab.parts[selected]!]&&<GeneratedPartView name={lab.parts[selected]!} src={GENERATED_PART_ART[lab.number]![lab.parts[selected]!]!}/>}<p>{componentFunction(lab.parts[selected]!)}</p></details></Panel>;
  const architecture=<Panel name="architecture" title={lab.number===62?"Formulas / ISA Reference":"System Architecture / Circuit"}>{lab.number===62?<div className="adv-formulas"><p><strong>Indicated airspeed (low-speed model)</strong><br/>q = total pressure − static pressure<br/>IAS = √(2q / ρ₀)</p><p><strong>True airspeed</strong><br/>TAS = √(2q / ρ), where ρ = p / (R × T)</p><p><strong>Pressure altitude</strong><br/>h = 44,330 × [1 − (p / 1013.25)<sup>0.1903</sup>] m</p><p><strong>ISA sea-level reference</strong><br/>1013.25 hPa · 15°C · 1.225 kg/m³</p></div>:<Architecture lab={lab} selected={activeStep}/ >}</Panel>;
  const steps=<Panel name="steps" title={`How It Works — ${lab.steps.length} Steps`}><ol>{lab.steps.map(([title,description],i)=><li key={title}><button aria-pressed={activeStep===i} onClick={()=>{setRunning(false);setWalkthrough(false);setStep(i);}}><span>{i+1}</span><strong>{title}</strong></button>{lab.number===64&&<GPSStageIcon stage={i}/>}{(lab.number===55||(lab.number===57&&i<4))&&<img src={asset(`stage${i+1}`)} alt={`${title} device hardware`}/>}{lab.number===57&&i===4&&<svg viewBox="0 0 150 95" role="img" aria-label="Illustrative absorbance calibration"><path d="M20 10v65h115" fill="none" stroke="#7ba1bf"/><path d="M20 75L125 15" stroke="#43bcff" strokeWidth="2"/><text x="65" y="90" fill="#b8dcef" fontSize="8">Concentration →</text><text x="5" y="40" fill="#b8dcef" fontSize="10">A</text></svg>}{lab.number===57&&i===5&&<div className="adv-mini-result">{mode.split(" ")[0]}<strong>{result.valid?result.metrics[1]?.value:"Invalid"}</strong><small>Relative teaching value</small></div>}<p>{description}</p></li>)}</ol></Panel>;
  const flow=<Panel name="flow" title={lab.number===57?"Simplified System Schematic":lab.number===63?"INS in Aircraft Navigation":lab.number===62?"Connections / Aircraft Inputs":"Input → Processing → Output"}>{lab.number===57?<ChemistryFluidics values={values} result={result}/>:lab.number===62?<AirDataConnections/>:lab.number===63?<><img src={asset("context")} alt="Aircraft inertial navigation equipment context"/><p>Angular rate → attitude; specific force → velocity and position. Navigation data is passed to flight-management and display systems.</p></>:<div className="adv-flow-stages">{(lab.number===62?[["Pitot","Total pressure from the pitot line"],["Static","Ambient pressure from static ports"],["Temperature","Outside-air temperature measurement"]]:lab.number===55?[["Input","Sample tubes with liquid mixture"],["Processing","High-speed rotation controlled by motor and electronics"],["Output","Components separated into density layers"]]:lab.number===56?[["Whole blood","Anticoagulated sample"],["Dilution & reagents","Prepare cells for detection"],["Sensing & counting","Impedance and optical channels"],["CBC results","Counts, indices and quality flags"]]:[["Input",lab.steps[0]![0]],["Processing",lab.steps.slice(1,-1).map(s=>s[0]).join(" → ")],["Output",lab.steps.at(-1)![0]]]).map(([name,text],i)=><div key={name}>{lab.number===56?<img src={asset(`flow${i}`)} alt={`${name} blood-analysis stage`}/>:<span>{["◉","▣","▤"][i]}</span>}<strong>{name}</strong><p>{text}</p>{lab.number===55&&<img src={asset(["input","rotor","output"][i]!)} alt={`${name} centrifugation illustration`}/>}</div>)}</div>}</Panel>;
  const controls=<Panel name="controls" title="Interactive Simulation"><label className="adv-mode">{lab.family==="centrifuge"?"Sample type":"Operating scenario"}<select value={mode} onChange={e=>setMode(e.target.value)}>{lab.modes.map(m=><option key={m}>{m}</option>)}</select></label>{lab.controls.map(c=><label className="adv-control" key={c.key}><span>{c.label}<output>{values[c.key]} {c.unit}</output></span><input aria-label={c.label} type="range" min={c.min} max={c.max} step={c.step} value={values[c.key]} onChange={e=>setValues(v=>({...v,[c.key]:Number(e.target.value)}))}/><small>{c.min} — {c.max} {c.unit}</small></label>)}{lab.number===60&&<div className="adv-cockpit-options"><label>Weather layer<select value={values.weather??0} onChange={e=>{setValues(v=>({...v,weather:Number(e.target.value)}));setMode("Navigation display");}}><option value="0">None</option><option value="1">Synthetic precipitation</option><option value="2">Synthetic strong returns</option></select></label><label>Map range<select value={values.mapRange??100} onChange={e=>{setValues(v=>({...v,mapRange:Number(e.target.value)}));setMode("Navigation display");}}>{[25,50,100,200].map(range=><option key={range} value={range}>{range} NM</option>)}</select></label></div>}{lab.number===64&&<label className="adv-waypoint">Set waypoint (latitude, longitude)<input aria-label="Waypoint latitude and longitude" value={waypoint} onChange={e=>{setWaypoint(e.target.value);const fields=e.target.value.split(",").map(s=>s.trim());const lat=Number(fields[0]),lon=Number(fields[1]);if(fields.length===2&&fields.every(Boolean)&&Number.isFinite(lat)&&Number.isFinite(lon)&&Math.abs(lat)<=90&&Math.abs(lon)<=180){setValues(v=>({...v,waypointLatitude:lat,waypointLongitude:lon}));setWaypointError("");}else setWaypointError("Waypoint not applied: enter latitude −90…90, longitude −180…180.");}}/ >{waypointError&&<small role="alert">{waypointError}</small>}</label>}<div className="adv-actions"><button className="adv-primary" disabled={!result.valid} onClick={()=>{setWalkthrough(false);if(lab.family==="centrifuge"&&time>=12)setTime(0);setRunning(v=>!v);}}>{running?"Ⅱ Pause":"▶ Run Simulation"}</button><button onClick={reset}>Reset</button></div><label className="adv-fault"><input type="checkbox" checked={fault} onChange={e=>setFault(e.target.checked)}/>{lab.number===64?"Enable interference / jamming":"Inject component fault"}</label><p className="adv-status" data-valid={result.valid} role="status">{result.status}</p><small>{running?"Running":"Paused"} · {time.toFixed(1)} s</small>{lab.number===55&&<p>Estimated RCF: <strong>{result.valid?result.metrics[0]?.value:"Unavailable"} × g</strong></p>}</Panel>;
  const signals=<Panel name="signals" title={lab.number===64?"Live Map & Route":"Results & Graphs (Simulated)"}>{lab.number===64&&<GPSMap image={asset("map")} values={values} time={time} valid={result.valid} zoom={mapZoom} onZoom={setMapZoom}/ >}{lab.number===56&&<InstrumentVisual lab={lab} result={result} values={values} time={time} mode={mode}/>} {(lab.number===64?[]:lab.number===55?result.traces.slice(0,1):lab.number===63?result.traces.filter(t=>t.label!=="Position drift"):result.traces).map(t=>lab.number===56?<CellHistogram key={t.label} trace={t}/>:[59,63].includes(lab.number)?<DeviceResponseTrace key={t.label} trace={t} time={time}/>:<TimedSignal key={t.label} trace={t} time={time}/>)}{[55,63].includes(lab.number)&&<InstrumentVisual lab={lab} result={result} values={values} time={time} mode={mode}/>}</Panel>;
  const visual=<Panel name="visual" title={lab.family==="gps"?"Satellite Geometry (Sky View)":lab.family==="pfd"?"The PFD at a Glance":"Live System View"}>{lab.number===60?<div className="adv-display-examples">{["Primary flight display","Altitude tape","Navigation display","Engine display"].map(display=><figure key={display} data-active={mode===display}><InstrumentVisual lab={lab} result={result} values={values} time={time} mode={display}/><figcaption>{display}</figcaption></figure>)}</div>:lab.number===61?<div className="adv-pfd-hardware"><img src={asset("display")} alt="Primary flight display bezel and controls"/><div><InstrumentVisual lab={lab} result={result} values={values} time={time} mode={mode}/></div></div>:<InstrumentVisual lab={lab} result={result} values={values} time={time} mode={mode}/>}</Panel>;
  const drift=lab.number===63?<Panel name="drift" title="Drift & Error Behavior">{result.traces.filter(t=>t.label==="Position drift").map(t=><DeviceResponseTrace key={t.label} trace={t} time={time}/>)}<p>Constant accelerometer bias integrates twice. GNSS aiding attenuates bias in this educational model.</p></Panel>:null;
  const advantages=lab.number===60?<Panel name="advantages" title="Advantages"><ul><li>Improved situational awareness</li><li>Integrated flight information</li><li>Reduced instrument clutter</li><li>Reconfigurable display views</li><li>Support for navigation and alerting functions</li></ul></Panel>:null;
  const inputs=lab.number===61?<Panel name="inputs" title="Sensors & Data Inputs"><ul><li>AHRS — attitude, rate and heading</li><li>Air Data Computer — airspeed, altitude and vertical speed</li><li>GPS / FMS — position, track and navigation guidance</li><li>Avionics buses — validated source data and status</li></ul></Panel>:null;
  const explanation=lab.number===61?<Panel name="explanation" title="PFD Elements Explained"><dl>{[["Attitude indicator","Shows pitch and roll relative to the horizon."],["Airspeed tape","Current airspeed with scale marks."],["Altitude tape","Current altitude with scale marks."],["Heading indicator","Aircraft heading and navigation orientation."],["Vertical speed","Rate of climb or descent."],["Annunciations","Mode labels are illustrative; no autopilot is connected."]].map(([label,text])=><div key={label}><dt>{label}</dt><dd>{text}</dd></div>)}</dl></Panel>:null;
  const readout=<Panel name="readout" title={lab.number===64?"Navigation Output (PVT)":lab.number===56?"CBC Results (Simulated)":"Calculated Outputs"}>{lab.number===56?<CBCResults result={result}/>:lab.number===62?<AirDataGauges result={result}/>:<dl>{result.metrics.filter(m=>lab.number!==64||!["Tracked satellites","Position uncertainty example"].includes(m.label)).map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value} <small>{m.unit}</small></dd></div>)}</dl>}{lab.number===62&&<div className="adv-airdata-traces">{result.traces.map(t=><TimedSignal key={t.label} trace={t} time={time}/>)}</div>}</Panel>;
  const applications=<Panel name="applications" title="Real-World Applications"><ul>{lab.applications.map(a=><li key={a}>{a}</li>)}</ul></Panel>;
  const safety=<Panel name="safety" title="Safety / Limitations"><ul>{lab.safety.map(s=><li key={s}>{s}</li>)}</ul>{lab.number===59&&<div className="adv-fbw-context"><div><h3>Real-World Applications</h3><ul>{lab.applications.map(a=><li key={a}>{a}</li>)}</ul></div><div><h3>Key Takeaways</h3><p>{lab.principle}</p></div></div>}</Panel>;
  const takeaways=<Panel name="takeaways" title="Key Takeaways">{lab.number===55?<ul><li>Rotation separates components according to density.</li><li>RCF increases with rotor radius and the square of RPM.</li><li>Balanced tubes reduce vibration and protect the rotor.</li><li>The lid remains locked until rotation stops.</li><li>Separation also depends on sample, medium and time.</li></ul>:lab.number===61?<ul><li>Air data, attitude and navigation share one display.</li><li>Pitch and bank move the artificial horizon.</li><li>Speed and altitude keep separate scales and units.</li><li>Heading helps the pilot interpret flight direction.</li><li>Invalid source data must be visibly flagged.</li></ul>:<><p>{lab.principle}</p><p>Inputs: {lab.steps[0]![0]}. Output: {lab.steps.at(-1)![0]}.</p></>}{[57,62].includes(lab.number)&&<div data-course-kind="quiz"><Quiz lab={lab}/></div>}</Panel>;
  return <div className={`advanced-lab adv-${lab.theme} adv-lab-${lab.number} ${hasSidebar?"adv-with-sidebar":""}`} data-lab={lab.number}>
    <header className="adv-topbar"><Link to={STUDIO_PATH} className="adv-brand">{lab.device.category==="medical"?"⚗":"✈"} <strong>Device {lab.number}</strong><small>Real Devices. Deeper Understanding.</small></Link><input aria-label="Search devices" placeholder="Search labs, components, or topics…" value={query} onChange={e=>{setQuery(e.target.value);setMenu(true);}}/><nav><Link to={STUDIO_PATH}>Studio Home</Link><button onClick={()=>setMenu(v=>!v)}>All Devices</button><a href="#advanced-controls">Simulate</a><a href="#advanced-quiz">Quiz</a></nav></header>
    {menu&&<nav className="adv-menu" aria-label="Lab search results"><button onClick={()=>setMenu(false)}>Close lab list</button>{links.map(l=><Link key={l.number} to={l.path}>Device {l.number} — {l.name}</Link>)}{!links.length&&<p>No matching labs.</p>}</nav>}
    {hasSidebar&&<aside className="adv-sidebar"><Link to={STUDIO_PATH}>⌂ Studio Home</Link><strong>{lab.device.name}</strong>{[["device","External Parts"],["internal","Internal Components"],["steps","How It Works"],["architecture","System Architecture"],["controls","Interactive Simulator"],["applications","Applications"],["safety","Safety & Limitations"],["quiz","Quiz"]].map(([id,label])=><a key={id} href={`#advanced-${id}`}>{label}</a>)}<p>Measure.<br/>Understand.<br/>Build a smarter tomorrow.</p></aside>}
    <main className="adv-main"><DeviceCourse lab={lab} onTabChange={tab=>{if(tab!=="simulation")setRunning(false);}}><section className="adv-hero"><div><span>DEVICE {lab.number} · {lab.device.category.toUpperCase()}</span><h1>{lab.number===55?`Device 55 — ${lab.device.name}`:lab.device.name}</h1><p>{lab.subtitle}</p><div className="adv-actions"><a className="adv-primary" href="#advanced-controls">Start Simulation →</a><button aria-pressed={walkthrough} onClick={()=>{if(walkthrough){setWalkthrough(false);}else{setRunning(false);setStep(0);setWalkthrough(true);document.getElementById("advanced-steps")?.scrollIntoView({behavior:"smooth"});}}}>{walkthrough?"Ⅱ Pause overview":"▷ Watch overview"}</button></div></div>{![55,58].includes(lab.number)&&<img src={asset("hero")} alt={`${lab.device.name} in context`}/>}</section>{lab.number===58&&<p className="adv-source-note">The supplied reference is a recovered component thumbnail. Its artwork is retained; no complete page layout was supplied.</p>}<div className="adv-dashboard">{device}{external}{internal}{inputs}{![59,60,61].includes(lab.number)&&flow}{![56,61].includes(lab.number)&&architecture}{steps}{controls}{explanation}{![60,61,62].includes(lab.number)&&signals}{![55,56,57,62,63].includes(lab.number)&&visual}{![55,59,60,61].includes(lab.number)&&readout}{lab.number!==59&&applications}{drift}{advantages}{safety}{lab.number!==59&&takeaways}{![57,62].includes(lab.number)&&<div data-course-kind="quiz"><Quiz lab={lab}/></div>}</div><footer><Link to={STUDIO_PATH}>← Back to How Devices Work</Link><span>Device {lab.number} · Educational engineering model</span><a href={lab.source} target="_blank" rel="noreferrer">Engineering reference ↗</a></footer></DeviceCourse></main>
  </div>;
}




























export default function AdvancedLabPage({lab}:{lab:AdvancedLab}){return lab.number>=135?<HouseholdLabPage lab={lab}/>:lab.number>=125?<ConsumerLabPage lab={lab}/>:lab.number>=115?<RoboticsLabPage lab={lab}/>:lab.number>=105?<ControlLabPage lab={lab}/>:lab.number>=95?<MarineLabPage lab={lab}/>:lab.number>=85?<SecurityLabPage lab={lab}/>:lab.number>=75?<SystemsLabPage lab={lab}/>:lab.number>=65?<AviationLabPage lab={lab}/>:<AdvancedFirstBatchPage lab={lab}/>;}


