export const AVIATION_COMPONENT_FUNCTIONS:Record<string,string>={
"Input signal conditioning":"Filters, protects and scales thermocouple, pressure, vibration and speed-pickup signals.",
"Analog-to-digital converters":"Sample conditioned analog inputs into digital measurement words.",
"Monitoring processor":"Filters and trends measurements, checks example limits and formats display and maintenance data.",
"Data memory":"Stores calibration, time-stamped trends and diagnostic events.",
"ARINC / CAN interface":"Formats aircraft-bus messages carrying parameter values and status.",
"Power supply":"Regulates aircraft power and filters electrical interference.",
"Power regulation":"Converts battery or external power to stable MCU and sensor supply rails.",
"IMU gyroscope / accelerometer":"Measures angular rate and specific force used by attitude estimation.",
"Barometer":"Measures ambient pressure to support relative altitude and vertical-speed estimation.",
"Flight control MCU":"Runs state estimation, attitude/rate feedback loops, motor mixing and supervision.",
"GNSS / UART interface":"Receives navigation position and velocity data through a serial interface.",
"PWM / DShot outputs":"Carry per-motor commands from the flight computer to electronic speed controllers.",
"Scanning antenna":"Directs transmitted microwave energy and collects echoes across the selected azimuth sector.",
"Transmit / receive switch":"Protects the sensitive receiver during transmission and routes returning echoes to it.",
"Microwave transmitter":"Produces the RF pulses used to illuminate precipitation.",
"Low-noise receiver":"Amplifies weak echoes, downconverts them and preserves signal-to-noise ratio.",
"Signal processor":"Estimates echo delay and strength after filtering and digital conversion.",
"Display computer":"Converts range and return strength into a colored navigation-display map.",
"Control panel":"Selects range, tilt, gain and operating mode.",
"RF synthesizer":"Generates the controlled microwave sweep used as the height-measurement reference.",
"Power amplifier":"Raises RF signal power before transmission through the antenna.",
"Transmit / receive antennas":"Transmit downward toward terrain and receive the reflected signal on separate RF paths.",
"Mixer":"Combines the transmitted reference and delayed received signal to produce their difference frequency.",
"IF filter and amplifier":"Selects and amplifies the beat-frequency band before digitization.",
"ADC":"Converts the filtered analog beat signal into digital samples for frequency estimation.",
"Height processor":"Converts measured delay or beat frequency into AGL height and validates the result.",
"Avionics interface":"Publishes measurement words, equipment status and validity to aircraft systems.",
"RF transmitter / receiver":"Generates a swept radio signal and receives the delayed terrain reflection.",
"Processor board":"Estimates propagation delay or frequency difference and calculates height above ground.",
"Transmit antenna":"Radiates the radio-altimeter measurement signal toward terrain.",
"Receive antenna":"Collects the terrain echo and feeds it to the receiver.",
"Avionics connector":"Carries aircraft power and digital height/status outputs.",
"1030 MHz receiver":"Receives interrogations from ground surveillance or airborne collision-avoidance equipment.",
"Decoder and signal processing":"Identifies interrogation pulse timing and extracts the requested surveillance mode.",
"Mode control processor":"Selects the appropriate identity, altitude or addressed response.",
"Code selector and memory":"Stores the pilot-selected octal squawk and configured aircraft identity.",
"Altitude encoder":"Supplies pressure-altitude data for altitude-reporting replies.",
"1090 MHz transmitter":"Sends formatted surveillance replies or extended-squitter broadcasts.",
"RF antenna connector":"Connects the transponder RF path to the external aircraft antenna.",
"ADS-B encoder":"Formats navigation and aircraft-state data into ADS-B messages.",
"Control processor":"Combines source data, supervises validity and schedules automatic broadcasts.",
"ARINC data interfaces":"Receive pressure altitude, identity and other avionics state over aircraft data buses.",
"GNSS receiver":"Calculates position, velocity and time and reports navigation-source integrity.",
"1030 / 1090 MHz transceiver":"Sends TCAS interrogations at 1030 MHz and receives transponder replies at 1090 MHz.",
"Signal processing":"Detects and decodes transponder replies from the received RF signals.",
"Surveillance processor":"Maintains relative aircraft tracks from surveillance measurements.",
"Threat tracking logic":"Estimates closure and vertical separation and determines encounter risk.",
"RA decision computer":"Evaluates resolution-advisory logic and, where supported, coordinates with another TCAS unit.",
"Directional antennas":"Support bearing estimation while transmitting and receiving surveillance signals.",
"Front cover and connector":"Connects aircraft power and data to the acquisition and recording electronics.",
"Shock mounts":"Reduce transmission of vibration and impact loads to protected components.",
"Data acquisition unit":"Collects aircraft parameters, validates their labels and prepares recording frames.",
"Processor and formatter":"Time-stamps and formats acquired parameters for continuous storage and later decoding.",
"Solid-state memory":"Stores recorded flight parameters in the crash-protected memory module.",
"Power backup":"Supports controlled data retention or shutdown when normal power is interrupted.",
"Underwater locator beacon":"Emits acoustic pulses after immersion to assist recovery of the recorder.",
"Thermal insulation":"Limits heat transfer into the crash-protected memory enclosure."
};
