/** Functions describe components, not their ordinal positions in the process. */
const functions: Record<string,string> = {
  "Lid lock interlock":"Confirms the lid is closed and prevents access until rotation stops.",
  "Rotor and tube holders":"Hold balanced samples at the selected distance from the rotation axis.",
  "Spindle":"Transfers motor torque to the rotor.",
  "Tachometer":"Measures rotational speed for closed-loop regulation.",
  "Brushless motor":"Converts electrical power into rotor torque.",
  "Imbalance sensor":"Detects excessive vibration caused by unequal loading.",
  "Control board":"Coordinates timing, sensor acquisition, protection and output commands.",
  "Control electronics":"Coordinate measurement channels, timing and result processing.",
  "Power supply":"Provides regulated electrical power to the instrument circuitry.",
  "Power conversion":"Converts aircraft power to the regulated rails used by computing boards.",
  "Power regulator":"Maintains the required supply voltage for electronic circuits.",
  "Cooling fan":"Moves air through the enclosure to remove heat.",
  "Sample probe":"Aspirates a measured aliquot from the sample container.",
  "Reagent pumps":"Meter and transport reagents through the fluidic paths.",
  "Fluidics manifold":"Routes samples and reagents into the required measurement channels.",
  "Mixing chamber":"Combines the sampled blood with the selected diluent or reagent.",
  "Impedance aperture":"Produces an electrical pulse when a cell displaces conducting fluid.",
  "Laser optical module":"Illuminates cells for scatter and fluorescence measurements.",
  "Photodiodes":"Convert received optical power into electrical measurement signals.",
  "Waste chamber":"Collects used sample and reagent fluid for safe disposal.",
  "Sample carousel":"Positions sample vessels at the pipetting station.",
  "Pipetting arm":"Transfers metered sample and reagent volumes into reaction vessels.",
  "Reagent tray":"Holds the assay reagents available for dispensing.",
  "Mixing system":"Homogenizes the sample and reagent mixture.",
  "Reaction cuvette":"Provides a controlled optical path through the reaction mixture.",
  "Incubator heater":"Maintains the reaction temperature required by the assay.",
  "Light source":"Supplies light for the optical measurement channel.",
  "Wavelength filter":"Selects the wavelength band used for absorbance measurement.",
  "Photodiode":"Converts transmitted light into a current for the optical front end.",
  "Avionics connectors":"Connect power and external avionics data signals to the chassis.",
  "Air-data interface":"Receives airspeed, pressure altitude and associated validity data.",
  "Inertial data interface":"Receives attitude, acceleration and angular-rate information.",
  "Processor boards":"Execute validated guidance and monitoring computations.",
  "Memory":"Stores program code, calibration data and working computation state.",
  "Data bus transceiver":"Sends and receives electrical messages on the avionics bus.",
  "Cooling chassis":"Conducts and removes heat from the installed computing electronics.",
  "Side-stick sensors":"Measure pilot control input for redundant flight-control channels.",
  "Air data sensors":"Measure atmospheric inputs used to schedule control laws.",
  "IMU":"Measures angular rates and accelerations for attitude estimation.",
  "Redundant flight computers":"Compute control demands and compare independent channels.",
  "Data buses":"Transport command, measurement and validity messages between subsystems.",
  "Actuator electronics":"Convert control demands into drive signals for the servo actuator.",
  "Servo actuator":"Moves a flight-control surface using a regulated drive command.",
  "Position feedback sensor":"Measures actuator or surface position for feedback control.",
  "LCD display":"Modulates transmitted light to display flight information.",
  "Backlight":"Illuminates the LCD panel.",
  "Graphics processor":"Transforms validated flight data into instrument graphics.",
  "Flight computer":"Processes sensor inputs and supervises display validity.",
  "ARINC data interface":"Receives and transmits avionics data words on the configured bus.",
  "Cooling assembly":"Removes heat from the display electronics.",
  "Connector panel":"Provides external power and data connections.",
  "Display screen":"Presents attitude, airspeed, altitude and navigation indications.",
  "Function keys":"Select display functions and settings.",
  "Bezel":"Supports the display and its surrounding controls.",
  "Data interface boards":"Condition and decode incoming avionics messages.",
  "Cooling and EMI shielding":"Manage heat and reduce electromagnetic interference.",
  "Pitot pressure port":"Connects total pressure from the pitot sensing line.",
  "Static pressure port":"Connects ambient static pressure from the aircraft static system.",
  "Pressure sensors":"Convert applied pressure into electrical signals.",
  "Temperature input":"Receives the air-temperature measurement used in air-data calculations.",
  "ADC":"Converts conditioned analog measurements into digital samples.",
  "ADC interface":"Transfers digitized sensor measurements to the processor.",
  "Processor board":"Calculates outputs from calibrated sensor measurements.",
  "Calibration memory":"Stores correction coefficients for the measurement channels.",
  "ARINC interface":"Exchanges calculated data and validity flags with other avionics.",
  "Gyroscope assembly":"Measures angular rate for attitude propagation.",
  "Accelerometer assembly":"Measures specific force for velocity and position integration.",
  "Data bus interface":"Transfers navigation results and receives aiding data.",
  "Rugged enclosure":"Protects electronics and provides mechanical mounting and shielding.",
  "GNSS antenna":"Receives the weak radio signals transmitted by navigation satellites.",
  "Low-noise amplifier":"Amplifies received RF signals while limiting added noise.",
  "RF filter":"Rejects signals outside the receiver passband.",
  "Downconverter":"Translates received radio signals to a frequency suitable for sampling.",
  "Reference oscillator":"Provides the receiver's local frequency and timing reference.",
  "Correlator":"Acquires and tracks satellite spreading codes and carrier signals.",
  "Navigation processor":"Solves position, velocity and receiver clock offset from measurements.",
  "Display interface":"Transfers navigation output to the user display or avionics system.",
};
export const componentFunction=(part:string)=>functions[part]??"Inspect this component in the functional architecture and the device working sequence.";
