import {parameterValue,itemAt} from './parameters';
import {encodeCode128,decodeCode128} from './code128';
import type {AdvancedLab} from './data';
import type {AdvancedResult} from './engine';
import type {Metric,Trace} from '../labs/engine';
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'];
const G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'];
const parity=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL'];
export function eanCheck(value:string){if(!/^\d{12}$/.test(value))return '';const sum=[...value].reduce((s,c,i)=>s+Number(c)*(i%2?3:1),0);return String((10-sum%10)%10);}
export function encodeEAN(value:string){if(!/^\d{13}$/.test(value)||eanCheck(value.slice(0,12))!==value[12])return '';return '101'+[...value.slice(1,7)].map((c,i)=>itemAt((itemAt(itemAt(parity, Number(value[0])), i)==='L'?L:G), Number(c))).join('')+'01010'+[...value.slice(7)].map(c=>[...itemAt(L, Number(c))].map(v=>v==='1'?'0':'1').join('')).join('')+'101';}
export function decodeEAN(bits:string){if(bits.length!==95||bits.slice(0,3)!=='101'||bits.slice(45,50)!=='01010'||bits.slice(92)!=='101')return '';let left='',scheme='',right='';for(let i=0;i<6;i++){const symbol=bits.slice(3+i*7,10+i*7),li=L.indexOf(symbol),gi=G.indexOf(symbol);if(li<0&&gi<0)return '';left+=String(li>=0?li:gi);scheme+=li>=0?'L':'G';const r=bits.slice(50+i*7,57+i*7),digit=L.indexOf([...r].map(v=>v==='1'?'0':'1').join(''));if(digit<0)return '';right+=digit;}const first=parity.indexOf(scheme);if(first<0)return '';const value=first+left+right;return eanCheck(value.slice(0,12))===value[12]?value:'';}
export function fingerprintFeatures(quality:number,offset:number){return Array.from({length:16},(_,i)=>({x:16+(i%4)*15+Math.sin(i*2.1)*offset,y:16+Math.floor(i/4)*15+Math.cos(i*1.7)*offset,angle:i*.47})).slice(0,Math.max(1,Math.round(16*quality/100)));}
export function fingerprintScore(quality:number,offset:number){const sample=fingerprintFeatures(quality,offset),reference=fingerprintFeatures(100,0);const similarity=sample.reduce((s,v,i)=>s+Math.exp(-Math.hypot(v.x-itemAt(reference, i).x,v.y-itemAt(reference, i).y)/8),0)/reference.length;return similarity*100;}
export function thermalEstimate(actual:number,ambient:number,assumedEmissivity:number,trueEmissivity=.95){const ta=actual+273.15,tr=ambient+273.15,radiance=trueEmissivity*ta**4+(1-trueEmissivity)*tr**4;return Math.max(0,(radiance-(1-assumedEmissivity)*tr**4)/assumedEmissivity)**.25-273.15;}
export function simulateConsumer(lab:AdvancedLab,p:Record<string,number>,mode:string,time:number,fault:boolean):AdvancedResult{
const metrics:Metric[]=[],traces:Trace[]=[],visual:number[]=[];let status='Ready for local interaction',valid=true,progress=clamp(time/8);
const metric=(label:string,value:number|string,unit='')=>metrics.push({label,value:typeof value==='number'?Number(value.toFixed(3)):value,unit});
const trace=(label:string,unit:string,span:number,fn:(t:number)=>number)=>traces.push({label,unit,color:'#2585df',timeSpan:span,axisLabel:`${span} s`,samples:Array.from({length:240},(_,i)=>fn(i/239*span))});
switch(lab.number){
case 125:{const residual=parameterValue(p, 'noise')/100*(1-(p.ancEnabled===0?0:parameterValue(p, 'anc')/100)),gain=parameterValue(p, 'volume')/100,bitrate=mode==='SBC'?328:mode==='AAC'?256:160;metric('Illustrative codec bitrate',bitrate,'kbps');metric('Output level',parameterValue(p, 'volume'),'%');metric('Residual noise',residual*100,'%');metric('ANC attenuation',-20*Math.log10(Math.max(.001,1-(p.ancEnabled===0?0:parameterValue(p, 'anc')/100))),'dB');metric('Test tone',parameterValue(p, 'frequency'),'Hz');trace('Mixed output sample','normalized',.02,t=>gain*(.6*Math.sin(2*Math.PI*parameterValue(p, 'frequency')*t)+residual*.3*Math.sin(2*Math.PI*120*t)));visual.push(gain,residual);status='Decoded tone + residual ambient noise · local signal model';break;}
case 126:{const steps=Math.floor(parameterValue(p, 'motion')*time/60),pulse=parameterValue(p, 'quality')/100*(.5+.15*Math.sin(time*2*Math.PI*parameterValue(p, 'heart')/60));metric('Heart rate input',parameterValue(p, 'heart'),'bpm');metric('Detected motion steps',steps);metric('Movement cadence',parameterValue(p, 'motion'),'steps/min');metric('Optical signal quality',parameterValue(p, 'quality'),'%');metric('Battery',parameterValue(p, 'battery'),'%');metric('Touch events',p.taps??0);metric('Wireless records',mode==='Sync'?p.syncs??0:0);trace('Synthetic PPG pulse','normalized',5,t=>parameterValue(p, 'quality')/100*(.5+.15*Math.sin(t*2*Math.PI*parameterValue(p, 'heart')/60)+.025*Math.sin(t*4*Math.PI*parameterValue(p, 'heart')/60)));visual.push(pulse,steps,parameterValue(p, 'heart'));status=p.battery===0?'Battery depleted — device inactive':mode==='Tap'?`${p.taps??0} touch events`:mode==='Move'?'Movement sampling active':mode==='Sync'?`${p.syncs??0} local records synchronized`:'Synthetic optical pulse sampling';if(p.battery===0)valid=false;break;}
case 127:{const coupling=Math.cos(parameterValue(p, 'alignment')*Math.PI/180)**2/(1+(parameterValue(p, 'distance')/3)**6),power=parameterValue(p, 'field')*coupling,readable=power>=15,authorized=readable&&mode==='Authorized card',tap=(p.taps??0)>0;metric('Coupled field',power,'%');metric('Card powered',readable?'Yes':'No');metric('Decoded ID',readable?'04 A1 B2 C3':'Unavailable');metric('Policy',mode);metric('Door relay',authorized&&tap?'Unlocked':'Locked');trace('Load-modulated envelope','normalized',.002,t=>readable?(1+.12*(Math.sin(t*2*Math.PI*4000)>0?1:-1)):0);visual.push(power,authorized&&tap?1:0);status=!tap?'Tap a card to apply access policy':!readable?'Insufficient coupling — no card response':authorized?'Authorized tap — door relay energized':'Access denied — relay remains locked';break;}
case 128:{const value='850045678905',bits=encodeCode128(value),effective=parameterValue(p, 'contrast')*parameterValue(p, 'light')/100*(mode==='Low contrast'?.3:1),damage=Math.max(parameterValue(p, 'damage'),mode==='Damaged symbol'?3:0),observed=effective<30?'0'.repeat(bits.length):[...bits].map((b,i)=>i>=20&&i<20+damage?(b==='1'?'0':'1'):b).join(''),decoded=decodeCode128(observed),scanned=(p.scans??0)>0;metric('Format','Code 128 B');metric('Effective optical contrast',effective,'%');metric('Decoded payload',scanned?decoded||'Read failed':'Awaiting trigger');metric('Modulo-103 checksum',scanned&&decoded?'Valid':'Not validated');trace('Optical module intensity','normalized',.02,t=>observed[Math.min(bits.length-1,Math.floor(t/.02*bits.length))]==='1'?.15:.95);visual.push(effective,damage,decoded?1:0);status=!scanned?'Press Scan to acquire the symbol':decoded?'Success — Code 128 checksum verified':'Read rejected — symbol or checksum invalid';break;}
case 129:{metric('Contrast',parameterValue(p, 'contrast'),'%');metric('Rotation',parameterValue(p, 'rotation'),'°');metric('Image decoder','jsQR / actual pixels');status='Load an example or local QR image, then scan';break;}
case 130:{const score=fingerprintScore(parameterValue(p, 'quality'),parameterValue(p, 'offset')),stage=p.stage??0,access=stage>=3&&score>=parameterValue(p, 'threshold');metric('Capture quality',parameterValue(p, 'quality'),'%');metric('Detected minutiae',stage>=2?fingerprintFeatures(parameterValue(p, 'quality'),parameterValue(p, 'offset')).length:0);metric('Match score',stage>=3?score:'Not matched','%');metric('Decision',stage<3?'Awaiting match':access?'Access granted':'Access denied');visual.push(score,access?1:0,stage);trace('Synthetic ridge contrast','normalized',1,t=>parameterValue(p, 'quality')/100*(.5+.4*Math.sin(t*2*Math.PI*16)));status=stage===0?'Place finger / Scan fingerprint':stage===1?'Synthetic fingerprint captured':stage===2?'Minutiae extracted':access?'Template match accepted':'Template match rejected';break;}
case 131:{const night=mode.startsWith('Night'),signal=clamp((parameterValue(p, 'light')+(night?45:0))*parameterValue(p, 'exposure')/1000),rate=(mode.includes('H.265')?2.5:4)*(parameterValue(p, 'quality')/75),connected=mode!=='Network disconnected',fps=connected?30*Math.min(1,parameterValue(p, 'bandwidth')/rate):0;metric('Exposure signal',signal*100,'%');metric('Encoded bitrate',rate,'Mbps');metric('Delivered frame rate',fps,'fps');metric('Network state',connected?'LAN / recording active':'Disconnected');metric('IR illumination',night?'Enabled':'Off');visual.push(signal,fps,night?1:0);trace('Frame payload estimate','Mbps',5,t=>connected?Math.min(rate,parameterValue(p, 'bandwidth'))*(.95+.05*Math.sin(t*5)):0);status=connected?'ISP / encoder / network delivery model':'No live network stream — local capture remains available';break;}
case 132:{const actual=mode==='Human Body'?36.5:mode==='Electrical Panel'?parameterValue(p, 'temperature')+20:parameterValue(p, 'temperature'),measured=thermalEstimate(actual,parameterValue(p, 'ambient'),parameterValue(p, 'emissivity'));metric('Estimated spot temperature',measured,'°C');metric('Synthetic actual temperature',actual,'°C');metric('Assumed emissivity',parameterValue(p, 'emissivity'));metric('Reflected temperature',parameterValue(p, 'ambient'),'°C');metric('Estimation error',measured-actual,'°C');visual.push(measured,actual);trace('Thermal cross-section','°C',1,t=>parameterValue(p, 'ambient')+(measured-parameterValue(p, 'ambient'))*Math.exp(-(((t-.5)*5)**2)));status='Fourth-power radiance approximation · true scene emissivity 0.95';break;}
case 133:{const stream=mode==='Streaming Wi-Fi',quality=stream?clamp(parameterValue(p, 'bandwidth')/12):1;metric('Active input',mode);metric('Panel luminance target',parameterValue(p, 'brightness'),'%');metric('Audio gain',parameterValue(p, 'volume'),'%');metric('Delivered picture quality',quality*100,'%');metric('Tuner channel',mode==='Broadcast tuner'?parameterValue(p, 'channel'):'Inactive');visual.push(parameterValue(p, 'brightness')/100,parameterValue(p, 'volume')/100,quality);trace('Display luminance','normalized',1,t=>parameterValue(p, 'brightness')/100*(.5+.45*Math.sin(t*2*Math.PI)));status=stream&&quality<1?'Bandwidth limits streaming picture quality':'Selected source routed to video and audio branches';break;}
case 134:{const unlocked=p.unlocked===1&&parameterValue(p, 'battery')>=10;metric('Latch',unlocked?'Unlocked':'Locked');metric('Door sensor',p.doorOpen===1?'Open':'Closed');metric('Battery',parameterValue(p, 'battery'),'%');metric('Failed attempts',p.failures??0);metric('Auto-lock delay',parameterValue(p, 'delay'),'s');visual.push(unlocked?1:0,parameterValue(p, 'battery'));status=parameterValue(p, 'battery')<10?'Low battery — virtual actuator inhibited':(p.failures??0)>=3?'Local lockout — Reset to restart':unlocked?'Authenticated — latch unlocked':'Locked — authentication required';break;}
default:throw new Error(`Unsupported consumer device ${lab.number}`);
}
if(fault){valid=false;status='Component fault — dependent outputs unavailable';metrics.forEach(m=>{m.value='Unavailable';m.unit='';});traces.forEach(t=>t.samples.fill(0));visual.fill(0);progress=0;}
return {metrics,traces,visual,status,valid,progress};
}


