import {parameterValue,itemAt} from './parameters';
import type {AdvancedLab} from "./data";
import type {AdvancedResult} from "./engine";
import type {Metric,Trace} from "../labs/engine";
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export function differentialPose(left:number,right:number,track:number,time:number){const velocity=(left+right)/2,yaw=(right-left)/track;return {x:Math.abs(yaw)<1e-9?velocity*time:velocity/yaw*Math.sin(yaw*time),y:Math.abs(yaw)<1e-9?0:velocity/yaw*(1-Math.cos(yaw*time)),heading:yaw*time*180/Math.PI,velocity,yaw};}
export function dpResponse(p:Record<string,number>,mode:string,time:number){
 let x=0,y=0,vx=0,vy=0,heading=180,rate=0,fx=0,fy=0,torque=0;
 const wind=18*(parameterValue(p, 'wind')*.514444)**2,current=800*(parameterValue(p, 'current')*.514444)**2,capacity=mode==="One thruster unavailable"?1800:3600,history:{time:number;x:number;y:number;heading:number;fx:number;fy:number;torque:number}[]=[];
 for(let i=0;i<=Math.ceil(time/.1);i++){
  const t=i*.1,dx=wind*.707-current,dy=wind*.707+parameterValue(p, 'waves')*350*Math.sin(t*.9),error=((parameterValue(p, 'heading')-heading+540)%360)-180;
  fx=mode==="Manual drift"?0:clamp(-dx-x*400*parameterValue(p, 'gain')-vx*600,-capacity,capacity);fy=mode==="Manual drift"?0:clamp(-wind*.707-y*400*parameterValue(p, 'gain')-vy*600,-capacity,capacity);torque=mode==="Manual drift"?0:clamp(error*70-rate*150,-capacity*.7,capacity*.7);
  if(i>0){vx+=(dx+fx-vx*120)/1000*.1;vy+=(dy+fy-vy*120)/1000*.1;x+=vx*.1;y+=vy*.1;rate+=(torque-rate*100)/800*.1;heading=(heading+rate*.1+360)%360;}
  history.push({time:t,x,y,heading,fx,fy,torque});
 }
 return history;
}
export function servoResponse(target:number,gain:number,load:number,time:number){let angle=20,velocity=0,integral=0,demand=0;const history:{time:number;angle:number;demand:number}[]=[];for(let i=0;i<=Math.ceil(time/.01);i++){const error=target-angle;integral=clamp(integral+error*.01,-150,150);demand=clamp(gain*error+integral*.6-velocity*.3,-100,100);velocity+=(demand*8-load*2-velocity*5)*.01;angle=clamp(angle+velocity*.01,0,180);history.push({time:i*.01,angle,demand});}return history;}
export function lineFollower(p:Record<string,number>,mode:string,time:number){const curvature=mode==="Curvy Track"?.45*Math.sin(time*.7):0,error=parameterValue(p, 'offset')*Math.exp(-parameterValue(p, 'gain')*time/120)+curvature/(1+parameterValue(p, 'gain')*.04),readings=Array.from({length:5},(_,i)=>Math.exp(-((i-2-error*2)**2)/.55)*parameterValue(p, 'contrast')/100*1000),sum=readings.reduce((a,b)=>a+b,0),valid=mode!=="Lost Line"&&parameterValue(p, 'contrast')>=15&&sum>50,position=valid?readings.reduce((total,v,i)=>total+v*(i-2)/2,0)/sum:0,correction=position*parameterValue(p, 'gain');return {readings:valid?readings:[0,0,0,0,0],position,valid,left:valid?clamp(parameterValue(p, 'speed')+correction,0,255):0,right:valid?clamp(parameterValue(p, 'speed')-correction,0,255):0};}
export function simulateControl(lab:AdvancedLab,p:Record<string,number>,mode:string,time:number,fault:boolean):AdvancedResult{
 const n=(k:string)=>p[k]??0,metrics:Metric[]=[],traces:Trace[]=[],visual:number[]=[];
 let valid=true,status="Synthetic control system ready",progress=clamp(time/12,0,1);
 const metric=(label:string,value:number|string,unit="")=>metrics.push({label,value:typeof value==="number"?Number(value.toFixed(3)):value,unit});
 const trace=(label:string,unit:string,color:string,span:number,fn:(t:number)=>number)=>traces.push({label,unit,color,timeSpan:span,axisLabel:`${span} s`,samples:Array.from({length:240},(_,i)=>fn(i/239*span))});
 switch(lab.family){
 case "marine-vhf":{
  const channel=mode==="DSC channel 70"?70:n("channel"),frequency=channel===70?156.525:156+.05*channel,open=n("signal")>=n("squelch"),deviation=mode==="DSC channel 70"?0:2.5*n("audio")/100;
  metric("Channel",channel);metric("Carrier frequency",frequency,"MHz");metric("Transmit power",mode==="Receive only"?0:n("power"),"W");metric("FM deviation",deviation,"kHz");metric("Squelch",open?"Open":"Muted");metric("Received level",n("signal"),"dBm");trace("Synthetic audio","relative","#2288db",.04,t=>open&&mode!=="DSC channel 70"?Math.sin(t*2*Math.PI*440)*n("audio")/100:0);trace("FM frequency deviation","kHz","#e88448",.04,t=>deviation*Math.sin(t*2*Math.PI*440));visual.push(channel,frequency,open?1:0,n("power"),deviation);status=mode==="DSC channel 70"?"Digital calling illustration — voice output inhibited":open?"Receive squelch open":"Received signal below squelch threshold";break;
 }
 case "epirb":{
  valid=n("battery")>10;const hasFix=n("satellites")>=4,selfTest=mode==="Self-test",stage=selfTest?Math.min(2,Math.floor(time/2)):Math.min(mode==="Satellite relay unavailable"?3:6,Math.floor(time/2)),messages=["Ready","Activation detected","GNSS checked","Message encoded","Satellite relay illustrated","Virtual receiving station notified","Homing / strobe illustrated"];
  metric("Beacon stage",selfTest?time>=4?"Self-test complete":"Local self-test":itemAt(messages,stage));metric("GNSS position",hasFix?"Synthetic 46.4177° N, 174.7833° E":"No fix — identifier-only message");metric("Battery charge",n("battery"),"%");metric("Satellite frequency",406,"MHz");metric("Local homing",121.5,"MHz");metric("Alert output",selfTest?"No alert in self-test":"Local illustration only");visual.push(stage,hasFix?1:0,n("battery"),selfTest?1:0);status=!valid?"Battery below teaching activation threshold":selfTest?"Self-test — no alert relay":mode==="Satellite relay unavailable"&&stage===3?"Virtual relay unavailable — message waiting":itemAt(messages,stage);progress=selfTest?Math.min(1,time/4):stage/6;break;
 }
 case "dynamic-positioning":{
  const history=dpResponse(p,mode,time),last=itemAt(history,history.length-1);metric("Position error",Math.hypot(last.x,last.y),"m");metric("Heading",last.heading,"°");metric("Surge force",last.fx,"N");metric("Sway force",last.fy,"N");metric("Yaw moment",last.torque,"Nm");metric("Wind force",18*(n("wind")*.514444)**2,"N");metric("Current force",800*(n("current")*.514444)**2,"N");visual.push(last.x,last.y,last.heading,last.fx,last.fy,last.torque);const full=dpResponse(p,mode,60);trace("Station-keeping error","m","#278bdf",60,t=>{const s=itemAt(full, Math.min(full.length-1,Math.floor(t/.1)));return Math.hypot(s.x,s.y);});status=mode==="Manual drift"?"No position correction — environmental drift":"Reduced surge / sway / yaw feedback allocation";break;
 }
 case "rov":{
  const hold=mode!=="Manual Control",depth=hold?12.4+(n("depth")-12.4)*(1-Math.exp(-time/5)):clamp(12.4+n("heave")*.01*time,0,100),heading=(102+n("yaw")*.08*time+360)%360,surge=n("surge")*.02,vertical=hold?(n("depth")-depth)*8:n("heave");metric("Depth",depth,"m");metric("Heading",heading,"°");metric("Surge speed",surge,"m/s");metric("Vertical demand",clamp(vertical,-100,100),"%");metric("Target depth",n("depth"),"m");metric("Current draw",2+Math.abs(n("surge"))*.04+Math.abs(n("yaw"))*.02+Math.abs(vertical)*.03,"A");visual.push(surge*time,depth,heading,clamp(vertical,-100,100));trace("Depth response","m","#258ce1",30,t=>hold?12.4+(n("depth")-12.4)*(1-Math.exp(-t/5)):clamp(12.4+n("heave")*.01*t,0,100));status=hold?"Pressure-feedback depth loop enabled":"Manual thruster command / telemetry";break;
 }
 case "auv":{
  const fused=mode!=="INS only",surface=mode==="Surface GNSS update",distance=n("speed")*time,drift=surface?0:n("bias")*time*(fused?.15:1),depth=surface?0:Math.min(n("depth"),time*1.5);metric("Mission distance",distance,"m");metric("Depth",depth,"m");metric("Depth limit",n("depth"),"m");metric("Position drift",drift,"m");metric("Speed",n("speed"),"m/s");metric("Inertial bias",n("bias"),"m/s");metric("GNSS",surface?"Surface fix available":"Unavailable underwater");metric("Obstacle policy",mode==="Obstacle avoidance"?"Route detour enabled":"Waypoint following");visual.push(distance,depth,drift,surface?1:0);trace("Position drift","m","#297edd",120,t=>surface?0:n("bias")*t*(fused?.15:1));status=surface?"Surface GNSS corrects accumulated position error":fused?"INS + DVL reduced velocity fusion":"Unaided inertial error accumulates";break;
 }
 case "marine-engine":{
  const cold=mode==="Cold start"||n("temperature")<40,protect=mode==="Overtemperature protection"||n("temperature")>105,throttle=n("throttle")*(protect?.5:1),pulse=(1.4+n("load")*.045+throttle*.015)*(cold?1.3:1),timing=clamp(8+n("rpm")/300-n("load")*.06-(protect?5:0),0,35),map=25+n("load")*.65,cycle=120000/n("rpm");metric("Engine speed",n("rpm"),"rpm");metric("Injector pulse width",pulse,"ms");metric("Ignition timing",timing,"° BTDC");metric("Manifold pressure",map,"kPa");metric("Throttle sensor",.5+n("throttle")*.04,"V");metric("Coolant",n("temperature"),"°C");metric("720° cycle",cycle,"ms");visual.push(n("rpm"),pulse,timing,map,throttle);trace("Crank timing","V","#238deb",.05,t=>((t*n("rpm")/60*60)%1)<.45?5:0);trace("Injector drive","V","#aa69d7",.05,t=>((t*1000)%cycle)<pulse?12:0);trace("Cam timing","V","#42a26b",.05,t=>((t*1000)%cycle)<cycle*.1?5:0);trace("Throttle position","V","#ed922c",.05,()=>.5+n("throttle")*.04);trace("Manifold pressure sensor","V","#ed6565",.05,t=>.5+map/100*4+.03*Math.sin(t*n("rpm")/60*Math.PI*2));status=protect?"Overtemperature demand limiting":cold?"Cold-start enrichment illustration":"Normal reduced fuel / ignition commands";break;
 }
 case "servo":{
  const target=mode==="Pulse-width command"?(n("pulse")-1)*180:n("angle"),pulse=mode==="Pulse-width command"?n("pulse"):1+n("angle")/180,history=servoResponse(target,n("gain"),n("load"),time),last=itemAt(history,history.length-1);metric("Target angle",target,"°");metric("Current angle",last.angle,"°");metric("Position error",target-last.angle,"°");metric("Command pulse",pulse,"ms");metric("Motor demand",last.demand,"%");metric("Opposing load",n("load"),"%");visual.push(last.angle,target,pulse,last.demand);const full=servoResponse(target,n("gain"),n("load"),8);trace("Feedback angle","°","#2189e2",8,t=>itemAt(full, Math.min(full.length-1,Math.floor(t/.01))).angle);trace("50 Hz command","V","#a867d9",.04,t=>t%.02<pulse/1000?5:0);status=Math.abs(target-last.angle)<1?"In position — feedback holding":"Servo correcting angular error";break;
 }
 case "stepper":{
  const divisor=mode==="Full Step"?1:mode==="Half Step"?2:Math.max(1,Math.round(n("microsteps"))),pulses=Math.min(n("steps"),Math.floor(n("frequency")*time)),angle=pulses*1.8/divisor*n("direction"),phase=pulses*n("direction")/divisor*Math.PI/2+Math.PI/4,currentA=n("current")*Math.cos(phase),currentB=n("current")*Math.sin(phase);metric("Commanded angle",angle,"°");metric("Pulses moved",pulses);metric("Pulse target",n("steps"));metric("Step frequency",n("frequency"),"pps");metric("Command increment",1.8/divisor,"°");metric("Phase A current",currentA,"A");metric("Phase B current",currentB,"A");metric("Direction",n("direction")>0?"CW":"CCW");visual.push(angle,pulses,currentA,currentB,divisor);trace("Phase A current","A","#e35b55",.04,t=>n("current")*Math.cos(Math.floor(t*n("frequency"))*n("direction")/divisor*Math.PI/2+Math.PI/4));trace("Phase B current","A","#258ce8",.04,t=>n("current")*Math.sin(Math.floor(t*n("frequency"))*n("direction")/divisor*Math.PI/2+Math.PI/4));trace("STEP pulses","V","#334856",.04,t=>t*n("frequency")%1<.5?5:0);trace("DIR signal","V","#777e8a",.04,()=>n("direction")>0?5:0);trace("Commanded shaft position","°","#327cab",.04,t=>Math.floor(t*n("frequency"))*1.8/divisor*n("direction"));status=pulses>=n("steps")?"Programmed move complete — currents holding":"Open-loop commanded move";progress=pulses/n("steps");break;
 }
 case "mobile-robot":{
  const stopped=mode==="Obstacle stop"&&n("distance")<.3&&(n("left")+n("right"))>0,left=stopped?0:n("left"),right=stopped?0:n("right"),pose=differentialPose(left,right,n("track"),time);metric("Forward speed",pose.velocity,"m/s");metric("Yaw rate",pose.yaw*180/Math.PI,"°/s");metric("X position",pose.x,"m");metric("Y position",pose.y,"m");metric("Obstacle range",n("distance"),"m");metric("Wheel track",n("track"),"m");visual.push(pose.x,pose.y,pose.heading,left,right,n("distance"));trace("Yaw angle","°","#2586d9",20,t=>differentialPose(left,right,n("track"),t).heading);status=stopped?"Obstacle threshold crossed — forward motors inhibited":"Differential-drive motion estimate";break;
 }
 case "line-follower":{
  const state=lineFollower(p,mode,time);metric("Line position",state.valid?state.position:"Unavailable");metric("Left motor command",state.left,"PWM");metric("Right motor command",state.right,"PWM");state.readings.forEach((v,i)=>metric(`Sensor ${i+1}`,v));metric("Surface contrast",n("contrast"),"%");visual.push(state.position,state.left,state.right,...state.readings);trace("Steering error","normalized","#268ce2",20,t=>lineFollower(p,mode,t).position);status=state.valid?Math.abs(state.position)<.05?"Line centered — forward motion":"Steering toward the detected line":"Line unavailable — virtual motors stopped";break;
 }
 default:throw new Error(`Unsupported control family ${lab.family}`);
 }
 if(fault){valid=false;status="Input / component fault — dependent outputs unavailable";}
 if(!valid){metrics.forEach(m=>{m.value="Unavailable";m.unit="";});traces.forEach(t=>t.samples.fill(0));visual.fill(0);progress=0;}
 return {metrics,traces,visual,valid,status,progress};
}


