import {parameterValue,itemAt} from './parameters';
import type {AdvancedLab} from './data';
import type {AdvancedResult} from './engine';
import type {Metric,Trace} from '../labs/engine';
const clamp=(v:number,a=0,b=1)=>Math.max(a,Math.min(b,v));
export function microwaveState(p:Record<string,number>,mode:string,time:number){const duration=parameterValue(p, 'duration')*60,seconds=Math.min(duration,time*20),duty=parameterValue(p, 'power')/100*(mode==='Defrost'?.3:mode==='Reheat'?.7:1);let temperature=20;for(let t=0;t<seconds;t+=.1){const on=t%10<duty*10;temperature+=((on?800*.65:0)-4*(temperature-20))/(parameterValue(p, 'mass')*3500)*.1;}const safe=p.doorClosed!==0&&p.foodPresent!==0,complete=seconds>=duration,on=safe&&!complete&&time>0&&seconds%10<duty*10;return {seconds,duration,temperature,duty,on,safe,complete,remaining:Math.max(0,duration-seconds),fan:safe&&time>0&&!complete,turntable:safe&&time>0&&!complete};}
export function washCycle(p:Record<string,number>,mode:string,time:number){const washDuration=mode==='Quick Wash'?8:mode==='Delicates'?12:mode==='Synthetics'?16:20,stages=['Fill','Wash','Drain','Rinse','Drain before spin','Spin','Complete'];let index=mode==='Rinse + Spin'?3:0,water=0,temp=20,stageTime=0,drum=0;for(let t=0;t<time;t+=.1){stageTime+=.1;const scale=1+parameterValue(p, 'load')/8;if(index===0||index===3){water=Math.min(20,water+5/scale*.1);if(water>=20){index=index===0?1:4;stageTime=0;}}else if(index===1){temp=Math.min(parameterValue(p, 'temperature'),temp+2.5/scale*.1);drum=45*Math.sin(stageTime*2);if(stageTime>=washDuration){index=2;stageTime=0;}}else if(index===2||index===4){water=Math.max(0,water-6*.1);if(water<=0){index=index===2?3:5;stageTime=0;}}else if(index===5){drum=parameterValue(p, 'spin')*(1-Math.exp(-stageTime/2));if(stageTime>=12){index=6;drum=0;stageTime=0;}}}const safe=p.doorClosed!==0,active=time>0&&index<6&&safe;return {stage:itemAt(stages,index),index,water,temp,drum:active?(index===1?drum:index===5?drum:0):0,inlet:active&&(index===0||index===3),pump:active&&(index===2||index===4),heater:active&&index===1&&temp<parameterValue(p, 'temperature'),locked:safe&&index<6&&time>0,complete:index===6,progress:index/6,safe};}
export function inductionState(p:Record<string,number>,mode:string,time:number){const compatible=mode==='Magnetic stainless steel'||mode==='Cast iron',coupling=compatible?Math.min(1,(parameterValue(p, 'diameter')/24)**2)*(mode==='Cast iron'?.93:.88):0,power=1800*parameterValue(p, 'power')/10*coupling;let temperature=20,cutoff=false;for(let t=0;t<time*15;t+=.1){if(temperature>=260)cutoff=true;temperature+=((cutoff?0:power)-5*(temperature-20))/(parameterValue(p, 'mass')*1800)*.1;}return {compatible,coupling,power:compatible&&!cutoff&&time>0?power:0,temperature,cutoff,frequency:parameterValue(p, 'frequency')*1000,field:compatible&&!cutoff&&time>0?Math.sqrt(power/1800):0};}
export function energySamples(p:Record<string,number>,connected=true){const vrms=parameterValue(p, 'voltage'),irms=connected?parameterValue(p, 'load')/(vrms*Math.max(.01,parameterValue(p, 'pf'))):0,phase=Math.acos(parameterValue(p, 'pf')),voltage=Array.from({length:400},(_,i)=>Math.SQRT2*vrms*Math.sin(2*Math.PI*i/400)),current=voltage.map((_,i)=>Math.SQRT2*irms*Math.sin(2*Math.PI*i/400-phase)),mean=(a:number[])=>a.reduce((s,v)=>s+v,0)/a.length,power=mean(voltage.map((v,i)=>v*itemAt(current, i)));return {voltage,current,power,vrms:Math.sqrt(mean(voltage.map(v=>v*v))),irms:Math.sqrt(mean(current.map(v=>v*v))),apparent:vrms*irms,reactive:vrms*irms*Math.sin(phase)};}
function solveLinear(a:number[][],b:number[]){const n=b.length,m=a.map((r,i)=>[...r,itemAt(b,i)]);for(let col=0;col<n;col++){let pivot=col;for(let i=col+1;i<n;i++)if(Math.abs(itemAt(itemAt(m, i), col))>Math.abs(itemAt(itemAt(m, pivot), col)))pivot=i;if(Math.abs(itemAt(itemAt(m, pivot), col))<1e-12)return null;[m[col],m[pivot]]=[itemAt(m,pivot),itemAt(m,col)];const divisor=itemAt(itemAt(m, col), col);for(let j=col;j<=n;j++)itemAt(m, col)[j]!/=divisor;for(let i=0;i<n;i++)if(i!==col){const factor=itemAt(itemAt(m, i), col);for(let j=col;j<=n;j++)itemAt(m, i)[j]!-=factor*itemAt(itemAt(m, col), j);}}return m.map(r=>itemAt(r,n));}
export function gpsSolution(count:number,noise:number,clock:number,time=0){const satellites=Array.from({length:Math.max(3,Math.min(12,Math.round(count)))},(_,i)=>{const az=i*2.3999632297,elevation=(20+(i*23)%58)*Math.PI/180,r=20200000;return {x:r*Math.cos(elevation)*Math.cos(az),y:r*Math.cos(elevation)*Math.sin(az),z:r*Math.sin(elevation),az,elevation};}),ranges=satellites.map((s,i)=>Math.hypot(s.x,s.y,s.z)+clock+noise*Math.sin(i*1.91+time*.7));if(count<4)return {valid:false,position:[0,0,0],clock:0,error:0,residual:0,satellites,ranges};let estimate=[0,0,0,0];for(let iteration=0;iteration<8;iteration++){const h=satellites.map(s=>{const d=Math.hypot(itemAt(estimate, 0)-s.x,itemAt(estimate, 1)-s.y,itemAt(estimate, 2)-s.z);return [(itemAt(estimate, 0)-s.x)/d,(itemAt(estimate, 1)-s.y)/d,(itemAt(estimate, 2)-s.z)/d,1];}),residual=satellites.map((s,i)=>itemAt(ranges, i)-(Math.hypot(itemAt(estimate, 0)-s.x,itemAt(estimate, 1)-s.y,itemAt(estimate, 2)-s.z)+itemAt(estimate, 3))),normal=Array.from({length:4},(_,r)=>Array.from({length:4},(_,c)=>h.reduce((sum,row)=>sum+itemAt(row, r)*itemAt(row, c),0))),rhs=Array.from({length:4},(_,r)=>h.reduce((sum,row,i)=>sum+itemAt(row, r)*itemAt(residual, i),0)),delta=solveLinear(normal,rhs);if(!delta)return {valid:false,position:[0,0,0],clock:0,error:0,residual:0,satellites,ranges};estimate=estimate.map((v,i)=>v+itemAt(delta, i));if(Math.hypot(...delta)<1e-6)break;}const residual=Math.sqrt(satellites.reduce((sum,s,i)=>sum+(itemAt(ranges, i)-(Math.hypot(itemAt(estimate, 0)-s.x,itemAt(estimate, 1)-s.y,itemAt(estimate, 2)-s.z)+itemAt(estimate, 3)))**2,0)/satellites.length);return {valid:true,position:estimate.slice(0,3),clock:itemAt(estimate,3),error:Math.hypot(...estimate.slice(0,3)),residual,satellites,ranges};}
export function multimeterReading(p:Record<string,number>,mode:string){const connected=p.probesConnected!==0,r=parameterValue(p, 'resistance'),rs=parameterValue(p, 'series'),v=parameterValue(p, 'voltage'),input=1e7,parallel=r*input/(r+input),voltage=v*parallel/(rs+parallel),current=v/(rs+r+.1),ohms=r,reading=mode==='Measure Current'?current:mode==='Measure Resistance'||mode==='Continuity'?ohms:mode==='AC RMS Voltage'?voltage:voltage,unit=mode==='Measure Current'?'A':mode==='Measure Resistance'||mode==='Continuity'?'Ω':'V',overload=mode==='Measure Current'&&current>(p.currentRange??10),fused=mode==='Measure Current'&&p.fuseBlown===1;return {reading,unit,connected,overload,fused,voltage,current,beep:mode==='Continuity'&&r<50&&connected};}
export function simulateHousehold(lab:AdvancedLab,p:Record<string,number>,mode:string,time:number,fault:boolean):AdvancedResult{
const metrics:Metric[]=[],traces:Trace[]=[],visual:number[]=[];let status='Ready for local teaching simulation',valid=true,progress=0;
const metric=(label:string,value:number|string,unit='')=>metrics.push({label,value:typeof value==='number'?Number(value.toFixed(6)):value,unit});
const trace=(label:string,unit:string,span:number,fn:(t:number)=>number)=>traces.push({label,unit,color:'#2583dc',timeSpan:span,axisLabel:`${span} s`,samples:Array.from({length:240},(_,i)=>fn(i/239*span))});
switch(lab.number){
case 135:{const s=microwaveState(p,mode,time);metric('Remaining cook time',s.remaining,'s');metric('Food temperature estimate',s.temperature,'°C');metric('Average duty cycle',s.duty*100,'%');metric('Magnetron',s.on?'On':'Off');metric('Turntable',s.turntable?'On':'Off');metric('Cooling fan',s.fan?'On':'Off');metric('Cycle',s.complete?'Complete':'Pending / cooking');visual.push(s.temperature,s.on?1:0,s.turntable?1:0,s.remaining);progress=s.seconds/s.duration;valid=s.safe;status=!s.safe?p.doorClosed===0?'Door open — heating inhibited':'No food load — heating inhibited':s.complete?'Cooking complete — heating stopped':time>0?'Controller executing compressed cook cycle':'Ready — 1 simulation second represents 20 cooking seconds';trace('Food thermal response','°C',15,t=>microwaveState(p,mode,t).temperature);break;}
case 136:{const s=washCycle(p,mode,time);metric('Cycle stage',s.stage);metric('Water level',s.water,'L');metric('Water temperature',s.temp,'°C');metric('Drum speed',s.drum,'rpm');metric('Inlet valve',s.inlet?'On':'Off');metric('Drain pump',s.pump?'On':'Off');metric('Heater',s.heater?'On':'Off');metric('Door lock',s.locked?'Locked':'Released');visual.push(s.index,s.water,s.temp,s.drum,s.inlet?1:0,s.pump?1:0);progress=s.progress;valid=s.safe;status=!s.safe?'Door open — outputs inhibited':s.complete?'Cycle complete — drained and stopped':time>0?`Running: ${s.stage}`:'Select program and start the compressed cycle';trace('Water level','L',65,t=>washCycle(p,mode,t).water);break;}
case 137:{const s=inductionState(p,mode,time);metric('Pan temperature',s.temperature,'°C');metric('Absorbed heating power',s.power,'W');metric('Pan coupling',s.coupling*100,'%');metric('Switching frequency',parameterValue(p, 'frequency'),'kHz');metric('Protection',!s.compatible?'Pan detection':s.cutoff?'Overtemperature':'Normal');visual.push(s.temperature,s.field,s.power);valid=s.compatible;status=!s.compatible?'Incompatible / absent pan — inverter inhibited':s.cutoff?'Overtemperature trip — heating disabled':time>0?'Compatible pan — local thermal response':'Ready — 1 simulation second represents 15 heating seconds';trace('Coil reference current','normalized',.0002,t=>s.field*Math.sin(2*Math.PI*s.frequency*t));trace('Pan temperature','°C',30,t=>inductionState(p,mode,t).temperature);break;}
case 138:{const connected=mode!=='Disconnect relay',s=energySamples(p,connected),hours=parameterValue(p, 'elapsed')*Math.min(1,time/10),kwh=s.power*hours/1000;metric('Energy interval total',kwh,'kWh');metric('Real power',s.power,'W');metric('Voltage RMS',s.vrms,'V');metric('Current RMS',s.irms,'A');metric('Apparent power',s.apparent,'VA');metric('Reactive power',s.reactive,'var');metric('Power factor',connected?parameterValue(p, 'pf'):0);metric('Relay',connected?'Connected':'Disconnected');metric('Tamper',mode==='Tamper event'?'Detected / logged':'Normal');metric('Frequency',50,'Hz');visual.push(kwh,s.power,s.irms,connected?1:0);progress=clamp(time/10);status=mode==='Tamper event'?'Tamper detected — local event report':connected?time>=10?'Interval complete — reset to measure another interval':'Sampling voltage/current and accumulating energy':'Relay open — zero load current / energy increment';trace('Voltage channel','V',.02,t=>itemAt(s.voltage, Math.min(399,Math.floor(t/.02*400))));trace('Current channel','A',.02,t=>itemAt(s.current, Math.min(399,Math.floor(t/.02*400))));break;}
case 139:{const s=gpsSolution(parameterValue(p, 'satellites'),p.noiseEnabled===0?0:parameterValue(p, 'noise'),parameterValue(p, 'clock'),time),origin=mode.startsWith('Mumbai')?[19.076,72.8777,14]:mode.startsWith('London')?[51.5074,-.1278,35]:[28.6139,77.209,237],lat=itemAt(origin, 0)+itemAt(s.position, 1)/111320,lon=itemAt(origin, 1)+itemAt(s.position, 0)/(111320*Math.cos(itemAt(origin, 0)*Math.PI/180));valid=s.valid;metric('Latitude',valid?lat:'No fix','° N');metric('Longitude',valid?lon:'No fix','° E');metric('Altitude',valid?itemAt(origin, 2)+itemAt(s.position, 2):'No fix','m');metric('Receiver clock offset',valid?s.clock/299792458*1e9:'No fix','ns');metric('Satellite observations',parameterValue(p, 'satellites'));metric('Synthetic position error',valid?s.error:'No fix','m');metric('Pseudorange residual RMS',valid?s.residual:'No fix','m');visual.push(lat,lon,itemAt(origin, 2)+itemAt(s.position, 2),s.error);status=valid?'Synthetic 3D + receiver clock solution converged':'Fewer than four observations — no 3D solution';trace('Solved position error','m',10,t=>gpsSolution(parameterValue(p, 'satellites'),p.noiseEnabled===0?0:parameterValue(p, 'noise'),parameterValue(p, 'clock'),t).error);break;}
case 140:{const s=multimeterReading(p,mode);metric('Live reading',!s.connected?'OPEN':s.fused?'FUSE':s.overload?'OL':s.reading,s.unit);metric('Input connection',s.connected?'Connected':'Disconnected');metric('Voltage across load',s.voltage,'V');metric('Series-path current',s.current,'A');metric('Continuity buzzer',s.beep?'On':'Off');metric('Current range',p.currentRange??10,'A');visual.push(s.reading,s.beep?1:0,s.overload?1:0,s.connected?1:0);status=!s.connected?'Probes disconnected':s.fused?'Current fuse open — no current reading':s.overload?'Selected current range exceeded':mode==='Measure Resistance'?'Internal test source measures the unpowered resistor':mode==='Continuity'?'Continuity threshold: below 50 Ω':mode==='Measure Current'?'Current probes inserted in series':'Voltage probes connected in parallel';trace(mode==='AC RMS Voltage'?'Sampled AC input':'ADC input model','V',.02,t=>mode==='AC RMS Voltage'?Math.SQRT2*s.voltage*Math.sin(2*Math.PI*50*t):mode==='Measure Current'?s.current*.1:mode==='Measure Resistance'||mode==='Continuity'?s.reading*.0001:s.voltage/100);break;}
default:throw new Error(`Unsupported household lab ${lab.number}`);
}
if(fault){valid=false;status='Sensor / component fault — outputs unavailable';metrics.forEach(m=>{m.value='Unavailable';m.unit='';});traces.forEach(t=>t.samples.fill(0));visual.fill(0);progress=0;}
return {metrics,traces,visual,status,valid,progress};
}

