import {itemAt} from './parameters';
import {describe,it,expect} from 'vitest';
import {renderToStaticMarkup} from '../test-course-render';
import {MemoryRouter} from 'react-router-dom';
import {createElement} from 'react';
import {ADVANCED_LABS,initialAdvancedValues,advancedPath} from './data';
import {simulateHousehold,microwaveState,washCycle,inductionState,energySamples,gpsSolution,multimeterReading} from './household-engine';
import HouseholdLabPage from './HouseholdLabPage';
const labs=ADVANCED_LABS.filter(l=>l.number>=135);
const params=(n:number)=>({...initialAdvancedValues(labs.find(l=>l.number===n)!),doorClosed:1,foodPresent:1,probesConnected:1,noiseEnabled:1});
describe('household labs 135–140',()=>{
it('completes all 86 new lab definitions',()=>{expect(ADVANCED_LABS).toHaveLength(86);expect(labs).toHaveLength(6);expect(new Set(ADVANCED_LABS.map(advancedPath)).size).toBe(86);expect(ADVANCED_LABS.map(l=>l.number).sort((a,b)=>a-b)).toEqual(Array.from({length:86},(_,i)=>55+i));});
for(const l of labs){it(`${l.number}: renders own panels, controls and hardware`,()=>{const html=renderToStaticMarkup(createElement(MemoryRouter,null,createElement(HouseholdLabPage,{lab:l})));expect(html).toContain(`hh-lab-${l.number}`);expect(html).toContain(`${l.number}-device.webp`);expect(html).toContain('Interactive Simulation');expect(l.parts.every(s=>Boolean(l.partFunctions?.[s]))).toBe(true);});it(`${l.number}: every mode produces finite results`,()=>{for(const mode of l.modes){const s=simulateHousehold(l,params(l.number),mode,8,false);expect(s.metrics.filter(m=>typeof m.value==='number').every(m=>Number.isFinite(m.value))).toBe(true);expect(s.traces.every(t=>t.samples.every(Number.isFinite))).toBe(true);}});it(`${l.number}: faults invalidate dependent outputs`,()=>{const s=simulateHousehold(l,params(l.number),itemAt(l.modes, 0),3,true);expect(s.valid).toBe(false);expect(s.metrics.every(m=>m.value==='Unavailable')).toBe(true);});}
it('microwave door and load interlocks inhibit the magnetron',()=>{const p=params(135);expect(microwaveState(p,'Manual cook',.1).on).toBe(true);expect(microwaveState({...p,doorClosed:0},'Manual cook',.1).on).toBe(false);expect(microwaveState({...p,foodPresent:0},'Manual cook',.1).safe).toBe(false);expect(microwaveState(p,'Manual cook',8).complete).toBe(true);expect(microwaveState(p,'Manual cook',8).on).toBe(false);});
it('food mass, power and program change the thermal response',()=>{const p=params(135);expect(microwaveState({...p,mass:2},'Manual cook',3).temperature).toBeLessThan(microwaveState({...p,mass:.2},'Manual cook',3).temperature);expect(microwaveState({...p,power:20},'Manual cook',3).temperature).toBeLessThan(microwaveState(p,'Manual cook',3).temperature);expect(microwaveState(p,'Defrost',3).temperature).toBeLessThan(microwaveState(p,'Manual cook',3).temperature);});
it('washing FSM fills, washes, drains, rinses, spins and completes',()=>{const p=params(136),states=Array.from({length:80},(_,i)=>washCycle(p,'Cotton (Normal)',i));for(const stage of ['Fill','Wash','Drain','Rinse','Drain before spin','Spin','Complete'] as const)expect(states.some(s=>s.stage===stage)).toBe(true);for(const s of states.filter(s=>s.stage==='Spin'))expect(s.water).toBe(0);const end=states.at(-1)!;expect(end.complete).toBe(true);expect(end.drum).toBe(0);expect(end.locked).toBe(false);});
it('open washer door inhibits drum, valves and heater',()=>{const s=washCycle({...params(136),doorClosed:0},'Cotton (Normal)',15);expect(s.safe).toBe(false);expect(s.drum).toBe(0);expect(s.inlet||s.pump||s.heater).toBe(false);});
it('wash load and program affect cycle timing',()=>{const p=params(136);expect(washCycle({...p,load:8},'Cotton (Normal)',6).index).toBe(0);expect(washCycle({...p,load:1},'Cotton (Normal)',6).index).toBe(1);expect(washCycle(p,'Quick Wash',35).index).toBeGreaterThan(washCycle(p,'Cotton (Normal)',35).index);});
it('induction rejects incompatible pans and responds to coupling and thermal mass',()=>{const p=params(137);expect(inductionState(p,'Aluminium (non-magnetic)',10).power).toBe(0);expect(inductionState(p,'No pan',10).compatible).toBe(false);expect(inductionState({...p,diameter:12},'Cast iron',5).temperature).toBeLessThan(inductionState({...p,diameter:24},'Cast iron',5).temperature);expect(inductionState({...p,mass:3},'Cast iron',5).temperature).toBeLessThan(inductionState({...p,mass:.3},'Cast iron',5).temperature);});
it('induction temperature trip disables heating',()=>{const s=inductionState({...params(137),mass:.3,power:10},'Cast iron',60);expect(s.cutoff).toBe(true);expect(s.power).toBe(0);});
it('meter samples recover RMS, real, apparent and reactive power',()=>{const s=energySamples(params(138));expect(s.vrms).toBeCloseTo(230,8);expect(s.power).toBeCloseTo(2300,8);expect(s.irms).toBeCloseTo(2300/(230*.85),8);expect(s.power/s.apparent).toBeCloseTo(.85,8);expect(Math.hypot(s.power,s.reactive)).toBeCloseTo(s.apparent,8);expect(energySamples(params(138),false).power).toBe(0);});
it('energy is the integrated real power interval',()=>{const l=labs.find(l=>l.number===138)!,s=simulateHousehold(l,{...params(138),elapsed:2},'Normal metering',10,false);expect(itemAt(s.metrics, 0).value).toBeCloseTo(4.6,6);expect(itemAt(simulateHousehold(l,params(138),'Disconnect relay',10,false).metrics, 0).value).toBe(0);});
it('GNSS solver recovers position and clock with noiseless ranges',()=>{for(const count of [4,6,12] as const){const s=gpsSolution(count,0,75);expect(s.valid).toBe(true);expect(s.clock).toBeCloseTo(75,5);expect(s.error).toBeLessThan(1e-4);expect(s.residual).toBeLessThan(1e-5);}expect(gpsSolution(3,0,50).valid).toBe(false);});
it('GNSS pseudorange noise changes solved coordinates and residuals',()=>{expect(gpsSolution(8,10,50).error).toBeGreaterThan(1);expect(gpsSolution(8,10,50).residual).toBeGreaterThan(1);expect(gpsSolution(8,10,50,1).position).not.toEqual(gpsSolution(8,10,50,2).position);});
it('DMM voltage loading and current shunt use separate input paths',()=>{const p=params(140);expect(multimeterReading(p,'Measure Voltage').reading).toBeCloseTo(5*1000/(1100),3);expect(multimeterReading(p,'Measure Current').reading).toBeCloseTo(5/1100.1,8);expect(multimeterReading(p,'Measure Resistance').reading).toBe(1000);});
it('DMM disconnected, overloaded, open-fuse and continuity states are explicit',()=>{const p=params(140);expect(multimeterReading({...p,probesConnected:0},'Measure Voltage').connected).toBe(false);expect(multimeterReading({...p,voltage:24,resistance:1,series:0,currentRange:.2},'Measure Current').overload).toBe(true);expect(multimeterReading({...p,fuseBlown:1},'Measure Current').fused).toBe(true);expect(multimeterReading({...p,resistance:10},'Continuity').beep).toBe(true);});
});
