import DeviceCourse from '../DeviceCourse';
import {RouterArchitecture,RouterSignal} from './RouterPanels';
import {QuadrupedArchitecture} from './QuadrupedPanels';
import {VisionArchitecture,VisionIPO} from './VisionPanels';
import {WarehouseArchitecture,WarehouseIPO} from './WarehousePanels';
import {GroundVehicleArchitecture,GroundVehicleView} from './GroundVehiclePanels';
import {SlamArchitecture,SlamDataFlow,SlamStepArt} from './SlamPanels';
import {IndustrialArchitecture,IndustrialSignal,IndustrialIPO} from './IndustrialControllerPanels';
import {BalanceArchitecture,BalanceIPO} from './BalancePanels';
import {parameterValue,itemAt} from './parameters';
import {useEffect,useMemo,useState,type ReactNode} from "react";
import {Link} from "react-router-dom";
import {STUDIO_PATH} from "../catalogue";
import {Waveform} from "../labs/visuals";
import {initialAdvancedValues,type AdvancedLab} from "./data";
import {simulateRobotics,navigationScene,armPoints,gaitState,inspectPixels,type Cell} from "./robotics-engine";
import type {AdvancedResult} from "./engine";
import {Card,Flow,Quiz} from "./SystemsLabPage";
import DeviceCircuit from "./DeviceCircuit";
import {CobotArchitecture,CobotIPO,CobotElectrical} from "./CobotPanels";
import {LidarArchitecture,LidarPointCloud,LidarDataFlow,LidarIPO} from "./LidarPanels";
import "./robotics.css";
const art=(n:number,role:string)=>`/device-labs/advanced/${String(n).padStart(3,"0")}-${role}.webp?v=6`;
const layouts:Record<number,[string,number,number,number][]>={
115:[["device",1,9,1],["internal",10,8,1],["flow",18,7,1],["architecture",1,9,2],["circuit",10,8,2],["steps",18,7,2],["simulation",1,12,3],["applications",13,6,3],["keys",19,6,3]],
116:[["device",1,10,1],["internal",11,7,1],["flow",18,7,1],["architecture",1,9,2],["circuit",10,9,2],["steps",19,6,2],["simulation",1,12,3],["signal",13,4,3],["applications",17,8,3],["keys",1,24,4]],
117:[["device",1,10,1],["internal",11,7,1],["flow",18,7,1],["architecture",1,10,2],["circuit",11,8,2],["parts",19,6,2],["steps",1,7,3],["simulation",8,11,3],["applications",19,6,3],["keys",1,24,4]],
118:[["internal",1,8,1],["flow",9,8,1],["architecture",17,8,1],["circuit",1,8,2],["steps",9,6,2],["signal",15,10,2],["simulation",1,12,3],["applications",13,6,3],["keys",19,6,3]],
119:[["device",1,13,1],["internal",14,11,1],["flow",1,9,2],["architecture",10,8,2],["circuit",18,7,2],["steps",1,13,3],["simulation",14,11,3],["signal",1,13,4],["applications",14,7,4],["keys",21,4,4]],
120:[["device",1,13,1],["parts",14,11,1],["overview",1,8,2],["flow",9,8,2],["architecture",17,8,2],["internal",1,8,3],["circuit",9,8,3],["steps",17,8,3],["simulation",1,12,4],["signal",13,6,4],["applications",19,6,4],["keys",1,24,5]],
121:[["internal",1,9,1],["flow",10,7,1],["architecture",17,8,1],["circuit",1,9,2],["steps",10,7,2],["simulation",17,8,2],["applications",1,13,3],["keys",14,11,3]],
122:[["device",1,8,1],["internal",9,8,1],["flow",17,8,1],["architecture",1,10,2],["circuit",11,7,2],["steps",18,7,2],["simulation",1,12,3],["signal",13,4,3],["applications",17,8,3],["keys",17,8,4]],
123:[["device",1,9,1],["internal",10,8,1],["parts",18,7,1],["flow",1,9,2],["architecture",10,15,2],["circuit",1,9,3],["steps",10,6,3],["signal",16,4,3],["simulation",20,5,3],["applications",1,13,4],["keys",14,11,4]],
124:[["internal",1,8,1],["flow",9,8,1],["simulation",17,8,1],["architecture",9,8,2],["circuit",17,8,2],["steps",1,8,3],["signal",9,9,3],["applications",18,7,3],["keys",1,24,4]]};
const circuitStages:Record<number,string[]>={115:["Li-Po / fuse","5 V buck / motor rail","IMU / I²C","MCU / PID","PWM / DIR","Dual H-bridge","DC motors / encoders"],116:["AC / EMI filter","24 V DC supply","Safety controller","Real-time CPU","Servo drive modules","Six joint motors","Encoder feedback"],117:["24 V distribution","Safety monitor","Main robot controller","Joint motor drives","Motor / harmonic gear","Torque / encoder feedback","Tool I/O / fieldbus"],118:["LiDAR / UART","IMU / I²C","Encoders / GPIO","Onboard computer","PWM / DIR","Motor H-bridge","Left / right motors"],119:["LiDAR / USB","IMU / I²C","Wheel encoders","ROS / SLAM processor","Map memory","Motor controller","DC motors / feedback"],120:["Battery / regulator","Camera / range sensor","GNSS / wheel odometry","Navigation computer","Drive / steering control","Traction / steering actuator","Motion feedback"],121:["48 V battery / BMS","Fuse / power switch","DC-DC rails","Industrial computer","CAN motor drives","Drive + lift motors","Encoder / rack feedback"],122:["24 V supply","Trigger sensor / DI","Camera / exposure","GigE / frame processor","Inspection logic","PLC digital output","Virtual diverter"],123:["22.2 V battery","DC-DC rails","IMU / foot sensing","Control computer","CAN / PWM drives","12 BLDC joint motors","Encoder / contact feedback"],124:["12 V DC input","Regulation / rails","WAN Ethernet PHY","Router SoC / CPU","RAM / flash / crystal","RF front end / antenna","LAN switch / ports"]};
function Architecture({lab,circuit=false}:{lab:AdvancedLab;circuit?:boolean}){
 if(lab.number===124&&!circuit)return <RouterArchitecture/>;
 if(lab.number===123&&!circuit)return <QuadrupedArchitecture/>;
 if(lab.number===122&&!circuit)return <VisionArchitecture/>;
 if(lab.number===121&&!circuit)return <WarehouseArchitecture/>;
 if(lab.number===120&&!circuit)return <GroundVehicleArchitecture/>;
 if(lab.number===119&&!circuit)return <SlamArchitecture/>;
 if(lab.number===116)return <IndustrialArchitecture circuit={circuit}/>;
 if(lab.number===115&&!circuit)return <BalanceArchitecture/>;
 if(circuit)return <DeviceCircuit lab={lab}/>;
 const a=lab.architecture!,stages=circuit?itemAt(circuitStages,lab.number):[...a.inputs.slice(0,2),...a.processing,...a.outputs.slice(0,2)],rows=Math.ceil(stages.length/4);
 if(!circuit)return <div className="rb-diagram"><svg viewBox="0 0 660 270" role="img" aria-label={`${lab.device.name} system architecture`}><defs><marker id={`rb-system-${lab.number}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#347bb1"/></marker></defs>{[a.inputs,a.processing,a.outputs].map((items,column)=>items.map((text,i)=>{const x=12+column*220,y=12+i*58;return <g key={`${column}-${i}`}><rect x={x} y={y} width="180" height="46" rx="4" stroke="#8eb4ce" fill={column===1?"#e1f2e8":column===2?"#fff0d8":"#e1efff"}/><text x={x+90} y={y+19} fontSize="12" textAnchor="middle">{text.split(" / ")[0]}</text><text x={x+90} y={y+35} fontSize="12" textAnchor="middle">{text.split(" / ").slice(1).join(" / ")}</text>{column===0&&<path d={`M192 ${y+23}H210V35H232`} fill="none" stroke="#347bb1" markerEnd={`url(#rb-system-${lab.number})`}/>} {column===1&&i<items.length-1&&<path d={`M322 ${y+46}v12`} stroke="#347bb1" markerEnd={`url(#rb-system-${lab.number})`}/>} {column===2&&<path d={`M412 ${35+(a.processing.length-1)*58}H432V${y+23}H452`} fill="none" stroke="#347bb1" markerEnd={`url(#rb-system-${lab.number})`}/>}</g>;}))}<path d="M542 220V250H102V187" fill="none" stroke="#31a576" strokeDasharray="5 4"/><text x="330" y="267" fontSize="12" textAnchor="middle">Independent measurements → controller → actuator / output branches</text></svg></div>;
 return <div className="rb-diagram"><svg viewBox={`0 0 650 ${rows*95+30}`} role="img" aria-label={`${lab.device.name} ${circuit?"electrical circuit":"system architecture"}`}><defs><marker id={`rb-arrow-${lab.number}-${circuit}`} viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#347bb1"/></marker></defs>{stages.map((text,i)=>{const r=Math.floor(i/4),c=r%2?3-i%4:i%4,x=10+c*160,y=12+r*95;return <g key={text}><rect x={x} y={y} width="130" height="54" rx="4" stroke="#88abc5" fill={circuit&&i<2?"#fff0dc":i<2?"#e1efff":"#e7f4ea"}/><text x={x+65} y={y+23} fontSize="12" textAnchor="middle">{text.split(" / ")[0]}</text><text x={x+65} y={y+40} fontSize="12" textAnchor="middle">{text.split(" / ").slice(1).join(" / ")}</text>{i<stages.length-1&&<path d={i%4===3?`M${x+65} ${y+54}v41`:r%2?`M${x} ${y+27}h-30`:`M${x+130} ${y+27}h30`} fill="none" stroke={circuit&&i<2?"#df6256":"#347bb1"} markerEnd={`url(#rb-arrow-${lab.number}-${circuit})`}/>}</g>;})}<path d={`M75 ${rows*95-15}V${rows*95+8}H620V5H75`} fill="none" stroke="#37a978" strokeDasharray="5 4"/><text x="320" y={rows*95+25} textAnchor="middle" fontSize="12">{circuit?"Power rails, control links and feedback are functional teaching connections.":"Observe → estimate → decide → act → feed back"}</text></svg></div>;
}
function GridView({lab,p,mode,time,mapping,onCell}:{lab:AdvancedLab;p:Record<string,number>;mode:string;time:number;mapping:boolean;onCell?:(cell:Cell)=>void}){
 const scene=navigationScene(lab.number,p,mode,time),grid=mapping?scene.known:scene.grid;
 return <svg viewBox="0 0 360 360" role="img" aria-label="Ray-derived occupancy map and computed reference path" onClick={onCell?e=>{const b=e.currentTarget.getBoundingClientRect();onCell({x:Math.floor((e.clientX-b.left)/b.width*18),y:Math.floor((e.clientY-b.top)/b.height*18)});}:undefined}><rect width="360" height="360" fill="#d9e4e8"/>{grid.map((row,y)=>row.map((v,x)=><rect key={`${x}-${y}`} x={x*20} y={y*20} width="20" height="20" fill={v<0?"#53656f":v===1?"#26363d":"#f0f3f2"} stroke="#bac7c9" strokeWidth=".5"/>))}<polyline points={scene.path.map(c=>`${c.x*20+10},${c.y*20+10}`).join(" ")} fill="none" stroke="#1c8ee1" strokeWidth="3" strokeDasharray="4 3"/>{mapping&&scene.scan.filter((_,i)=>i%2===0).map((ray,i)=><path key={i} d={`M${scene.pose.x*20} ${scene.pose.y*20}L${ray.x*20} ${ray.y*20}`} stroke="#e56c64" strokeWidth=".6" opacity=".45"/>)}<circle cx={scene.goal.x*20+10} cy={scene.goal.y*20+10} r="7" fill="#56bf72" stroke="white"/><g transform={`translate(${scene.estimated.x*20} ${scene.estimated.y*20})`}><circle r="9" fill="#1c90e2" stroke="white" strokeWidth="2"/><path d="M0-11L5 2H-5Z" fill="#e94c43"/></g></svg>;
}
function ArmView({result,front=true,closed=false,top=false,industrial=false}:{result:AdvancedResult;front?:boolean;closed?:boolean;top?:boolean;industrial?:boolean}){const pose=armPoints(result.visual.slice(0,6));return <svg viewBox="0 0 320 235" role="img" aria-label="Reduced six-joint arm pose"><path d="M20 210H300M70 210L110 185H235L275 210" fill="none" stroke="#c8d8e3"/><rect x="70" y="182" width="90" height="20" rx="4" fill="#536d7a"/>{pose.points.map((p,i)=>{const x=110+(top?Math.cos(itemAt(result.visual, 0)*Math.PI/180)*parameterValue(p, 'x'):front?parameterValue(p, 'x'):Math.sin(itemAt(result.visual, 0)*Math.PI/180)*parameterValue(p, 'x'))*150,y=195-(top?Math.sin(itemAt(result.visual, 0)*Math.PI/180)*parameterValue(p, 'x'):parameterValue(p, 'z'))*150,prev=pose.points[i-1];return <g key={i}>{prev&&<path d={`M${110+(top?Math.cos(itemAt(result.visual, 0)*Math.PI/180)*prev.x:front?prev.x:Math.sin(itemAt(result.visual, 0)*Math.PI/180)*prev.x)*150} ${195-(top?Math.sin(itemAt(result.visual, 0)*Math.PI/180)*prev.x:prev.z)*150}L${x} ${y}`} stroke={industrial?"#dfbc27":"#9fb6c5"} strokeWidth="17" strokeLinecap="round"/>}<circle cx={x} cy={y} r="11" fill={industrial?"#dbb222":"#4d92bb"} stroke="#214f6b" strokeWidth="2"/>{i===3&&<g transform={`translate(${x} ${y}) rotate(${result.visual[3]??0})`}><path d={closed?"M0 8V25M-3 25V35M3 25V35":"M0 8V25M-10 25V35M10 25V35"} stroke="#334957" strokeWidth="5"/></g>}</g>;})}<text x="160" y="228" textAnchor="middle" fontSize="12">{top?"Top projection":front?"Side elevation":"Front projection"} · reduced joint geometry</text></svg>;}
function BalanceView({result}:{result:AdvancedResult}){return <svg viewBox="0 0 300 230" role="img" aria-label="Inverted-pendulum pitch simulation"><path d="M10 200H290" stroke="#416d8a"/><path d="M150 15V200" stroke="#58a268" strokeDasharray="4 4"/><g transform={`translate(150 190) rotate(${result.visual[0]})`}><rect x="-20" y="-95" width="40" height="85" rx="4" fill="#343f48"/>{[-78,-48,-18].map(y=><path key={y} d={"M-25 "+y+"H25"} stroke="#a9b5a8" strokeWidth="5"/>)}<path d="M-18-80V-10M18-80V-10" stroke="#c9ad62" strokeWidth="3"/><rect x="-19" y="-110" width="38" height="18" fill="#24739c"/><circle cx="-10" cy="-101" r="6" fill="#c2d7df" stroke="#193b4d"/><circle cx="10" cy="-101" r="6" fill="#c2d7df" stroke="#193b4d"/><rect x="-15" y="-70" width="30" height="24" fill="#277faa"/><circle cx="-30" cy="0" r="18" fill="#273741"/><circle cx="30" cy="0" r="18" fill="#273741"/><circle cx="-30" cy="0" r="12" fill="#1769b6"/><circle cx="30" cy="0" r="12" fill="#1769b6"/><circle cx="-30" cy="0" r="4" fill="#83969c"/><circle cx="30" cy="0" r="4" fill="#83969c"/><path d="M0-90V-110" stroke="#526f82"/></g><text x="150" y="222" textAnchor="middle" fontSize="12">Pitch {result.valid?itemAt(result.visual, 0).toFixed(2)+"°":"Unavailable"}</text></svg>;}
function QuadrupedView({p,mode,time,contacts}:{p:Record<string,number>;mode:string;time:number;contacts:boolean}){const legs=gaitState(p,mode,time);return <svg viewBox="0 0 330 235" role="img" aria-label="Quadruped leg trajectories and contact phases"><path d="M10 205H320" stroke="#98b1bf"/><g transform={`translate(165 95) rotate(${parameterValue(p, 'pitch')})`}><rect x="-95" y="-20" width="190" height="40" rx="10" fill="#3e535f"/><rect x="-35" y="-40" width="70" height="20" rx="4" fill="#73848d"/>{legs.map((leg,i)=>{const origin=i<2?-70:70,side=i%2?9:-9,hip=leg.hip*Math.PI/180,knee=leg.knee*Math.PI/180,mx=origin+Math.sin(hip)*46,my=25+Math.cos(hip)*46,fx=mx+Math.sin(hip+knee)*46,fy=my+Math.cos(hip+knee)*46;return <g key={i} transform={`translate(${side} 0)`} opacity={i%2?.65:1}><path d={`M${origin} 15L${mx} ${my}L${fx} ${fy}`} fill="none" stroke="#98abb7" strokeWidth="10" strokeLinecap="round"/><circle cx={origin} cy="15" r="12" fill="#233947"/><circle cx={mx} cy={my} r="7" fill="#344f60"/><circle cx={fx} cy={fy} r="7" fill={contacts?leg.contact?"#41b676":"#eac156":"#233947"}/></g>;})}</g><text x="165" y="228" fontSize="12" textAnchor="middle">{mode} · stance / swing from gait phase</text></svg>;}
function VisionView({p,mode,processing}:{p:Record<string,number>;mode:string;processing:boolean}){const s=inspectPixels(p,mode);return <svg viewBox="0 0 160 175" role="img" aria-label="Synthetic pixel frame processed by the inspection algorithm"><rect width="160" height="175" fill="#111a20"/>{s.pixels.map((row,y)=>row.map((v,x)=>v>20?<rect key={`${x}-${y}`} x={16+x*2} y={12+y*2} width="2" height="2" fill={processing?itemAt(itemAt(s.binary, y), x)?"#e5e9eb":"#202c34":`rgb(${v},${v},${v})`}/>:null))}{processing&&<rect x="29" y="25" width="104" height="104" fill="none" stroke={s.accept?"#46c57c":"#e66c58"}/>}<text x="80" y="157" fill="white" fontSize="12" textAnchor="middle">Synthetic test frame · 64 × 64 pixels</text><text x="80" y="170" fill={s.accept?"#46c57c":"#e66c58"} fontSize="12" textAnchor="middle">{s.accept?"ACCEPT":"REJECT"}</text></svg>;}
export default function RoboticsLabPage({lab}:{lab:AdvancedLab}){
 const [p,setP]=useState<Record<string,number>>(()=>({...initialAdvancedValues(lab),enabled:1,estop:0,obstacle:-1})),[mode,setMode]=useState(itemAt(lab.modes,0)),[time,setTime]=useState(0),[running,setRunning]=useState(false),[fault,setFault]=useState(false),[tab,setTab]=useState("Internal"),[step,setStep]=useState(0),[front,setFront]=useState(true),[mapping,setMapping]=useState(true),[contacts,setContacts]=useState(true),[processing,setProcessing]=useState(true),[auto,setAuto]=useState(false),[ssid,setSsid]=useState("Lab124-Router"),[events,setEvents]=useState<string[]>([]),[waypoints,setWaypoints]=useState<Record<string,number>[]>([]),[tool,setTool]=useState(false),[replaying,setReplaying]=useState(false),[armView,setArmView]=useState("Side");
 const result=useMemo(()=>simulateRobotics(lab,p,mode,time,fault),[lab,p,mode,time,fault]),navigation=[118,119,121].includes(lab.number),arm=[116,117].includes(lab.number);
 useEffect(()=>{if(!running)return;const id=setInterval(()=>setTime(t=>Math.min(120,t+.1)),100);return()=>clearInterval(id);},[running]);
 useEffect(()=>{if(time>=120||lab.number===115&&result.status.startsWith("Balance lost"))setRunning(false);},[time,lab.number,result.status]);
 useEffect(()=>{if(!replaying||!running||!waypoints.length)return;const target=itemAt(waypoints,Math.floor(time/3)%waypoints.length);setP(v=>({...v,...target,motionStart:time,...Object.fromEntries(result.visual.slice(0,6).map((x,i)=>[`start${i+1}`,x]))}));},[replaying,running,waypoints,Math.floor(time/3)]);
 useEffect(()=>{if(!auto||lab.number!==122)return;const id=setInterval(()=>{setTime(t=>t+1);setEvents(v=>[`Auto inspection: ${result.status}`,...v].slice(0,20));},1500);return()=>clearInterval(id);},[auto,lab.number,result.status]);
 const reset=()=>{setP({...initialAdvancedValues(lab),enabled:1,estop:0,obstacle:-1});setMode(itemAt(lab.modes,0));setTime(0);setRunning(false);setFault(false);setTab("Internal");setStep(0);setFront(true);setMapping(true);setContacts(true);setProcessing(true);setAuto(false);setSsid("Lab124-Router");setEvents([]);setWaypoints([]);setTool(false);setReplaying(false);setArmView("Side");};
 const heldJoints=()=>Object.fromEntries(result.visual.slice(0,6).map((v,i)=>[`hold${i+1}`,v]));
 const manualMove=(dx:number,dy:number)=>{const scene=navigationScene(lab.number,p,mode,time),x=Math.round(p.startx??2)+dx,y=Math.round(p.starty??14)+dy;if(scene.grid[y]?.[x]===0){setP(v=>({...v,startx:x,starty:y}));setMode("Manual");setTime(0);setRunning(false);}};
 const run=()=>{if(lab.number===122){setTime(t=>t+1);setEvents(v=>[`Inspection: ${result.status}`,...v].slice(0,20));}else if(lab.number===124)setEvents(v=>[`Applied local settings: ${ssid}, ${mode}, channel ${parameterValue(p, 'channel')}`,...v].slice(0,20));else setRunning(v=>!v);};
 const display=!result.valid?<p role="alert">Sensor-dependent visualization unavailable</p>:lab.number===115?<BalanceView result={result}/>:arm?<><ArmView result={result} industrial={lab.number===116} front={lab.number===117?armView==="Side":front} top={lab.number===117&&armView==="Top"} closed={tool}/ >{lab.number===116&&mode==="I/O Monitor"&&<div className="rb-io"><h3>Live I/O monitor</h3><p>Safety input: {parameterValue(p, 'estop')?"E-stop active":"Clear"}</p><p>Drive enable: {parameterValue(p, 'enabled')?"ON":"OFF"}</p><p>Tool output: {tool?"Gripper close":"Gripper open"}</p></div>}{lab.number===116&&mode==="Diagnostics"&&<div className="rb-diagnostics"><h3>Local drive diagnostics</h3>{result.metrics.slice(0,6).map((m,i)=><p key={m.label}>J{i+1} following error: {((p[`j${i+1}`]??0)-Number(m.value)).toFixed(1)}° · {parameterValue(p, 'estop')||!parameterValue(p, 'enabled')?"Inhibited":"Enabled"}</p>)}</div>}</>:navigation?<GridView lab={lab} p={p} mode={mode} time={time} mapping={mapping} onCell={cell=>setP(v=>({...v,obstacle:cell.y*18+cell.x}))}/>:lab.number===122?<VisionView p={p} mode={mode} processing={processing}/>:lab.number===123?<QuadrupedView p={p} mode={mode} time={time} contacts={contacts}/>:lab.number===124?<div className="rb-wifi"><span>◔</span><strong>{result.metrics[0]?.value} dBm</strong><p>{result.metrics[1]?.value} Mbps total</p><p>{result.metrics[2]?.value} Mbps / client</p><p>{parameterValue(p, 'clients')} clients · {ssid}</p><small>Synthetic nearby APs: ch 1 (24%), ch 6 (8%), ch 11 (18%). Five-channel overlap illustrates shared airtime.</small></div>:<GroundVehicleView result={result} p={p} time={time}/>;
 const renderSliders=(advanced=false)=><div className="rb-controls">{lab.controls.filter(c=>lab.number===124?((c.key==="distance"||c.key==="interference")===advanced):lab.number!==117||((c.key==="contact"||c.key==="distance")===advanced)).map(c=><label key={c.key}><span>{c.label}</span><input type="range" aria-label={c.label} min={c.min} max={c.max} step={c.step} value={p[c.key]} onChange={e=>{setP(v=>({...v,...(arm&&(c.key==="contact"&&Number(e.target.value)>parameterValue(v,'force')||c.key==="force"&&Number(e.target.value)<parameterValue(v,'contact'))?heldJoints():{}),[c.key]:Number(e.target.value)}));if(lab.number===118&&c.key==="speed")setMode("Autonomous");}}/><output>{p[c.key]} {c.unit}</output></label>)}</div>;
 const controls=<><div className="sy-run"><button className="sy-primary" disabled={!result.valid} onClick={run}>{lab.number===122?"Run inspection":lab.number===124?"Apply local settings":running?"Pause":"Start simulation"}</button><button onClick={reset}>Reset</button><output>{time.toFixed(1)} s</output></div><label className="sy-mode">Operating mode<select value={mode} onChange={e=>setMode(e.target.value)}>{lab.modes.map(m=><option key={m}>{m}</option>)}</select></label>{lab.number===124&&<label className="rb-text">SSID<input value={ssid} maxLength={32} onChange={e=>setSsid(e.target.value)}/></label>}{renderSliders()}{lab.number===124&&<details><summary>Distance & interference</summary>{renderSliders(true)}</details>}{lab.number===117&&<details><summary>Contact & proximity settings</summary>{renderSliders(true)}</details>}<label className="sy-fault"><input type="checkbox" checked={fault} onChange={e=>{setFault(e.target.checked);setRunning(false);setAuto(false);}}/> Sensor / control fault</label><p className={`sy-status ${result.valid?"":"invalid"}`} role="status">{result.status}</p></>;
 const extras=arm?<div className="rb-extra">{lab.number===117?["Front","Side","Top"].map(view=><button key={view} aria-pressed={armView===view} onClick={()=>setArmView(view)}>{view} view</button>):<button aria-pressed={front} onClick={()=>setFront(v=>!v)}>Change arm view</button>}<button aria-pressed={p.enabled===1} onClick={()=>setP(v=>({...v,...heldJoints(),enabled:v.enabled?0:1}))}>{parameterValue(p, 'enabled')?"Disable drives":"Enable drives"}</button><button onClick={()=>{setTime(0);setRunning(false);setP(v=>({...v,j1:0,j2:0,j3:0,j4:0,j5:0,j6:0}));}}>Move home</button><button className="rb-stop" aria-pressed={p.estop===1} onClick={()=>{setRunning(false);setP(v=>({...v,...heldJoints(),estop:v.estop?0:1}));}}>{parameterValue(p, 'estop')?"Release virtual E-stop":"Emergency stop"}</button><button aria-pressed={tool} onClick={()=>setTool(v=>!v)}>Gripper {tool?"closed":"open"}</button>{lab.number===117&&<><button onClick={()=>setWaypoints(v=>[...v,Object.fromEntries(Object.entries(p).filter(([k])=>/^j[1-6]$/.test(k)))])}>Record waypoint</button><button disabled={!waypoints.length} onClick={()=>{setP(v=>({...v,...waypoints[0],motionStart:0,...Object.fromEntries(result.visual.slice(0,6).map((x,i)=>[`start${i+1}`,x]))}));setTime(0);setReplaying(true);setRunning(true);}}>Replay waypoints</button><p>{waypoints.length} local joint waypoints</p></>}</div>:navigation?<div className="rb-extra">{lab.number===118&&[["Forward",0,-1],["Left",-1,0],["Right",1,0],["Backward",0,1]].map(([label,dx,dy])=><button key={String(label)} onClick={()=>manualMove(Number(dx),Number(dy))}>{String(label)}</button>)}<label><input type="checkbox" checked={mapping} onChange={e=>setMapping(e.target.checked)}/> Show measured occupancy</label><button onClick={()=>setP(v=>({...v,obstacle:8*18+8}))}>Add central obstacle</button><button onClick={()=>setP(v=>({...v,obstacle:-1}))}>Clear added obstacle</button><button onClick={()=>{setRunning(false);setTime(0);}}>Reset map</button><p>Click a cell to add one obstacle · routes use the synthetic reference grid.</p></div>:lab.number===122?<div className="rb-extra"><label><input type="checkbox" checked={processing} onChange={e=>setProcessing(e.target.checked)}/> Show processing steps</label><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/> Auto inspection</label><output>{events.length} local inspections</output></div>:lab.number===123?<div className="rb-extra"><button onClick={()=>{setRunning(false);setTime(t=>Math.min(120,t+.1));}}>Step gait</button><label><input type="checkbox" checked={contacts} onChange={e=>setContacts(e.target.checked)}/> Show foot contacts</label></div>:null;
 const parts=<div className="rb-parts">{(lab.number===123?[4,5,2,1,3,7].map(i=>({part:itemAt(lab.parts,i),i})):lab.parts.map((part,i)=>({part,i}))).map(({part,i})=><details key={part}><summary>{[117,123].includes(lab.number)&&<img src={art(lab.number,`part-${lab.number===123?[4,5,2,1,3,7].indexOf(i):i}`)} alt={`${part} hardware`}/>}<span>{i+1}</span>{part}</summary><p>{lab.partFunctions?.[part]??lab.principle.split(".").find(sentence=>sentence.toLowerCase().includes(itemAt(part.split(" "), 0).toLowerCase()))??`Signal connection: ${itemAt(circuitStages, lab.number).find(stage=>stage.toLowerCase().includes(itemAt(part.split(" "), 0).toLowerCase()))??lab.architecture!.processing[0]}. Inspect the learning modelelled subsystem path.`}</p></details>)}</div>;
 const metrics=<dl className="sy-metrics">{result.metrics.map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value} {m.unit}</dd></div>)}</dl>;
 const panels:Record<string,ReactNode>={
 overview:<Card name="overview" title="Device Overview"><p>{lab.principle}</p></Card>,
 device:<Card name="device" title={lab.number===120?"Autonomous Ground Vehicle":"Real Hardware / Device Overview"}>{lab.number===119?<div className="slam-hero"><img src={art(119,"external")} alt="SLAM wheeled robot exploring an office"/><GridView lab={lab} p={p} mode={mode} time={time} mapping={mapping}/></div>:<img src={art(lab.number,"external")} alt={`${lab.device.name} real equipment`}/>}<p>{lab.principle}</p></Card>,
 internal:<Card name="internal" title={lab.number===121?"Robot Overview & Internal Components":lab.number===120?"Functional Internal Architecture":"Inside the Device / Exploded View"}><div className="sy-tabs">{["External","Internal","Circuit"].map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t}</button>)}</div>{tab==="Circuit"||lab.number===120&&tab==="Internal"?<Architecture lab={lab} circuit/>:<img src={art(lab.number,tab.toLowerCase())} alt={`${lab.device.name} ${tab.toLowerCase()} hardware`}/>}<details><summary>Inspect component functions</summary>{parts}</details></Card>,
 parts:<Card name="parts" title="Key Components">{parts}</Card>,
 flow:<Card name="flow" title="Input → Processing → Output">{lab.number===122?<VisionIPO/>:lab.number===121?<WarehouseIPO/>:lab.number===116?<IndustrialIPO/>:lab.number===115?<BalanceIPO/>:lab.number===118?<LidarIPO/>:lab.number===117?<CobotIPO/>:<Flow lab={lab}/>}<blockquote>Measure. Think. Act. Repeat.</blockquote></Card>,
 architecture:<Card name="architecture" title="Complete System Block Diagram">{lab.number===118?<LidarArchitecture/>:lab.number===117?<CobotArchitecture/>:<Architecture lab={lab}/>}</Card>,
 circuit:<Card name="circuit" title="Simplified Electrical / Control Architecture">{lab.number===117?<CobotElectrical/>:<Architecture lab={lab} circuit/>}</Card>,
 steps:<Card name="steps" title="Working Principle (Step by Step)"><ol className="rb-steps">{lab.steps.map(([title,text],i)=><li key={title}><button onClick={()=>setStep(i)} aria-pressed={step===i}><span>{i+1}</span>{title}</button>{lab.number===119&&<SlamStepArt step={i}/>}<p>{text}</p></li>)}</ol></Card>,
 signal:<Card name="signal" title="Signal & Data Flow">{lab.number===124?<RouterSignal/>:lab.number===119?<><SlamDataFlow/><details><summary>Odometry drift trace</summary>{result.traces.map(t=><Waveform key={t.label} trace={t}/>)}</details></>:lab.number===116?<><IndustrialSignal/><details><summary>Joint response curve</summary>{result.traces.map(t=><Waveform key={t.label} trace={t}/>)}</details></>:lab.number===118?<><LidarDataFlow p={p} mode={mode} time={time}/><details><summary>Odometry drift trace</summary>{result.traces.map(t=><Waveform key={t.label} trace={t}/>)}</details></>:<><div className="rb-flow">{lab.number===122?lab.steps.map(([t])=><span key={t}>{t} ↓</span>):lab.architecture!.processing.map(t=><span key={t}>{t} →</span>)}</div>{result.traces.map(t=><Waveform key={t.label} trace={t}/>)}</>}</Card>,
 simulation:<Card name="simulation" title={lab.number===124?"Simulation & Control":"Interactive Simulation & Control Panel"}><div className={`rb-simulation ${arm?"arm":""}`}><div className="rb-live">{display}{extras}{lab.number===115&&result.traces[0]&&<details><summary>Pitch response curve</summary><Waveform trace={result.traces[0]}/></details>}<dl className={`sy-metrics ${lab.number===117?"rb-cobot-feedback":""}`}>{result.metrics.slice(0,lab.number===123?2:4).map(m=><div key={m.label}><dt>{m.label}</dt><dd>{m.value} {m.unit}</dd></div>)}</dl></div><div>{controls}</div></div><details className="sy-measurements"><summary>All simulation results</summary>{metrics}</details>{events.length>0&&<details><summary>Local event log ({events.length})</summary>{events.map((e,i)=><p key={i}>{e}</p>)}</details>}</Card>,
 applications:<Card name="applications" title="Real-World Applications"><div className="rb-applications">{lab.applications.map((a,i)=><p key={a}>{[115,116,117,118,119,121,122,123,124].includes(lab.number)&&<img src={art(lab.number,`application-${i}`)} alt={a}/>}◈ {a}</p>)}</div></Card>,
 keys:<Card name="keys" title="Key Takeaways">{lab.number===123&&<><p>✓ Perception estimates body state and terrain</p><p>✓ Gait planning coordinates stance and swing phases</p><p>✓ Inverse kinematics converts foot targets to joint angles</p><p>✓ Joint feedback controls leg torque and position</p><p>✓ IMU and foot sensing support body balance</p></>}{lab.number===122&&<><p>✓ Hardware, illumination and software work together</p><p>✓ Controlled lighting makes image measurements repeatable</p><p>✓ Processing extracts geometry and defect evidence</p><p>✓ Classification turns measurements into a decision</p><p>✓ Digital I/O connects inspection to production control</p></>}{lab.number===121&&<><p>✓ Mechanical lift and motion control work together</p><p>✓ Sensor fusion supports reliable indoor navigation</p><p>✓ Encoders close the positioning and lift loops</p><p>✓ Task communication connects warehouse workflows</p></>}{lab.number===120&&<><p>✓ Camera and range sensing observe the ground environment</p><p>✓ GNSS and wheel odometry support position estimates</p><p>✓ Steering angle and wheelbase determine turning rate</p><p>✓ Guidance commands traction and steering separately</p><p>✓ An obstacle supervisor can brake forward travel</p></>}{lab.number===119&&<><p>✓ SLAM estimates pose while updating a map</p><p>✓ LiDAR, IMU and encoders provide complementary inputs</p><p>✓ Occupancy evidence marks free and occupied cells</p><p>✓ Planning finds a route from start to goal</p><p>✓ Feedback updates pose and navigation commands</p></>}{lab.number===116&&<><p>✓ Real-time control coordinates multiple robot joints</p><p>✓ Servo drives close position loops using encoders</p><p>✓ Safety inputs independently inhibit drive commands</p><p>✓ I/O manages grippers and production tools</p><p>✓ Fieldbus communication links external automation</p></>}{lab.number===115&&<><p>✓ An IMU combines acceleration and angular-rate sensing</p><p>✓ Angle estimation provides real-time tilt feedback</p><p>✓ PID uses proportional, integral and derivative terms</p><p>✓ Motor drivers convert control demand into wheel torque</p><p>✓ Wheel motion moves the base beneath the body</p><p>✓ Fast repeated feedback is essential for balance</p></>}{lab.safety.map(s=><p key={s}>✓ {s}</p>)}<details><summary>Quick Quiz</summary><Quiz lab={lab}/></details><details><summary>Technical reference</summary><a href={lab.source} target="_blank" rel="noreferrer">Engineering reference</a></details></Card>
 };
 const hero=[118,121,124].includes(lab.number);
 return <div className={`sy-lab rb-lab rb-lab-${lab.number}`}><header className="sy-header"><Link to={STUDIO_PATH}>Device {lab.number}<small>How Devices Work</small></Link><nav><a href="#internal">Hardware</a><a href="#architecture">Architecture</a><a href="#simulation">Simulation</a><a href="#applications">Applications</a></nav><Link to={STUDIO_PATH}>All devices →</Link></header>{lab.number===117&&<aside className="rb-cobot-sidebar"><Link to={STUDIO_PATH}>◈ How Devices Work</Link><a href="#overview">Device overview</a><a href="#internal">Internal parts</a><a href="#architecture">System diagram</a><a href="#simulation">Interactive lab</a><a href="#applications">Applications</a><a href="#keys">Knowledge check</a></aside>}<main className="sy-main"><DeviceCourse lab={lab} onTabChange={tab=>{if(tab!=="simulation")setRunning(false);}}><div className={`rb-hero ${hero?"with-art":""}`}><div><h1>Device {lab.number} — {lab.device.name}</h1><h3>{lab.subtitle}</h3>{(hero||lab.number===122)&&<p>{lab.principle.split(".").slice(0,2).join(".")}.</p>}<a className="sy-primary" href="#simulation">Start lab →</a></div>{hero&&<img src={art(lab.number,"device")} alt={`${lab.device.name} source hardware`}/ >}{lab.number===118&&<LidarPointCloud p={p} mode={mode} time={time}/>}</div><div className="rb-dashboard">{itemAt(layouts, lab.number).map(([name,column,span,row])=><div className={`rb-slot rb-slot-${name}`} key={name} style={{gridColumn:`${column}/span ${span}`,gridRow:row}}>{panels[name]}</div>)}</div><footer><Link to={STUDIO_PATH}>← All devices</Link><span>Device {lab.number} · How Devices Work</span></footer></DeviceCourse></main></div>;
}





