import {parameterValue,itemAt} from './parameters';
import type {AdvancedLab} from "./data";
import type {AdvancedResult} from "./engine";
import type {Metric,Trace} from "../labs/engine";
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
export type Cell={x:number;y:number};
export function gridPath(grid:number[][],start:Cell,goal:Cell):Cell[]{
 const size=grid.length,key=(c:Cell)=>c.y*size+c.x;
 if(!grid[start.y]||!grid[goal.y]||itemAt(itemAt(grid, start.y), start.x)!==0||itemAt(itemAt(grid, goal.y), goal.x)!==0)return [];
 const queue=[start],seen=new Set([key(start)]),parent=new Map<number,Cell>();
 for(let q=0;q<queue.length;q++){const current=itemAt(queue,q);if(key(current)===key(goal)){const path=[current];while(key(itemAt(path, 0))!==key(start))path.unshift(parent.get(key(itemAt(path, 0)))!);return path;}for(const [dx,dy] of [[1,0],[0,-1],[-1,0],[0,1]] as const){const next={x:current.x+dx,y:current.y+dy};if(next.x<0||next.y<0||next.x>=size||next.y>=size||itemAt(itemAt(grid, next.y), next.x)!==0||seen.has(key(next)))continue;seen.add(key(next));parent.set(key(next),current);queue.push(next);}}
 return [];
}
export function roomGrid(warehouse=false,obstacle=-1){const size=18;return Array.from({length:size},(_,y)=>Array.from({length:size},(_,x)=>x===0||y===0||x===size-1||y===size-1||y*size+x===obstacle|| (warehouse?x>=4&&x<=13&&[4,5,8,9,12,13].includes(x)&&y>=3&&y<=13&&y!==8:x===8&&y>2&&y<14&&y!==8||y===5&&x>9&&x<15)?1:0));}
export function rayScan(grid:number[][],pose:Cell,count:number,maxRange:number,angle=0){const rays:{angle:number;range:number;x:number;y:number;hit:boolean}[]=[];for(let i=0;i<count;i++){const a=angle+i/count*Math.PI*2;let distance=0,hit=false;for(distance=.05;distance<maxRange;distance+=.05){const x=Math.floor(pose.x+Math.cos(a)*distance),y=Math.floor(pose.y+Math.sin(a)*distance);if(!grid[y]||grid[y][x]!==0){hit=true;break;}}distance=Math.min(distance,maxRange);rays.push({angle:a,range:distance,x:pose.x+Math.cos(a)*distance,y:pose.y+Math.sin(a)*distance,hit});}return rays;}
export function navigationScene(number:number,p:Record<string,number>,mode:string,time:number){
 const warehouse=number===121,grid=roomGrid(warehouse,p.obstacle??-1),start={x:Math.round(p.startx??2),y:Math.round(p.starty??14)},stations=[{x:2,y:2},{x:7,y:2},{x:11,y:15},{x:15,y:8}],goal=warehouse?itemAt(stations,clamp(Math.round(parameterValue(p, 'station'))-1,0,3)):{x:Math.round(p.goalx??16),y:Math.round(p.goaly??2)};
 const path=gridPath(grid,start,goal),speed=(["Manual","Mapping only","Lift only","Obstacle blocked"].includes(mode)?0:(p.speed??.5))/(warehouse?1+(p.load??0)/100:1),distance=mode==="Manual"||mode==="Mapping only"||mode==="Lift only"||mode==="Obstacle blocked"||!path.length?0:time*speed*2,index=Math.min(Math.max(0,path.length-1),Math.floor(distance)),fraction=index>=path.length-1?0:distance-Math.floor(distance),from=path[index]??start,to=path[Math.min(index+1,path.length-1)]??start,pose={x:from.x+.5+(to.x-from.x)*fraction,y:from.y+.5+(to.y-from.y)*fraction};
 const drift=(p.bias??0)*time*(mode==="Landmark correction"?.1:mode==="Odometry only"?1:.4),estimated={x:pose.x+drift,y:pose.y},count=Math.round(p.rays??72),range=(p.range??8)*2,scan=rayScan(grid,pose,count,range),known=grid.map(row=>row.map(()=>-1));
 for(let frame=0;frame<=Math.min(index,30);frame++){const point=path[frame]??start,origin={x:point.x+.5,y:point.y+.5},bias=(p.bias??0)*frame/(speed*2||1)*(mode==="Landmark correction"?.1:mode==="Odometry only"?1:.4);for(const ray of rayScan(grid,origin,count,range)){for(let d=0;d<ray.range;d+=.25){const x=Math.floor(origin.x+Math.cos(ray.angle)*d+bias),y=Math.floor(origin.y+Math.sin(ray.angle)*d);if(known[y]&&x>=0&&x<18)known[y][x]=0;}if(ray.hit){const x=Math.floor(ray.x+bias),y=Math.floor(ray.y);if(known[y]&&x>=0&&x<18)known[y][x]=1;}}}
 return {grid,known,path,pose,estimated,scan,drift,speed,goal,progress:path.length?clamp(distance/Math.max(1,path.length-1),0,1):0};
}
export function balanceResponse(p:Record<string,number>,mode:string,time:number){let angle=parameterValue(p, 'initial')*Math.PI/180,rate=0,integral=0,demand=0,lost=false;const target=parameterValue(p, 'setpoint')*Math.PI/180,history:{time:number;angle:number;rate:number;demand:number;lost:boolean}[]=[];for(let i=0;i<=Math.ceil(time/.01);i++){const t=i*.01,error=angle-target;if(i>0&&!lost){integral=clamp(integral+error*.01,-1,1);demand=mode==="Controller disabled"?0:clamp(parameterValue(p, 'kp')*error+parameterValue(p, 'ki')*integral+parameterValue(p, 'kd')*rate,-4,4);rate+=(20*angle-.8*demand-.8*rate+(mode==="Push disturbance"&&t>2&&t<2.2?5:0))*.01;angle+=rate*.01;if(Math.abs(angle)>.6){lost=true;demand=0;}}history.push({time:t,angle:angle*180/Math.PI,rate:rate*180/Math.PI,demand:demand/4*100,lost});}return history;}
export function armPoints(joints:number[]){const lengths=[.45,.35,.2];let x=0,z=.2,angle=Math.PI/2;const points=[{x,z}];for(let i=0;i<3;i++){angle+=itemAt(joints, i+1)*Math.PI/180;x+=Math.cos(angle)*itemAt(lengths, i);z+=Math.sin(angle)*itemAt(lengths, i);points.push({x,z});}const yaw=itemAt(joints, 0)*Math.PI/180;return {points,x:x*Math.cos(yaw),y:x*Math.sin(yaw),z,wrist:joints.slice(3)};}
export function legIK(x:number,z:number,length=.23){const raw=(x*x+z*z-2*length*length)/(2*length*length),reachable=raw>=-1&&raw<=1,knee=-Math.acos(clamp(raw,-1,1)),hip=Math.atan2(x,z)-Math.atan2(length*Math.sin(knee),length+length*Math.cos(knee));return {hip:hip*180/Math.PI,knee:knee*180/Math.PI,reachable};}
export function gaitState(p:Record<string,number>,mode:string,time:number){const offsets=mode==="Trot"?[0,.5,.5,0]:mode==="Bound"?[0,0,.5,.5]:[0,.5,.75,.25],frequency=parameterValue(p, 'speed')?1+parameterValue(p, 'speed'):0;return offsets.map((offset,i)=>{const phase=mode==="Stand"?0:(time*frequency+offset)%1,contact=mode==="Stand"||phase<.6,stride=mode==="Stand"?0:parameterValue(p, 'speed')*.15,x=stride*Math.cos(phase*2*Math.PI),z=parameterValue(p, 'height')+(i<2?1:-1)*.18*Math.tan(parameterValue(p, 'pitch')*Math.PI/180)+(i%2?1:-1)*.12*Math.tan(parameterValue(p, 'roll')*Math.PI/180)-(contact?0:.05*Math.sin((phase-.6)/.4*Math.PI));return {...legIK(x,z),x,z,contact,phase};});}
export function inspectPixels(p:Record<string,number>,mode:string){const size=64,light=parameterValue(p, 'light')/100*(mode==="Poor illumination"?.3:1),missing=mode==="Missing feature"?Math.max(6,parameterValue(p, 'defect')):parameterValue(p, 'defect'),pixels=Array.from({length:size},(_,y)=>Array.from({length:size},(_,x)=>{const r=Math.hypot(x-32,y-32),cut=x>32&&Math.abs(y-32)<missing&&r>15;return Math.round((25+195*clamp(Math.min((r-12)/2,(25-r)/2),0,1)*(cut?0:1))*light);})),binary=pixels.map(row=>row.map(v=>v>40+(1-parameterValue(p, 'edge'))*100?1:0)),seen=new Set<number>();let area=0,components=0,cx=0,cy=0;for(let y=0;y<size;y++)for(let x=0;x<size;x++){const key=y*size+x;if(!itemAt(binary, y)[x]!||seen.has(key))continue;components++;const queue=[{x,y}];seen.add(key);for(let q=0;q<queue.length;q++){const c=itemAt(queue,q);area++;cx+=c.x;cy+=c.y;for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]] as const){const nx=c.x+dx,ny=c.y+dy,k=ny*size+nx;if(nx>=0&&ny>=0&&nx<size&&ny<size&&itemAt(itemAt(binary, ny), nx)&&!seen.has(k)){seen.add(k);queue.push({x:nx,y:ny});}}}}
 const expected=1500,defect=clamp(1-area/expected,0,1),accept=area>=parameterValue(p, 'area')&&defect<=parameterValue(p, 'threshold')&&components===1;return {pixels,binary,area,components,centroid:{x:area?cx/area:0,y:area?cy/area:0},defect,accept};}
export function simulateRobotics(lab:AdvancedLab,p:Record<string,number>,mode:string,time:number,fault:boolean):AdvancedResult{
 const metrics:Metric[]=[],traces:Trace[]=[],visual:number[]=[];let valid=true,status="Local teaching model ready",progress=clamp(time/20,0,1);
 const metric=(label:string,value:number|string,unit="")=>metrics.push({label,value:typeof value==="number"?Number(value.toFixed(3)):value,unit});
 const trace=(label:string,unit:string,span:number,fn:(t:number)=>number)=>traces.push({label,unit,color:"#278cdd",timeSpan:span,axisLabel:`${span} s`,samples:Array.from({length:240},(_,i)=>fn(i/239*span))});
 switch(lab.family){
 case "balance":{const states=balanceResponse(p,mode,time),s=states.at(-1)!;metric("Pitch angle",s.angle,"°");metric("Gyro rate",s.rate,"°/s");metric("Control error",parameterValue(p, 'setpoint')-s.angle,"°");metric("Motor demand",s.demand,"%");metric("Controller",mode);visual.push(s.angle,s.demand,s.rate);status=s.lost?"Balance lost — reset to return near upright":"Balancing with reduced feedback dynamics";const full=balanceResponse(p,mode,10);trace("Body pitch","°",10,t=>itemAt(full, Math.min(full.length-1,Math.floor(t/.01))).angle);break;}
 case "industrial-arm":case "cobot":{const cobot=lab.family==="cobot",stopped=p.estop===1||p.enabled===0||(cobot&&parameterValue(p, 'contact')>parameterValue(p, 'force')),slow=cobot&&mode==="Safety monitored motion"?clamp((parameterValue(p, 'distance')-.2)/1,0,1):1,speed=stopped?0:parameterValue(p, 'speed')/100*slow,alpha=1-Math.exp(-Math.max(0,time-(p.motionStart??0))*speed*2),joints=Array.from({length:6},(_,i)=>{const target=mode==="Program Run"?itemAt(p, `j${i+1}`)+15*Math.sin(time*.5+i):parameterValue(p,`j${i+1}`);return stopped?(p[`hold${i+1}`]??0):(p[`start${i+1}`]??0)+(target-(p[`start${i+1}`]??0))*alpha;}),pose=armPoints(joints);joints.forEach((v,i)=>metric(`Joint ${i+1} feedback`,v,"°"));metric("TCP X",pose.x,"m");metric("TCP Y",pose.y,"m");metric("TCP Z",pose.z,"m");metric("Speed scale",speed*100,"%");if(cobot){metric("Contact force",parameterValue(p, 'contact'),"N");metric("Force limit",parameterValue(p, 'force'),"N");metric("Human proximity",parameterValue(p, 'distance'),"m");}visual.push(...joints,pose.x,pose.y,pose.z);status=stopped?"Protective stop — virtual drives inhibited":cobot&&slow<1?"Proximity reduces commanded speed":"Virtual drives enabled / joint feedback active";trace("Joint 2 response","°",10,t=>parameterValue(p, 'j2')*(1-Math.exp(-t*speed*2)));break;}
 case "lidar-robot":case "slam":case "warehouse":{const scene=navigationScene(lab.number,p,mode,time),blocked=!scene.path.length||mode==="Obstacle blocked";metric("Pose X",scene.estimated.x/2,"m");metric("Pose Y",scene.estimated.y/2,"m");metric("Speed",blocked?0:scene.speed,"m/s");metric("Position drift",scene.drift/2,"m");metric("Reference path length",scene.path.length? (scene.path.length-1)/2:"No route","m");metric("Measured scan points",scene.scan.length);metric("Mapped cells",scene.known.flat().filter(v=>v>=0).length);metric("Occupied endpoints",scene.known.flat().filter(v=>v===1).length);if(lab.number===121){const lift=mode==="Lift only"?parameterValue(p, 'lift')*(1-Math.exp(-time/2)):scene.progress>.95?parameterValue(p, 'lift')*Math.min(1,(time-(scene.path.length-1)/scene.speed/2)/2):0;metric("Lift height",Math.max(0,lift),"m");metric("Payload",parameterValue(p, 'load'),"kg");metric("Target station",parameterValue(p, 'station'));visual.push(Math.max(0,lift));}visual.push(scene.pose.x,scene.pose.y,scene.drift);progress=scene.progress;status=blocked?"No free reference-grid route — motion inhibited":scene.progress>=1?"Goal reached / virtual task ready":"Computed reference-grid route / ray-derived map";trace("Odometry drift","m",60,t=>(p.bias??0)*t/2*(mode==="Landmark correction"?.1:mode==="Odometry only"?1:.4));break;}
 case "autonomous-vehicle":{const stopped=mode==="Obstacle braking"&&parameterValue(p, 'distance')<1,speed=stopped?0:parameterValue(p, 'speed'),yaw=speed*Math.tan(parameterValue(p, 'steer')*Math.PI/180)/parameterValue(p, 'wheelbase'),x=Math.abs(yaw)<1e-9?speed*time:speed/yaw*Math.sin(yaw*time),y=Math.abs(yaw)<1e-9?0:speed/yaw*(1-Math.cos(yaw*time));metric("Vehicle speed",speed,"m/s");metric("Yaw rate",yaw*180/Math.PI,"°/s");metric("X position",x,"m");metric("Y position",y,"m");metric("Obstacle distance",parameterValue(p, 'distance'),"m");metric("Wheelbase",parameterValue(p, 'wheelbase'),"m");metric("Position source",mode==="GNSS-corrected pose"?"Synthetic GNSS update":"Wheel motion estimate");visual.push(x,y,yaw*time*180/Math.PI);status=stopped?"Obstacle braking — virtual drive stopped":"Reduced bicycle-model trajectory";trace("Yaw angle","°",20,t=>yaw*t*180/Math.PI);break;}
 case "machine-vision":{const s=inspectPixels(p,mode);metric("Foreground area",s.area,"pixels");metric("Defect score",s.defect);metric("Connected components",s.components);metric("Centroid X",s.centroid.x,"px");metric("Centroid Y",s.centroid.y,"px");metric("Inspection result",s.accept?"ACCEPT":"REJECT");metric("Threshold",parameterValue(p, 'threshold'));visual.push(s.accept?1:0,s.area,s.defect);status=s.accept?"ACCEPT — measured pixels satisfy the limits":"REJECT — measured features fail the limits";trace("Row 32 grayscale","level",64,t=>itemAt(itemAt(s.pixels, 32), clamp(Math.floor(t),0,63)));break;}
 case "quadruped":{const legs=gaitState(p,mode,time);legs.forEach((leg,i)=>{metric(`Leg ${i+1} hip`,leg.hip,"°");metric(`Leg ${i+1} knee`,leg.knee,"°");metric(`Foot ${i+1} contact`,leg.contact?"Stance":"Swing");visual.push(leg.hip,leg.knee,leg.contact?1:0);});metric("Speed target",mode==="Stand"?0:parameterValue(p, 'speed'),"m/s");metric("Body height",parameterValue(p, 'height'),"m");status=legs.every(l=>l.reachable)?"Foot targets within reduced leg reach":"Foot target exceeds leg reach — inspect body pose";trace("Front-left hip","°",4,t=>itemAt(gaitState(p,mode,t), 0).hip);break;}
 case "wifi-router":{const band=mode==="2.4 GHz"?2.4:5,channelLoss=(mode==="5 GHz"?0:[{channel:1,load:24},{channel:6,load:8},{channel:11,load:18}].reduce((sum,ap)=>sum+ap.load*Math.max(0,1-Math.abs(parameterValue(p, 'channel')-ap.channel)/5),0)),signal=-32+10*Math.log10(parameterValue(p, 'power')/100)-20*Math.log10(parameterValue(p, 'distance'))-(band===5?6:0),snr=signal+95,quality=clamp((snr-5)/35,0,1),capacity=(mode==="Dual-band"?650:band===5?450:150)*quality*(1-parameterValue(p, 'interference')/120)*(1-channelLoss/100),total=capacity/(1+.02*(parameterValue(p, 'clients')-1));metric("Signal strength",signal,"dBm");metric("Total payload throughput",total,"Mbps");metric("Per-client fair share",total/parameterValue(p, 'clients'),"Mbps");metric("Connected clients",parameterValue(p, 'clients'));metric("Selected channel",parameterValue(p, 'channel'));metric("Interference",parameterValue(p, 'interference'),"%");metric("Synthetic adjacent-channel load",channelLoss,"%");metric("SNR estimate",snr,"dB");visual.push(signal,total,total/parameterValue(p, 'clients'),parameterValue(p, 'clients'));status="Shared-airtime throughput illustration / local settings";trace("Aggregate payload","Mbps",10,t=>total*(.94+.06*Math.sin(t*1.7)));break;}
 default:throw new Error(`Unsupported robotics family ${lab.family}`);
 }
 if(fault){valid=false;status="Sensor / control fault — dependent outputs unavailable";metrics.forEach(m=>{m.value="Unavailable";m.unit="";});traces.forEach(t=>t.samples.fill(0));visual.fill(0);progress=0;}
 return {metrics,traces,visual,valid,status,progress};
}

