import {parameterValue,itemAt} from './parameters';
import type { AdvancedLab } from "./data";
import type { AdvancedResult } from "./engine";
import type { Metric,Trace } from "../labs/engine";
const clamp=(x:number,a:number,b:number)=>Math.max(a,Math.min(b,x));
const c=299792458,rad=Math.PI/180;
export function compassField(p:Record<string,number>){const yaw=parameterValue(p, 'yaw')*rad,pitch=parameterValue(p, 'pitch')*rad,roll=parameterValue(p, 'roll')*rad,x=22*Math.cos(yaw),y=22*Math.sin(yaw),z=42;const bx=x*Math.cos(pitch)-z*Math.sin(pitch),by=x*Math.sin(roll)*Math.sin(pitch)+y*Math.cos(roll)+z*Math.sin(roll)*Math.cos(pitch),bz=x*Math.cos(roll)*Math.sin(pitch)-y*Math.sin(roll)+z*Math.cos(roll)*Math.cos(pitch);return [bx+parameterValue(p, 'offset'),by,bz] as const;}
export function compassHeading(p:Record<string,number>,mode:string){const [rx,ry,rz]=compassField(p),x=rx-(mode==="Calibrated offset"?parameterValue(p, 'offset'):0),pitch=parameterValue(p, 'pitch')*rad,roll=parameterValue(p, 'roll')*rad,hx=mode==="Uncompensated"?x:x*Math.cos(pitch)+ry*Math.sin(roll)*Math.sin(pitch)+rz*Math.cos(roll)*Math.sin(pitch),hy=mode==="Uncompensated"?ry:ry*Math.cos(roll)-rz*Math.sin(roll);return (Math.atan2(hy,hx)/rad+parameterValue(p, 'declination')+720)%360;}
export function simulateSecurity(lab:AdvancedLab,p:Record<string,number>,mode:string,time:number,fault:boolean):AdvancedResult{
 const n=(key:string,d=0)=>p[key]??d,metrics:Metric[]=[],traces:Trace[]=[],visual:number[]=[];let valid=true,status="Ready — teaching model",progress=clamp(time/10,0,1);
 const metric=(label:string,value:number|string,unit="")=>metrics.push({label,value:typeof value==="number"?Number(value.toFixed(4)):value,unit});
 const trace=(label:string,unit:string,color:string,span:number,fn:(t:number)=>number,axisLabel=`${span} s`)=>traces.push({label,unit,color,timeSpan:span,axisLabel,samples:Array.from({length:240},(_,i)=>fn(i*span/239))});
 switch(lab.family){
 case "laser-ranging":{const factor=mode==="Bright target"?1.6:mode==="Dark target"?.25:1,reflectivity=n("reflectivity")/100*factor,delay=2*n("distance")/c*1e9,snr=100*reflectivity*(250/n("distance"))**2,sigma=n("jitter")*c/2/1e9/Math.sqrt(Math.max(.05,snr)),error=sigma*Math.sin(time*2.3+1.2),distance=n("distance")+error;metric("Measured distance",distance,"m");metric("Round-trip delay",delay,"ns");metric("Timing uncertainty",sigma,"m RMS");metric("Relative return SNR",snr);trace("Received optical pulse","relative","#179bea",delay*1.2+10,t=>reflectivity*Math.exp(-.5*((t-delay)/Math.max(.2,n("jitter")))**2),"ns delay");visual.push(distance,delay,snr,sigma);status=snr<.5?"Weak reflection — distance quality degraded":"Virtual time-of-flight measurement available";break;}
 case "sdr":{const carrier=mode==="Receive AM"?99.1:98.7,offset=(carrier-n("frequency"))*1000,fs=n("rate"),aliased=((offset+fs/2)%fs+fs)%fs-fs/2,power=-70+n("gain"),inBand=Math.abs(offset)<=n("bandwidth")/2,nyquist=n("bandwidth")>fs,active=inBand&&power>n("squelch");metric("Carrier frequency",carrier,"MHz");metric("Baseband offset",offset,"kHz");metric("Aliased offset",aliased,"kHz");metric("Received level",power,"dBm");metric("Channel bandwidth",n("bandwidth"),"kHz");metric("Integrated noise",-174+10*Math.log10(n("bandwidth")*1000)+n("gain")+6,"dBm");metric("Nyquist bandwidth",fs,"kHz");metric("Demodulated output",active?"Open":"Muted");trace("RF spectrum","dBm","#4b97ee",20,x=>-100+Math.sin(x*29+time)*2+(power+100)*Math.exp(-.5*((88+x-carrier)/.06)**2)+20*Math.exp(-.5*((88+x-104.5)/.04)**2),"88 → 108 MHz");trace("I/Q baseband","relative","#29a988",.02,t=>active?Math.cos(2*Math.PI*aliased*1000*t)*(mode==="Receive AM"?.5+.4*Math.sin(2*Math.PI*400*t):1):0,"20 ms");visual.push(carrier,offset,aliased,power,active?1:0,nyquist?1:0);status=nyquist?"Aliasing warning — channel bandwidth exceeds sample rate":!inBand?"Carrier outside tuned channel — output muted":active?"Synthetic signal selected — baseband processing active":"Squelch closed";break;}
 case "secure-radio":{const ber=.5*Math.exp(-(10**(n("snr")/10))),packetSuccess=(1-ber)**256*(1-n("loss")/100),rate=n("rate")*packetSuccess,auth=mode==="Authenticated link";metric("Bit-error bound",ber);metric("Packet delivery",packetSuccess*100,"%");metric("Delivered payload",auth?rate:0,"kbps");metric("Authentication",auth?"Verified teaching state":"Rejected");trace("Illustrative link error bound","probability","#2689dd",30,snr=>.5*Math.exp(-(10**(snr/10))),"0 → 30 dB SNR");visual.push(packetSuccess,rate,auth?1:0);status=auth?"Local authenticated packet demonstration ready":"Verification failure — plaintext withheld";break;}
 case "iff":{const code=String(Math.round(n("code"))).padStart(4,"0"),verified=!mode.endsWith("unverified");valid=/^[0-7]{4}$/.test(code);metric("Identity code",code);metric("Interrogation",1030,"MHz");metric("Response",1090,"MHz");metric("Round-trip propagation",2*n("range")*1000/c*1e6,"µs");metric("Processing latency",n("delay"),"µs");metric("Identification",verified?"Valid teaching reply":"Unknown — verification failed");trace("Virtual interrogation / response","logic","#2b8ad6",1000,t=>t<5?1:t>2*n("range")*1000/c*1e6+n("delay")&&t<2*n("range")*1000/c*1e6+n("delay")+8&&verified?1:0,"µs");visual.push(n("range"),verified&&valid?1:0,n("delay"));status=!valid?"Invalid identity — four octal digits required":verified?"Virtual reply decoded; no operational identity assertion":"Unknown — no authenticated response";break;}
 case "electronic-id":{const readable=n("distance")<=8&&n("timeout")>=100,authorized=time>0&&readable&&mode==="Valid employee card";metric("Credential",readable?"SYN-1024587":"No readable response");metric("Authorization",authorized?"Access granted":"Access denied");metric("Reader response time",readable?100:"Timeout","ms");metric("Virtual lock",authorized?"Unlocked":"Locked");metric("Policy reason",!readable?"Out of field / timeout":mode==="Unknown card"?"Not enrolled":mode==="Expired card"?"Expired":mode==="Revoked card"?"Revoked":"Active employee policy");visual.push(authorized?1:0,readable?1:0);progress=time>0?1:0;status=time===0?"Present a credential — tap to evaluate access":authorized?"Synthetic credential authorized — virtual access granted":"Access denied — virtual lock remains closed";break;}
 case "gps-receiver":{const count=n("satellites")+(mode==="Multi-constellation"?4:0),dop=n("geometry")*Math.sqrt(8/Math.max(4,count)),sigma=n("noise")*dop*(mode==="Urban multipath"?3:1),lat=37.4275+sigma*Math.sin(time*.7)/111320,lon=-122.1697+sigma*Math.cos(time*.7)/(111320*Math.cos(37.4275*rad));valid=count>=4&&n("strength")>=28;metric("Latitude",lat,"° N");metric("Longitude",Math.abs(lon),"° W");metric("Satellites used",count);metric("Geometry dilution",dop);metric("Position error RMS",sigma,"m");metric("Signal C/N0",n("strength"),"dB-Hz");metric("Fix",valid?"3D teaching fix":"No valid fix");trace("Illustrative position error","m","#2289e4",60,t=>sigma*Math.sin(t*.7));visual.push(lat,lon,count,dop,sigma);status=valid?"Synthetic GNSS solution available":"Insufficient satellites or C/N0 — no position output";break;}
 case "electronic-compass":{const field=compassField(p),heading=compassHeading(p,mode);metric("Heading",heading,"°");metric("Raw Hx",itemAt(field, 0),"µT");metric("Raw Hy",itemAt(field, 1),"µT");metric("Raw Hz",itemAt(field, 2),"µT");metric("Heading deviation",((heading-n("yaw")+540)%360)-180,"°");metric("Compensation",mode);trace("Heading at varying pitch","°","#2b87df",120,x=>compassHeading({...p,pitch:x-60},mode),"−60 → +60° pitch");visual.push(heading,...field,n("pitch"),n("roll"));status=mode==="Uncompensated"?"Uncompensated magnetic heading — tilt error visible":mode==="Calibrated offset"?"Hard-iron offset removed before tilt compensation":"Tilt-compensated magnetic heading";break;}
 case "ground-satellite":{const frequency=mode.startsWith("Ka")?30:mode.startsWith("C")?6:14,fspl=92.45+20*Math.log10(frequency)+20*Math.log10(36000),error=Math.hypot(n("azimuth")-180,n("elevation")-35),loss=Math.min(60,12*(error/2)**2),received=n("power")+30+42+40-fspl-loss,noise=-174+10*Math.log10(n("rate")*1e6)+2,snr=received-noise,ber=Math.min(.5,.5*Math.exp(-(10**(snr/10)))),throughput=snr<3?0:n("rate")*(1-ber);metric("Received signal",received,"dBm");metric("SNR",snr,"dB");metric("Payload throughput",throughput,"Mbps");metric("Error bound",ber);metric("Free-space loss",fspl,"dB");metric("Pointing loss",loss,"dB");visual.push(n("azimuth"),n("elevation"),snr,throughput);trace("Pointing-loss pattern","dB","#2288df",20,x=>Math.min(60,12*((x-10)/2)**2),"−10 → +10° error");status=snr<3?"Link margin insufficient — payload inhibited":"Ground terminal connected — illustrative link";break;}
 case "perimeter":{const event=mode==="Wind disturbance"?.3:mode==="Animal motion"?.6:1,signal=clamp(n("strength")*event-n("noise")*.35,0,100),persistent=n("persistence")>=.5,alarm=time>0&&signal>=n("threshold")&&persistent;metric("Filtered event",signal,"%");metric("Persistence qualified",persistent?"Yes":"No");metric("Alarm state",alarm?"Virtual alarm active":"Monitoring");metric("Event classification",mode);metric("Local notification",alarm?"Displayed locally":"None");trace("Sensor / persistence envelope","%","#e46561",6,t=>t<1?0:t<1+n("persistence")?signal:0);visual.push(signal,alarm?1:0,persistent?1:0);status=time===0?"Ready — run detection to evaluate the event":alarm?"Synthetic intrusion criterion met — local event recorded":"Below alarm criterion — monitoring";break;}
 default:throw new Error(`Unsupported security family ${lab.family}`);
 }
 if(fault){valid=false;status="Acquisition / component fault — dependent outputs unavailable";}
 if(!valid){metrics.forEach(m=>{m.value="Unavailable";m.unit="";});traces.forEach(t=>t.samples.fill(0));visual.fill(0);progress=0;}
 return {metrics,traces,visual,status,valid,progress};
}
