import { useState } from "react";
import type { Lab } from "./data";
import type { LabResult, Trace } from "./engine";
import FrontEnd from "./FrontEnd";

export function Waveform({trace}: {trace: Trace}) {
 const [cursor,setCursor]=useState<number|null>(null);
 const min=Math.min(0,...trace.samples),max=Math.max(...trace.samples,min+.01),range=max-min;
 const xMax=trace.xSamples?Math.max(.01,...trace.xSamples):1;
 const points=trace.samples.map((v,i)=>`${40+(trace.xSamples?(trace.xSamples[i]??0)/xMax:i/(trace.samples.length-1))*550},${112-(v-min)/range*87}`).join(" ");
 return <figure className="dl-wave"><figcaption><strong style={{color:trace.color}}>{trace.label}</strong><span>{trace.unit}</span></figcaption><svg viewBox="0 0 610 145" role="img" aria-label={`${trace.label} waveform`} onPointerMove={e=>{const r=e.currentTarget.getBoundingClientRect();const fraction=Math.max(0,Math.min(1,((e.clientX-r.left)/r.width*610-40)/550));setCursor(trace.xSamples?trace.xSamples.reduce((best,x,i)=>Math.abs(x-fraction*xMax)<Math.abs((trace.xSamples?.[best]??0)-fraction*xMax)?i:best,0):Math.round(fraction*(trace.samples.length-1)));}} onPointerLeave={()=>setCursor(null)}><g className="dl-grid-lines">{[25,54,83,112].map(y=><path key={y} d={`M40 ${y}H590`}/>)}{[40,150,260,370,480,590].map(x=><path key={x} d={`M${x} 25V112`}/>)}</g><g className="dl-axis"><text x="3" y="30">{max.toFixed(1)}</text><text x="3" y="115">{min.toFixed(1)}</text><text x="40" y="136">0</text><text x="590" y="136" textAnchor="end">{trace.axisLabel}</text></g><polyline points={points} fill="none" stroke={trace.color} strokeWidth="2"/>{cursor!==null&&<><path d={`M${40+(trace.xSamples?(trace.xSamples[cursor]??0)/xMax:cursor/(trace.samples.length-1))*550} 25V112`} stroke="currentColor" strokeDasharray="3 3"/><text x="280" y="18">{trace.xSamples?`${trace.xSamples[cursor]?.toFixed(2)} ${trace.xUnit} · `:""}{trace.samples[cursor]?.toFixed(3)} {trace.unit}</text></>}</svg></figure>;
}

export function Circuit({lab,selected}:{lab:Lab;selected:number}) {
 const bridge=["scale","composition"].includes(lab.engine), optical=["oximeter","heart","hearing","audio","glucose","infrared"].includes(lab.engine),digital=["remote","nfc","phone","robot","autopilot"].includes(lab.engine);
 const specific:Partial<Record<Lab["engine"],string[]>>={mri:["RF excitation","Spins / gradients","RF receive chain","ADC","Reconstruction"],ct:["X-ray source","Rotating gantry","Detector array","ADC","Reconstruction"],xray:["X-ray source","Collimator","Pixel detector","ADC","Image processor"],mammography:["X-ray source","Compression / geometry","Pixel detector","ADC","Image processor"],pet:["Tracer events","Scintillators","Coincidence timing","Digitization","Reconstruction"],spect:["Gamma photons","Collimator","Scintillator / PMT","Event readout","Reconstruction"],ventilator:["Breath settings","Flow / pressure","Feedback controller","Blower / valves","Breathing circuit"],anesthesia:["Gas supply","Mixture / vapor","Breathing circuit","Supervisory sensors","Control / alarms"],dialysis:["Flow settings","Blood / dialysate","Dialyzer","Sensor supervision","Pump control"],pcr:["Cycle program","Thermal controller","Peltier / block","Thermistor feedback","Optical qPCR"],remote:["Key matrix","Command encoder","Carrier modulator","IR channel","TV decoder"],nfc:["Reader field","RF coupling","Protocol exchange","Secure credential","Transaction state"],pacemaker:["Sensing lead","Input front end","Escape timer","Virtual pulse","Capture feedback"],defibrillator:["ECG pads","Rhythm analysis","Charge supervision","Safety interlocks","Virtual event"],aed:["ECG pads","Rhythm analysis","Safety controller","Ready state","Virtual event"],icd:["Sensing lead","Rhythm analysis","Threshold / timing","Safety supervision","Virtual event"]};
 const blocks=specific[lab.engine]??(digital?[lab.sensor,"Interface","MCU / DSP","Driver",lab.parts.at(-1)!]:[lab.sensor,bridge?"Bridge amplifier":optical?"Sensor preamp / TIA":"Input amplifier","Anti-alias filter","ADC","MCU / DSP"]);
 return <div className="dl-circuit"><FrontEnd lab={lab}/><svg viewBox="0 0 680 175" role="img" aria-label={`${lab.device.name} conceptual acquisition circuit`}><defs><marker id={`arrow-${lab.number}`} markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0 0L8 4L0 8" fill="#429bff"/></marker></defs><path d="M40 26H640" stroke="#6aa6d8"/><text x="45" y="18">Regulated supply • decoupling at each stage</text>{blocks.map((label,i)=><g key={label}><rect x={12+i*134} y="58" width="120" height="61" rx="7" fill={selected===i?"#125db4":"#16324b"} stroke="#4a90c5"/><text x={72+i*134} y="81" textAnchor="middle" fill="#c4e5ff">{label.split(" ").slice(0,2).join(" ")}</text><text x={72+i*134} y="100" textAnchor="middle" fill="#c4e5ff">{label.split(" ").slice(2).join(" ")}</text>{i<4&&<path d={`M${132+i*134} 88h14`} stroke="#429bff" markerEnd={`url(#arrow-${lab.number})`}/>}<path d={`M${72+i*134} 119v24`} stroke="#6aa6d8"/></g>)}<path d="M40 143H640" stroke="#6aa6d8"/><text x="43" y="165">Signal return / reference • educational block circuit</text></svg><p>{lab.engine==="thermometer"?"10 kΩ NTC + 10 kΩ divider → buffered voltage → 12-bit ADC. Temperature is recovered using the β equation.":bridge?"A differential bridge signal is amplified before conversion. Excitation and reference must be stable.":optical?"A small sensor current or voltage is conditioned, filtered and sampled before digital analysis.":digital?"The controller validates input, updates system state and supervises the output interface.":"The sensor interface conditions the analog signal. Sampling and digital processing extract the device’s useful output."}</p></div>;
}

export function NuclearSlice({level,quality,slice=50,plane="Transverse"}:{level:number;quality:number;slice?:number;plane?:string}) {
 if(plane==="Cardiac")return <svg viewBox="0 0 180 180" role="img" aria-label="Synthetic myocardial tracer ring"><rect width="180" height="180" fill="#050b19"/><g style={{filter:`brightness(${level}) blur(${(1-quality)*3}px)`}}><ellipse cx="90" cy="85" rx="48" ry="57" fill="none" stroke="#ed5e32" strokeWidth="24"/><ellipse cx="90" cy="85" rx="44" ry="53" fill="none" stroke="#ffe452" strokeWidth="7"/></g><text x="9" y="171" fontSize="8" fill="#b0c2d7">Synthetic cardiac tracer phantom</text></svg>;
 if(plane==="Oncology")return <svg viewBox="0 0 180 180" role="img" aria-label="Synthetic whole-body tracer distribution"><rect width="180" height="180" fill="#050b19"/><g style={{filter:`brightness(${level}) blur(${(1-quality)*2}px)`}}><circle cx="90" cy="24" r="15" fill="#ad367f"/><path d="M70 43h40l15 53-15 4-8-25 3 80H92l-2-46-2 46H75l3-80-8 25-15-4Z" fill="#423279"/>{[[90,26,8],[94,62,7],[84,89,5],[102,100,6],[90,122,7]].map(([x,y,r])=><circle key={y} cx={x} cy={y} r={r} fill="#ffd543"/>)}<circle cx="93" cy="62" r="4" fill="#ff5532"/></g><text x="9" y="171" fontSize="8" fill="#b0c2d7">Synthetic whole-body tracer phantom</text></svg>;
 return <svg viewBox="0 0 180 180" role="img" aria-label={`Synthetic ${plane.toLowerCase()} tracer distribution, slice ${slice}`}><defs><radialGradient id={`uptake-${slice}`}><stop stopColor="#fff76e"/><stop offset=".35" stopColor="#ff7624"/><stop offset=".7" stopColor="#bd2259"/><stop offset="1" stopColor="#322b76"/></radialGradient></defs><rect width="180" height="180" rx="5" fill="#050b19"/><g transform={`translate(90 86) rotate(${plane==="Coronal"?90:plane==="Sagittal"?-25:0}) scale(${.72+slice/250})`} style={{filter:`brightness(${Math.max(.25,level)}) blur(${(1-quality)*2}px)`}}><ellipse rx="62" ry="72" fill="#29215f"/>{[-1,1].map(side=><g key={side}><ellipse cx={side*27} cy="-5" rx="23" ry="58" fill={`url(#uptake-${slice})`}/><ellipse cx={side*14} cy="-4" rx="9" ry="27" fill="#141439"/><ellipse cx={side*22} cy="38" rx="20" ry="17" fill="#ed572f" opacity={.35+quality*.6}/></g>)}<ellipse cy="59" rx="28" ry="13" fill="#d84b41"/></g><text x="8" y="171" fontSize="8" fill="#b0c2d7">Synthetic tracer phantom</text></svg>;
}

function AnatomyPhantom({lab,result,values,mode}:{lab:Lab;result:LabResult;values:Record<string,number>;mode:string}) {
 if(lab.number===7&&mode==="Head")return <figure className="dl-reference-scene"><img src="/device-labs/07-scene.webp?v=3" alt="Reference axial CT head section" style={{width:"100%",maxHeight:220,objectFit:"contain",filter:`contrast(${.7+result.quality}) brightness(${.45+result.imageLevel*.5})`}}/><figcaption>Reference axial section · simulated acquisition adjustments</figcaption></figure>;
 const chest=mode==="Chest"||(lab.engine==="xray"&&mode!=="Bone"&&mode!=="Soft tissue")||lab.engine==="detector";
 const bone=mode==="Bone"||mode==="Bone reconstruction";
 const abdominal=mode==="Abdomen"||mode==="Soft tissue";
 return <div className="dl-phantom" style={{filter:`contrast(${.7+result.quality}) brightness(${.45+result.imageLevel*.5})`}}><svg viewBox="0 0 240 200" role="img" aria-label={`${mode} synthetic anatomical phantom`}><rect width="240" height="200" fill="#07121b"/>
 {lab.engine==="mammography"?<g><path d="M30 15Q185 10 205 95Q208 171 30 178Z" fill="#747d85"/>{Array.from({length:12},(_,i)=><path key={i} d={`M38 ${24+i*12}Q${80+i*5} ${55+i*10} ${165-i*3} ${73+i*7}`} stroke="#b8bec6" opacity=".4" fill="none"/>)}<circle cx="149" cy="90" r="6" fill="#e6ecf0"/></g>:
 chest?<g><path d="M62 20q58-18 116 0l20 153H42Z" fill="#69757c"/><path d="M110 34q-57-30-58 106q10 27 57 17Z M130 34q57-30 58 106q-10 27-57 17Z" fill="#243c49"/><path d="M105 85q35-20 49 18q-3 31-36 34Z" fill="#8c999f"/>{Array.from({length:8},(_,i)=><g key={i} stroke="#b6c3c9" strokeWidth="3" fill="none"><path d={`M114 ${37+i*14}Q${63-i} ${24+i*12} ${52+i} ${62+i*11}`}/><path d={`M126 ${37+i*14}Q${177+i} ${24+i*12} ${188-i} ${62+i*11}`}/></g>)}<path d="M119 24v141" stroke="#a6b4bd" strokeWidth="6"/></g>:
 bone?<g fill="#bcc8cf"><path d="M80 20q-18-10-24 2t16 17l19 117q-8 25 9 24t13-21L95 37q22-19 4-24Z"/><path d="M130 20q-16-10-23 2t16 17l20 117q-8 25 9 24t12-21L145 37q22-19 4-24Z"/><path d="M83 48l17 100M132 48l18 100" stroke="#667781" strokeWidth="4"/></g>:
 abdominal?<g><ellipse cx="120" cy="96" rx="81" ry="78" fill="#7a8790"/><ellipse cx="120" cy="96" rx="71" ry="68" fill="#334450"/><ellipse cx="90" cy="68" rx="35" ry="22" fill="#8b9ca5"/><ellipse cx="161" cy="78" rx="16" ry="23" fill="#98abb5"/><ellipse cx="86" cy="115" rx="19" ry="27" fill="#748a98"/><ellipse cx="153" cy="115" rx="19" ry="27" fill="#748a98"/><circle cx="120" cy="144" r="16" fill="#ced8df"/></g>:
 <g transform={`rotate(${mode.includes("Coronal")?90:mode.includes("Sagittal")?-25:0} 120 95)`}><ellipse cx="120" cy="95" rx="70" ry="86" fill="#b1bdc1"/><ellipse cx="120" cy="95" rx="62" ry="78" fill="#374047"/><ellipse cx="93" cy="80" rx="22" ry="39" fill={mode.includes("T1")?"#a3b3bb":"#80919a"}/><ellipse cx="147" cy="80" rx="22" ry="39" fill={mode.includes("T1")?"#a3b3bb":"#80919a"}/><ellipse cx={110+(values.slice??50)*.2} cy="130" rx="19" ry="26" fill="#c6d2d5"/></g>}
 {Array.from({length:24},(_,i)=><path key={i} d={`M40 ${20+i*7}H200`} opacity={(1-result.quality)*.4} stroke="#fff"/>)}{lab.engine==="detector"&&mode==="Raw pixels"&&Array.from({length:16},(_,i)=><path key={i} d={`M${40+i*10} 20v150 M40 ${20+i*10}h160`} stroke="#779cae" opacity=".25"/>)}<text x="12" y="193" fill="#b6d9df" fontSize="9">Synthetic {mode.toLowerCase()} teaching phantom</text></svg></div>;
}

export function LiveVisual({lab,result,values,time,mode}:{lab:Lab;result:LabResult;values:Record<string,number>;time:number;mode:string}) {
 if(result.status.includes("inhibited"))return <div className="dl-invalid-reading"><strong>Output inhibited</strong><p>{result.status}</p><small>Clear the fault or restore a valid input to resume.</small></div>;
 if(lab.engine==="camera")return <div className="dl-camera-scene" style={{filter:`brightness(${result.imageLevel}) blur(${(1-result.quality)*5}px) sepia(${mode==="Tungsten"?.45:mode==="Daylight"?.12:0})`}}><svg viewBox="0 0 420 230" role="img" aria-label="Synthetic landscape responds to camera exposure and focus"><rect width="420" height="230" fill="#82c6e6"/><circle cx="340" cy="45" r="22" fill="#fff3ac"/><path d="M0 145L100 25l75 95 70-100 115 130 60-50v140H0Z" fill="#5c7892"/><path d="M70 60l30-35 30 38-28-12Z M210 63l35-43 35 39-29-14Z" fill="#e8edf4"/><path d="M0 155Q100 135 210 155T420 155V230H0Z" fill="#397c8e"/><path d="M0 145l30-65 30 65-20-10v40H20v-40Z" fill="#284f3b"/><text x="12" y="217" fill="white" fontSize="11">Synthetic scene • exposure × {result.metrics[0]?.value}</text></svg></div>;
 if(lab.engine==="phone")return <div className="dl-phone-display" style={{filter:`brightness(${(values.brightness??70)/100+.25})`}}><div>9:41 <span>{values.wifi?"Wi-Fi":""} {values.network?"5G":""}</span></div><strong>{result.metrics.find(m=>m.label==="Active app")?.value}</strong><div className="dl-app-icons">{["◉","⌖","▦","♫","✉","☁"].map(icon=><span key={icon}>{icon}</span>)}</div><p>{result.metrics.find(m=>m.label==="Network")?.value} · {values.saver?"Battery saver":"Standard power"}</p><small>Virtual device dashboard</small></div>;
 if(lab.engine==="ultrasound"||lab.engine==="doppler")return <svg className="dl-live-visual" viewBox="0 0 430 230" role="img" aria-label="Synthetic acoustic imaging sector"><defs><clipPath id={`sector-${lab.number}`}><path d="M210 20L100 200Q210 250 320 200Z"/></clipPath></defs><g clipPath={`url(#sector-${lab.number})`}><rect width="430" height="230" fill="#24303a"/>{Array.from({length:30},(_,i)=><path key={i} d={`M110 ${40+i*6}q100 ${12*Math.sin(i)} 210 0`} stroke="#a0a7aa" strokeWidth="3" opacity={(values.gain??60)/200}/>)}<ellipse cx="210" cy={60+(values.depth??12)*5} rx="42" ry="23" fill={lab.engine==="doppler"||mode==="Color flow"||mode==="Doppler"?"#ca5a73":"#c1c8ca"}/></g><text x="15" y="220">Synthetic {lab.engine==="doppler"?"flow overlay":"echo sector"} • {values.frequency??5} MHz</text></svg>;
 if(lab.engine==="microscope"||lab.engine==="endoscope")return <figure className="dl-reference-scene"><div style={{overflow:"hidden",borderRadius:lab.engine==="microscope"?"50%":"12px",maxWidth:260,margin:"auto",aspectRatio:"1"}}><img src={`/device-labs/${lab.number}-scene.webp?v=3`} alt={lab.engine==="microscope"?"Reference microscopic cell specimen":"Reference endoscopic lumen view"} style={{width:"100%",height:"100%",objectFit:"cover",transform:`scale(${lab.engine==="microscope"?Math.max(1,(values.magnification??400)/400):values.zoom??1})`,filter:`brightness(${result.imageLevel}) contrast(${mode==="Phase contrast"||mode==="Enhanced contrast"?1.5:1}) blur(${(1-result.quality)*3}px)`}}/></div><figcaption>Reference scene · simulated optical adjustments</figcaption></figure>;
 if(lab.engine==="nfc")return <div className="dl-transaction"><span>{result.status.includes("approved")?"✓":result.status.includes("failed")?"×":"◉"}</span><strong>{result.status.includes("approved")?"Payment Approved":result.status.includes("failed")?"Exchange Failed":"Ready to Tap"}</strong><b>{values.amount?.toFixed(2)} test units</b><small>{values.token?"Tokenized test credential":"Test identifier"} · simulated terminal</small></div>;
 if(lab.engine==="remote")return <div className="dl-virtual-tv"><strong>Virtual TV</strong><span>{result.status.includes("transmitted")?`${result.metrics.find(m=>m.label==="Receiver action")?.value}`:"Choose a command"}</span><small>{result.status.includes("transmitted")?"Packet accepted by virtual receiver":"Waiting for infrared packet"}</small></div>;
 if(lab.engine==="robot") {const c=result.coordinates;return <svg className="dl-live-visual" viewBox="0 0 430 230" role="img" aria-label="Robot joint geometry"><path d="M15 195H415M70 20V205" stroke="#43647d"/><g stroke="#46b9fa" strokeWidth="14" strokeLinecap="round"><path d={`M70 195L${70+(c[0]??0)*.8} ${195-(c[1]??0)*.8}L${70+(c[2]??0)*.8} ${195-(c[3]??0)*.8}L${70+(c[4]??0)*.8} ${195-(c[5]??0)*.8}`}/></g><g transform={`translate(${70+(c[4]??0)*.8} ${195-(c[5]??0)*.8}) rotate(${(values.joint4??0)+(values.joint5??0)+(values.joint6??0)})`}><path d="M0 -9h17v18H0" fill="none" stroke="#f0ce56" strokeWidth="3"/></g><circle cx="70" cy="195" r="16" fill="#d3e9f4"/><text x="165" y="220">Tool pose from joint angles</text></svg>;}
 if(lab.engine==="radar"||lab.engine==="sonar")return <svg className="dl-live-visual" viewBox="0 0 430 230" role="img" aria-label="Range and bearing display"><g stroke="#2b775e" fill="#071d20">{[95,65,35].map(r=><circle key={r} cx="210" cy="115" r={r}/>)}<path d="M115 115H305M210 20V210"/></g><path d={`M210 115l${95*Math.cos(time*(values.rotation??12)/60*6.28)} ${95*Math.sin(time*(values.rotation??12)/60*6.28)}`} stroke="#53e7a8" strokeWidth="3"/>{Array.from({length:lab.engine==="radar"?values.targets??6:1},(_,i)=><circle key={i} cx={210+Math.cos(i*2.4)*((i*19+40)%90)} cy={115+Math.sin(i*2.4)*((i*19+40)%90)} r="4" fill="#80ffa9"/>)}<text x="12" y="222">{values.range??values.distance} {lab.engine==="radar"?"km":"m"} range</text></svg>;
 if(lab.engine==="pet"||lab.engine==="spect")return <div className="dl-phantom"><NuclearSlice level={result.imageLevel} quality={result.quality} slice={values.slice??50} plane={mode}/></div>;
 if(["mri","ct","xray","detector","mammography"].includes(lab.engine))return <AnatomyPhantom lab={lab} result={result} values={values} mode={mode}/>;
 if(lab.engine==="autopilot")return <svg className="dl-live-visual" viewBox="0 0 430 230" role="img" aria-label="Flight attitude and selected heading"><defs><clipPath id="attitude"><circle cx="210" cy="115" r="93"/></clipPath></defs><g clipPath="url(#attitude)"><rect x="110" y="15" width="200" height="100" fill="#237fac"/><rect x="110" y="115" width="200" height="100" fill="#8f6341"/><path d="M120 115H300" stroke="white" strokeWidth="3"/>{[-30,-15,15,30].map(y=><path key={y} d={`M180 ${115+y}h60`} stroke="white"/>)}</g><path d="M150 115h45l15 9 15-9h45" stroke="#f5ce4b" strokeWidth="4" fill="none"/><text x="22" y="221">Heading {values.heading}° • Selected altitude {values.target} ft</text></svg>;
 return <div className="dl-large-reading"><strong>{result.metrics[0]?.value}</strong><span>{result.metrics[0]?.unit}</span><small>{result.metrics[0]?.label}</small><div className="dl-quality"><i style={{width:`${result.quality*100}%`}}/></div></div>;
}
