import type { LabGuideContent } from "./types";

export const LABS_05: LabGuideContent[] = [
  {
    id: "reorder-buffer",
    labNumber: 5,
    title: "Out-of-Order Execution & In-Order Commit",
    aim: "Separate completion order from retirement order, and see a reorder buffer discard younger work when an exception is injected.",
    purpose: "Precise exceptions require architectural state to change in program order even when execution finishes out of order.",
    prerequisites: ["Register renaming", "Speculative versus committed state", "Pipeline stages after issue"],
    learningObjectives: ["Read ROB head and tail", "Explain why a finished younger instruction cannot commit first", "Describe what Inject Exception on ADD removes"],
    theory: [
      "Dispatch places an instruction in the ROB. Issue and execution may complete out of order.",
      "Commit retires the oldest ROB entry only. That write is the architectural update.",
      "If the ADD is marked with an exception, that instruction and every younger entry are flushed. Older entries may still commit.",
    ],
    keyTerms: [
      { term: "ROB", meaning: "Reorder buffer. Holds results until they can retire in order." },
      { term: "Commit", meaning: "Retirement of the oldest completed entry into architectural state." },
      { term: "Flush", meaning: "Removal of the faulting instruction and younger speculative work." },
    ],
    assumptions: ["One ROB for the displayed sequence.", "Inject a precise exception faults the instruction chosen in Faulting instruction. It is not a trap from the host CPU.", "Show Pipeline Animation only changes the drawing."],
    setup: ["The page opens on its built-in out-of-order example.", "Inject a precise exception is off until you enable it."],
    procedure: [
      "Reset and Step with the exception toggle off. Note an instruction that finishes before an older one.",
      "Watch the ROB: the younger result stays speculative until the head commits.",
      "Record completion order and commit order separately.",
      "Turn Inject Exception on ADD on, Reset, and Step until the flush text appears.",
      "Read Flushed instructions and confirm younger work does not update architectural state.",
      "Turn Show Pipeline Animation on or off and confirm the cycle count does not change.",
    ],
    controls: ["Instruction stream", "Reorder buffer entries, issue width, commit width, ALU count, multiply count, memory unit count", "Inject a precise exception and Faulting instruction", "Show Pipeline Animation", "Play, Pause, Previous, Step, Reset, Simulation Speed"],
    observations: ["Which ROB entry is oldest", "Which instruction has completed but not committed", "Flush count after the injected exception"],
    formulas: [{ name: "Commit rule", expression: "Retire only the ROB head", note: "A completed younger entry waits." }],
    expectedBehavior: ["Execution order can differ from program order.", "Commit order matches program order.", "The injected fault drops the ADD and younger instructions."],
    resultInterpretation: ["If a finished instruction remains in the ROB while an older entry is incomplete, retirement is still in order.", "If flushed instructions do not appear as committed results, the exception stayed precise."],
    misconceptions: ["Out-of-order completion is not out-of-order commit.", "The ROB is not a cache.", "Flushing younger work does not roll back instructions that already committed."],
    variations: ["Type a program where SUB has no dependence on MUL, then Step until SUB writes back while MUL is still in the ROB.", "Turn the exception on, pick the faulting instruction, and confirm younger completed work is flushed.", "Raise commit width and watch more than one ready head retire in one cycle."],
    learningOutcomes: ["Point to the ROB head", "Explain precise exceptions using the flush", "Distinguish completed from committed"],
    viva: [
      { question: "Why is the ROB required for precise exceptions?", answer: "It delays architectural updates until the instruction is the oldest and fault-free." },
      { question: "Can a younger add commit before an older load?", answer: "No. It may finish earlier, but commit waits." },
      { question: "What is flushed?", answer: "The instruction selected in Faulting instruction, and everything younger, after Inject a precise exception is on." },
      { question: "What state is speculative?", answer: "ROB results that have not committed." },
      { question: "Does Show Pipeline Animation change the model?", answer: "No. It only changes the drawing." },
    ],
    selfCheck: [
      { prompt: "Commit order is:", choices: ["The order instructions finish", "Program order", "Cache-line order"], answer: 1, why: "Only the ROB head retires." },
      { prompt: "A younger finished instruction is:", choices: ["Already architectural", "Speculative until the head commits", "Flushed immediately"], answer: 1, why: "Completion is not commit." },
      { prompt: "Inject a precise exception on the chosen instruction removes:", choices: ["Only older instructions", "That instruction and younger instructions", "The whole cache"], answer: 1, why: "Older committed work stays. Use the Faulting instruction menu to choose which instruction faults." },
    ],
    summary: "The machine may finish work early. Architectural state moves only at the ROB head, which is what makes an exception precise.",
  },
  {
    id: "branch-predictor",
    labNumber: 6,
    title: "1-Bit & 2-Bit Branch Predictor",
    aim: "Compare a 1-bit predictor with a 2-bit saturating counter on the same branch trace.",
    purpose: "A 1-bit predictor copies the last outcome, so a loop exit flips the next prediction. A 2-bit counter needs two disagreeing outcomes before it changes its guess.",
    prerequisites: ["Taken and not-taken outcomes", "A loop’s last iteration", "What a misprediction is"],
    learningObjectives: ["Step both finite-state machines", "Compute accuracy from the history table", "Explain the loop-exit difference"],
    theory: [
      "The 1-bit state is Taken or Not taken. After the branch resolves, the state becomes the actual outcome.",
      "The 2-bit states are strongly taken, weakly taken, weakly not taken, and strongly not taken. A hit moves toward strong. A miss moves one step toward the opposite strong state.",
      "On T T T T N, the 1-bit machine misses the exit and the next entry. The 2-bit machine, started strongly taken, misses the exit and stays taken for the next entry.",
    ],
    keyTerms: [
      { term: "Hysteresis", meaning: "The 2-bit counter does not reverse after a single surprise." },
      { term: "Accuracy", meaning: "Correct predictions divided by predictions made, times 100." },
    ],
    assumptions: ["Both predictors see the same edited trace.", "Initial state is whatever the two selectors show.", "The lab does not claim the 2-bit predictor wins on every pattern."],
    setup: ["Branch Trace Input accepts a pattern and Load example presets: Simple Loop, Alternating, Mostly Taken, Mostly Not Taken.", "1-bit initial and 2-bit initial set the starting state."],
    procedure: [
      "Load Simple Loop. Set the 1-bit predictor to Taken and the 2-bit predictor to Strongly taken.",
      "Reset and Step through every branch. Watch both state diagrams.",
      "In Prediction History, mark the exit and the following entry.",
      "Read Accuracy Comparison. Do not assume the 2-bit number matches a screenshot; use the table.",
      "Load Alternating and repeat. Compare which machine is worse.",
      "Change the 2-bit initial state to Weakly not taken and repeat the loop.",
    ],
    controls: ["Branch trace editor and Load example", "1-bit initial state", "2-bit initial state", "Highlight Mispredictions", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["State before and after each branch", "Whether the prediction matched the outcome", "Accuracy of each machine", "The two misses of the 1-bit loop predictor versus the single exit miss of a strongly taken 2-bit counter"],
    formulas: [{ name: "Accuracy", expression: "correct / total × 100", note: "Use the counts in Accuracy Comparison for the trace you actually ran." }],
    expectedBehavior: ["Simple Loop favors the 2-bit counter when it starts strongly or weakly taken.", "Alternating punishes both, often the 2-bit machine as well.", "Changing the initial state changes the first predictions."],
    resultInterpretation: ["If the 2-bit predictor’s only loop miss is the exit, hysteresis kept the next iteration taken.", "If Alternating shows a low accuracy for both, correlation or a different history is needed. This lab has neither."],
    misconceptions: ["The 2-bit predictor is not more accurate on every trace.", "Accuracy is not the same as the initial state.", "One branch PC in this lab is a single counter, not a whole pattern table."],
    variations: ["Set the 2-bit counter to Strongly not taken before the Mostly Taken trace.", "Edit one outcome in the trace and Step only that branch."],
    learningOutcomes: ["Draw both state machines", "Predict the loop-boundary misses", "Compute accuracy from the history"],
    viva: [
      { question: "Why does a 1-bit predictor miss twice on a loop?", answer: "The exit writes Not taken, so the next entry is predicted not taken and misses." },
      { question: "What does saturating mean?", answer: "Strongly taken stays strongly taken on another taken outcome. It does not wrap." },
      { question: "When can the 1-bit predictor win?", answer: "On a pattern that flips every branch, a counter with memory of two outcomes can lag." },
      { question: "What is the prediction before the branch resolves?", answer: "The current state: taken if the 1-bit state is Taken, or if the 2-bit state is weakly or strongly taken." },
      { question: "Does Highlight Mispredictions change the counts?", answer: "No. It only marks rows." },
    ],
    selfCheck: [
      { prompt: "A strongly taken 2-bit counter that sees Not taken becomes:", choices: ["Strongly not taken", "Weakly taken", "Taken in the 1-bit sense only"], answer: 1, why: "It steps once, from strong to weak." },
      { prompt: "Accuracy uses:", choices: ["Only mispredictions in the denominator", "Correct predictions over all predictions", "BTB hits"], answer: 1, why: "Both correct and incorrect predictions count in the total." },
      { prompt: "The 2-bit predictor always beats the 1-bit predictor.", choices: ["True", "False"], answer: 1, why: "Alternating traces are a counterexample." },
    ],
    summary: "Hysteresis helps loops and hurts rapid alternation. Read the accuracy table for the trace you ran.",
  },
  {
    id: "correlating-predictor",
    labNumber: 7,
    title: "Correlating Branch Predictor",
    aim: "See how global history, local history, and a bimodal counter index different pattern-table entries.",
    purpose: "Some branches are predictable only when a recent outcome is known. GShare mixes the PC with global history so that context selects the counter.",
    prerequisites: ["2-bit saturating counters", "Taken encoded as 1 and not-taken as 0", "Why a single bimodal counter aliases different contexts"],
    learningObjectives: ["Read the global history register", "Compute a GShare index as PC XOR history", "Compare bimodal, local, and GShare accuracy"],
    theory: [
      "A bimodal counter is indexed by PC only. It cannot tell two contexts of the same branch apart.",
      "Local history is this branch’s own recent outcomes. Global history is the recent outcomes of all branches.",
      "GShare indexes the pattern history table with PC XOR the global history. The low bit of the history is the most recent outcome. Update on Each Branch writes the resolved outcome back into the selected counter.",
    ],
    keyTerms: [
      { term: "GHR", meaning: "Global history register." },
      { term: "PHT", meaning: "Pattern history table of 2-bit counters." },
      { term: "Aliasing", meaning: "Two different contexts select the same counter and corrupt it." },
    ],
    assumptions: ["History length and table size are the ones drawn on the page.", "Toggling a predictor off hides it; it does not delete the other predictors’ state until Reset.", "The Aliasing example is a lab trace, not a measurement from a chip."],
    setup: ["Load example: Correlated pair, Alternating branches, Mostly taken, Loop-like, Aliasing.", "Initial counter sets every counter’s start state."],
    procedure: [
      "Load Correlated pair. Set the initial counter to Strongly not taken. Reset.",
      "Step and write the GHR after each branch. The newest bit is the low bit.",
      "With Global Predictor (GShare) on, read the PHT index and the counter used.",
      "Turn on Local Predictor and Bimodal Predictor and compare their predictions for the same branch.",
      "Load Aliasing. Find two contexts that land on one counter.",
      "Turn Update on Each Branch off, Reset, and see that counters stop learning.",
    ],
    controls: ["Load example and the editable PC, instruction, and T/N outcome", "Initial counter", "Global Predictor (GShare), Local Predictor, Bimodal Predictor", "Update on Each Branch", "Highlight Mispredictions", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["GHR bits", "Local-history bits for one PC", "PHT index and counter value", "Which component was correct", "Accuracy Analyzer percentages"],
    formulas: [{ name: "GShare index", expression: "index = PC XOR global history", note: "The width is the history length implemented in the lab, not a full architectural PC." }],
    expectedBehavior: ["Correlated pair improves once history distinguishes the second branch.", "Bimodal accuracy stays flat when the same PC alternates by context.", "Aliasing makes one counter swing between two unrelated patterns."],
    resultInterpretation: ["If GShare accuracy exceeds bimodal accuracy on the correlated trace, the history bit selected a better counter.", "If aliasing drops accuracy, the table is too small for the contexts, not because correlation is impossible."],
    misconceptions: ["GShare does not store the target address. That is a BTB.", "XOR indexing is not the same as concatenating history in every design; this lab uses XOR.", "A hidden predictor is not necessarily reset."],
    variations: ["Change the initial counter and repeat Correlated pair.", "Edit one outcome from T to N and watch the GHR bit flip."],
    learningOutcomes: ["Update a GHR by hand", "Explain a GShare index", "Define aliasing from the Aliasing trace"],
    viva: [
      { question: "What does the bimodal table ignore?", answer: "Other branches’ outcomes. It sees only the PC." },
      { question: "Which bit is the most recent outcome?", answer: "The low bit of the history." },
      { question: "Why XOR the PC with history?", answer: "So the same PC uses different counters in different global contexts." },
      { question: "What is aliasing?", answer: "Distinct contexts updating one counter." },
      { question: "What happens if Update on Each Branch is off?", answer: "The prediction is made, but the counter and useful training do not follow the outcome." },
    ],
    selfCheck: [
      { prompt: "GShare’s index depends on:", choices: ["PC only", "PC and global history", "The BTB target"], answer: 1, why: "The lab indexes with PC XOR history." },
      { prompt: "Local history belongs to:", choices: ["One branch PC", "Every branch mixed together", "The cache"], answer: 0, why: "Global history is the mixed one." },
      { prompt: "Aliasing means the predictor is correlated.", choices: ["True", "False"], answer: 1, why: "Aliasing is a collision, not successful correlation." },
    ],
    summary: "Correlation works when history selects the right counter. Aliasing is the cost of a small table.",
  },
  {
    id: "branch-target-buffer",
    labNumber: 8,
    title: "Branch Target Buffer Explorer",
    aim: "Look up branch targets in a BTB and separate a hit from a tag miss, a conflict, and a replacement.",
    purpose: "Direction prediction says taken or not. The BTB says where a taken branch goes, early enough for the next fetch.",
    prerequisites: ["Direct-mapped versus set-associative lookup", "Tags and indexes", "LRU and FIFO"],
    learningObjectives: ["Split a PC into index and tag", "Explain a BTB hit", "Explain a conflict miss when two PCs share a set"],
    theory: [
      "A BTB entry stores a tag and a target. A hit requires the index to select the set and the tag to match.",
      "A miss means fetch does not get a predicted target from the BTB. The entry can be filled after the branch resolves.",
      "Direct-mapped organization has one way, so LRU and FIFO are disabled. Two-way organization uses the selected replacement policy when both ways are valid.",
    ],
    keyTerms: [
      { term: "Index", meaning: "Bits that select the set." },
      { term: "Tag", meaning: "The remaining PC bits that must match." },
      { term: "Target", meaning: "The predicted next PC, not the taken/not-taken bit." },
    ],
    assumptions: ["Enable BTB off means lookups do not hit.", "The traces are Hot loop, Two branch PCs, Capacity pressure, Conflict misses, Target change, and Associative replacement.", "Replacement policy applies only when ways is 2."],
    setup: ["Organization is Direct-mapped or 2-way.", "Policy is Least recently used or FIFO, disabled for direct-mapped."],
    procedure: [
      "Set Direct-mapped and Enable BTB. Load Hot loop. Reset and Step. Record hits after the first fill.",
      "Load Conflict misses. Identify the two PCs that share a set and the eviction.",
      "Switch to 2-way and Least recently used. Load Associative replacement and Step until a way is replaced.",
      "Change the policy to FIFO, Reset, and compare which way leaves.",
      "Load Target change. Confirm a tag hit can still hold a stale target until the entry is updated.",
      "Turn Enable BTB off and confirm the hit rate collapses.",
    ],
    controls: ["Organization", "Replacement policy", "Trace selector", "Enable BTB", "Show Lookup Details", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Selected set", "Tag comparison", "Predicted target", "Hit, miss, or eviction", "Hit rate"],
    formulas: [{ name: "Hit rate", expression: "BTB hits / lookups × 100", note: "The first reference to an entry is a miss until it is filled." }],
    expectedBehavior: ["A repeated PC hits after it is installed.", "Conflict misses replace the only way when the organization is direct-mapped.", "Two-way replacement follows LRU or FIFO as selected."],
    resultInterpretation: ["A high hit rate on Hot loop means the same PC reused one entry.", "A conflict miss with a correct direction predictor would still fetch the wrong path if the target is missing. This page is about the target."],
    misconceptions: ["The BTB does not, by itself, predict taken versus not taken.", "A tag match with an old target is not a correct redirect until the target field is updated.", "FIFO and LRU do nothing in a direct-mapped buffer."],
    variations: ["Run Conflict misses as direct-mapped and then as 2-way.", "Turn Show Lookup Details off and infer hit or miss from the hit-rate counter alone."],
    learningOutcomes: ["Perform a BTB lookup", "Name the replaced way under LRU and FIFO", "Separate target prediction from direction prediction"],
    viva: [
      { question: "What is stored in a BTB entry?", answer: "A tag and a target PC, plus whatever valid and replacement state the organization needs." },
      { question: "Why can two branches miss even if both are taken?", answer: "They can index the same set and thrash one way." },
      { question: "When is the replacement selector disabled?", answer: "In the direct-mapped organization." },
      { question: "What does a hit supply?", answer: "The predicted target, so fetch can continue there." },
      { question: "Is hit rate the same as direction accuracy?", answer: "No. This lab counts target lookups." },
    ],
    selfCheck: [
      { prompt: "A BTB hit compares the:", choices: ["Tag", "Taken/not-taken counter only", "Cache data"], answer: 0, why: "The index selects the set. The tag must match." },
      { prompt: "FIFO is available when organization is:", choices: ["Direct-mapped", "2-way", "Always"], answer: 1, why: "The policy control is disabled for one way." },
      { prompt: "Target change can hit and still be wrong until:", choices: ["The target field is updated", "The GHR shifts", "The ROB commits"], answer: 0, why: "The entry can hold a stale target." },
    ],
    summary: "The BTB is an address predictor. Conflicts and stale targets are visible in the lookup details, separate from direction accuracy.",
  },
];
