import type { LabGuideContent } from "./types";

export const LABS_25: LabGuideContent[] = [
  {
    id: "dram-controller",
    labNumber: 25,
    title: "DRAM Bank & Memory Controller Simulator",
    aim: "Decode addresses into channel, rank, bank, row, and column, then compare FCFS with FR-FCFS on row hits and row conflicts.",
    purpose: "DRAM latency depends on whether the row is already open. The controller chooses which request uses the open row.",
    prerequisites: ["Bank, row, and column", "Activate, read, write, and precharge", "Queueing"],
    learningObjectives: ["Classify a hit, miss, and conflict", "Read the command sequence", "Explain why FR-FCFS can starve"],
    theory: [
      "A closed bank needs ACTIVATE then READ or WRITE. A row hit needs only the column command. A row conflict precharges, activates the new row, then reads or writes.",
      "The lab’s timing defaults are 2 cycles for tRCD, tCL, tRP, and tRAS. Do not copy a datasheet’s 12/12/12/40 into this page.",
      "FCFS serves arrival order. FR-FCFS prefers a ready row hit. Presets: All row hits, Repeated row conflicts, Same bank different rows, Different banks, Mixed locality, FR-FCFS advantage, Potential starvation.",
    ],
    keyTerms: [
      { term: "Row hit", meaning: "The requested row is already open in that bank." },
      { term: "Row conflict", meaning: "Another row is open, so PRE and ACT are required." },
      { term: "BLP", meaning: "Bank-level parallelism: different banks can overlap." },
    ],
    assumptions: ["Ranks and channels are decoded and displayed. They do not add a second controller in this model.", "Show Timing Details, Show Row Buffer, and Highlight Row Hits are visual."],
    setup: ["Set banks, rows, and columns before you interpret an address. Then pick a policy and a preset."],
    procedure: [
      "Load All row hits under FCFS. Step and confirm each access after the first is a column command.",
      "Load Repeated row conflicts. Count PRE and ACT.",
      "Load Different banks and see two banks busy.",
      "Load FR-FCFS advantage. Record hits and average latency for FCFS, switch to FR-FCFS, Reset, and compare.",
      "Load Potential starvation and see a conflicting request wait behind hits.",
      "Change the bank count and re-decode one address.",
    ],
    controls: ["Channels, ranks, banks, rows, columns", "Policy FCFS or FR-FCFS", "Presets", "Show Timing Details", "Show Row Buffer", "Highlight Row Hits", "Auto Advance Requests", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Open row per bank", "Command sequence", "Hit or conflict label", "Latency", "Which request the policy picks"],
    formulas: [{ name: "Hit versus conflict", expression: "Hit latency uses tCL. Conflict adds tRP + tRCD + tCL.", note: "With each parameter at 2, a hit is shorter than a conflict by the precharge and activate." }],
    expectedBehavior: ["The advantage preset gives FR-FCFS more row hits and a lower average latency than FCFS.", "Conflicts issue PRE then ACT.", "Different banks overlap."],
    resultInterpretation: ["A lower average with the same requests means the policy found more hits, not that DRAM became faster.", "A request that never issues while hits keep arriving is the starvation case."],
    misconceptions: ["A row miss and a row conflict are not the same phrase in every textbook. Here a conflict means another row is open.", "FR-FCFS is not fair.", "The timing numbers are the lab’s defaults."],
    variations: ["Rerun Mixed locality under both policies.", "Reduce banks to 2 and watch conflicts rise on the different-bank preset."],
    learningOutcomes: ["Decode an address", "Write the command sequence for a conflict", "Compare the two policies’ hit counts"],
    viva: [
      { question: "What commands does a row hit need?", answer: "The column command, READ or WRITE. The row is already active." },
      { question: "What does a conflict add?", answer: "Precharge and activate before the column command." },
      { question: "What does FR-FCFS prefer?", answer: "A request that hits the open row, ahead of an older conflicting request." },
      { question: "Why can that starve a request?", answer: "Newer hits keep winning while the conflicting request waits." },
      { question: "What is bank-level parallelism?", answer: "Independent banks proceed without sharing one row buffer." },
    ],
    selfCheck: [
      { prompt: "A hit’s extra commands are:", choices: ["None beyond the column access", "PRE and ACT always", "A fence"], answer: 0, why: "The row is open." },
      { prompt: "FR-FCFS can:", choices: ["Prefer hits and delay a conflict", "Ignore the row buffer", "Remove tCL"], answer: 0, why: "That is the starvation preset." },
      { prompt: "This page’s default timing is a DDR datasheet.", choices: ["True", "False"], answer: 1, why: "tRCD, tCL, tRP, and tRAS are 2 in the lab." },
    ],
    summary: "Open the right row, or pay precharge and activate. FR-FCFS harvests hits and can leave a conflicting request waiting.",
  },
  {
    id: "memory-consistency",
    labNumber: 26,
    title: "Memory Consistency Model Explorer",
    aim: "Enumerate the outcomes a litmus test is allowed to produce under sequential consistency, total store order, weak ordering, and acquire/release.",
    purpose: "Coherence is about one address. Consistency is about the order of different addresses as seen by other cores.",
    prerequisites: ["A store buffer", "Fences", "The store-buffering and message-passing litmus tests"],
    learningObjectives: ["State which outcomes SC forbids", "Explain why TSO allows r0 = 0, r1 = 0", "Place a fence so a flag is not observed early"],
    theory: [
      "Sequential consistency executes one global order consistent with each thread’s program order. It forbids the store-buffering outcome where both loads read 0.",
      "Total store order lets a core’s own stores sit in a FIFO buffer. A load can pass its own stores to other addresses, so both loads can read 0. A fence waits until that core’s buffer is empty.",
      "Weak ordering can also reorder stores, so message passing can observe the flag without the data. Acquire/release on the synchronized variant forbids flag = 1 with data = 0 and allows flag = 1 with data = 42. The table is every legal outcome, not a random sample.",
    ],
    keyTerms: [
      { term: "Litmus test", meaning: "A small program used to ask which outcomes a model allows." },
      { term: "TSO", meaning: "Total store order. Stores are FIFO. A load may bypass earlier stores to other addresses." },
      { term: "Fence", meaning: "An ordering instruction. Here it executes only when that core’s store buffer is empty." },
    ],
    assumptions: ["Models are Sequential consistency, Total store order, Weak ordering, and Acquire/release.", "Litmus tests are Store buffering, Message passing, Message passing with release/acquire, and Load buffering.", "IRIW is not in this lab.", "Show Store Buffers, Show Memory Values, and Animate Execution do not change the model."],
    setup: ["Pick one model and one litmus test. Add a fence only on the core and instruction the toggle names."],
    procedure: [
      "Select Store buffering and Sequential consistency. Step. Both-zero should be absent from the allowed outcomes.",
      "Switch to Total store order and Reset. Both-zero should appear. Watch the store buffers.",
      "Enable Fence after core 0’s store and Fence after core 1’s store. Both-zero should disappear again.",
      "Select Message passing under TSO. A plain flag store stays ordered with the earlier data store.",
      "Switch to Weak ordering. The flag can be seen while the data is still 0.",
      "Select Message passing with release/acquire. Confirm flag = 1 implies data = 42.",
    ],
    controls: ["Consistency model", "Litmus test", "Fence after core 0 store", "Fence after core 0 load", "Fence after core 1 store", "Fence after core 1 load", "Show Store Buffers", "Show Memory Values", "Animate Execution", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Store-buffer contents", "Each load’s result", "Allowed outcome rows", "Whether a fence is still waiting"],
    formulas: [{ name: "Allowed set", expression: "An outcome is shown only if some legal execution produces it", note: "Absence means the model forbids it, not that a random run missed it." }],
    expectedBehavior: ["SC forbids store-buffering both-zero.", "TSO allows it until fences drain the buffers.", "Weak message passing can show the flag early.", "Release/acquire forbids flag without data."],
    resultInterpretation: ["If an outcome appears, the model permits it. If it is missing, the model forbids it.", "A fence that never issues is waiting for that core’s buffer."],
    misconceptions: ["Coherence and consistency are different questions.", "TSO does not reorder a core’s own stores.", "The table is not 10,000 random runs."],
    variations: ["Replace the litmus text with a new two-thread test and compare the allowed counts under SC and TSO.", "Turn on Manual interleaving and pick the next legal core action yourself.", "Insert fence on a thread and confirm the forbidden outcome disappears."],
    learningOutcomes: ["Classify an outcome as allowed or forbidden", "Explain a store buffer", "Place the fences that restore SC for this test"],
    viva: [
      { question: "Why can TSO produce both loads reading 0?", answer: "Each load bypasses its own core’s buffered store to the other address." },
      { question: "Why does SC forbid that?", answer: "No single program-order-respecting total order ends with both loads reading the initial value." },
      { question: "When does a fence execute here?", answer: "When that core’s store buffer is empty." },
      { question: "Can TSO show the message-passing flag without the data?", answer: "Not in this model. A core’s stores stay in order." },
      { question: "What does acquire/release forbid?", answer: "Observing the flag while the payload is still the old value." },
    ],
    selfCheck: [
      { prompt: "Store buffering both-zero is allowed by this lab’s SC.", choices: ["True", "False"], answer: 1, why: "SC forbids it." },
      { prompt: "The outcome table is:", choices: ["Every legal outcome", "A sample of 10,000 runs", "Only the first cycle"], answer: 0, why: "It enumerates the model." },
      { prompt: "A fence waits for:", choices: ["That core’s store buffer to drain", "Every cache to be Invalid", "The BTB"], answer: 0, why: "It cannot retire while this core’s stores are buffered." },
    ],
    summary: "Read the allowed set. SC is the strictest. TSO adds the store buffer. Weak ordering needs a release and an acquire before the flag means the data is visible.",
  },
  {
    id: "atomic-operations",
    labNumber: 27,
    title: "Atomic Operations & Synchronization",
    aim: "Compare a lost update with fetch-and-add, and compare a test-and-set lock with a ticket lock under the same contention.",
    purpose: "A read-modify-write that is not atomic loses increments. A lock that is correct can still be unfair.",
    prerequisites: ["Critical section", "Atomic read-modify-write", "Fairness"],
    learningObjectives: ["Explain a lost update", "Read a CAS failure", "Compare spin time and fairness"],
    theory: [
      "A non-atomic increment reads the counter, then writes it back. If every thread reads before any write, the counter becomes 1.",
      "Fetch-and-add returns the old value and adds in one step, so N threads each adding 1 leave the counter at N.",
      "Test-and-set spins on a flag. With think time 0 the lowest id can win every round. A ticket lock hands out increasing tickets. Fairness is the standard deviation of per-thread wait. Compare-and-swap writes only on a match. A failed store-conditional does not clear another thread’s reservation.",
    ],
    keyTerms: [
      { term: "TAS", meaning: "Test-and-set. Atomically reads a flag and sets it." },
      { term: "CAS", meaning: "Compare-and-swap. Writes only if the observed value is still expected." },
      { term: "LL/SC", meaning: "Load-linked arms a reservation. Store-conditional succeeds only if it is intact." },
      { term: "Ticket lock", meaning: "Threads take a number and enter in that order." },
    ],
    assumptions: ["Threads are 2, 4, or 8.", "Critical-section cycles, non-critical cycles, and rounds are the timing knobs.", "The lab does not model cache traffic for spinning."],
    setup: ["Examples: TAS lock, 2 threads; TAS lock, high contention; CAS counter; Fetch-and-add counter; LL/SC retry; Ticket lock fairness; Non-atomic lost update; Atomic versus non-atomic counter."],
    procedure: [
      "Load Non-atomic lost update. Step until every thread has written. The counter should be 1.",
      "Load Fetch-and-add counter with the same thread count. The counter should equal the number of successful adds.",
      "Load TAS lock, high contention. Non-critical cycles are already 0. Record which thread wins.",
      "Load Ticket lock fairness and compare the fairness number with TAS.",
      "Load CAS counter and find a failed compare that does not write.",
      "Load LL/SC retry and confirm a failed store-conditional leaves the other reservation alone.",
    ],
    controls: ["Primitive", "Load example", "Thread count", "Critical section cycles", "Non-critical cycles", "Rounds", "Show Lock State", "Show Thread Activity", "Highlight Critical Section", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Counter value", "Who holds the lock", "Retries", "Per-thread wait", "Fairness", "Whether a CAS or SC wrote"],
    formulas: [{ name: "Fairness", expression: "Standard deviation of per-thread wait", note: "A smaller number is fairer. It is not a throughput metric." }],
    expectedBehavior: ["The lost update ends at 1.", "Fetch-and-add ends at the thread count for one round of increments.", "Ticket wait is more even than TAS when think time is 0.", "At most one thread is in the critical section."],
    resultInterpretation: ["A correct final counter means the updates were atomic.", "A correct lock with one thread always winning is mutual exclusion without fairness."],
    misconceptions: ["Mutual exclusion does not imply fairness.", "A failed CAS must not write.", "This page does not count coherence traffic for the spin."],
    variations: ["Raise non-critical cycles on TAS and see whether the same thread still dominates.", "Set threads to 8 on the lost-update preset."],
    learningOutcomes: ["Predict the lost-update result", "Explain a ticket", "Read the fairness number"],
    viva: [
      { question: "Why does the non-atomic counter become 1?", answer: "Every thread reads 0, then every thread writes 1." },
      { question: "What does fetch-and-add guarantee?", answer: "The add happens as one step, so each increment is counted." },
      { question: "Why is TAS unfair at think time 0?", answer: "The lowest id can reacquire the flag immediately." },
      { question: "What does a ticket lock order?", answer: "Entry follows the ticket numbers." },
      { question: "What must a failed store-conditional not do?", answer: "It must not clear another thread’s reservation." },
    ],
    selfCheck: [
      { prompt: "Four non-atomic increments that all read 0 finish at:", choices: ["4", "1", "0"], answer: 1, why: "Each writes 1." },
      { prompt: "A smaller fairness number means:", choices: ["More even waits", "More retries always", "A broken lock"], answer: 0, why: "It is the standard deviation of wait." },
      { prompt: "CAS writes when the compare fails.", choices: ["True", "False"], answer: 1, why: "The write is conditional." },
    ],
    summary: "Atomicity fixes the counter. A ticket fixes who goes next. TAS can be correct and still let one thread win every time.",
  },
  {
    id: "amdahl",
    labNumber: 28,
    title: "Multicore Scaling & Amdahl's Law",
    aim: "Sweep core count and serial fraction, then add communication and synchronization so speedup is no longer the pure Amdahl curve.",
    purpose: "A parallel region shrinks. The serial region, messages, and barriers do not. Efficiency falls even when the program is correct.",
    prerequisites: ["Speedup and efficiency", "A serial fraction", "The difference between strong and weak scaling"],
    learningObjectives: ["Compute an Amdahl speedup", "Read efficiency", "Explain a gap between the ideal, pure, and configured curves"],
    theory: [
      "With overhead off, speedup is 1 / (f + (1 − f) / N). The limit as N grows is 1 / f when f is not zero.",
      "Ideal speedup is N. Efficiency is speedup / N.",
      "For N greater than 1 the lab adds the communication slider once and adds synchronization cost times the barrier count. Both terms are zero at one core. Strong scaling keeps total work fixed. Weak scaling keeps work per core fixed.",
    ],
    keyTerms: [
      { term: "Serial fraction", meaning: "The part that does not shrink when cores are added." },
      { term: "Strong scaling", meaning: "Fixed total work, more cores." },
      { term: "Weak scaling", meaning: "Work grows with cores so each core’s work stays about constant." },
    ],
    assumptions: ["Communication and synchronization percentages are relative to the serial-plus-parallel critical path, not a network simulator.", "The core timeline draws at most 16 cores even if the sweep goes to 64.", "Show ideal, Show work breakdown, and the include toggles change the chart, not a hidden second model."],
    setup: ["Presets: Ideal parallel workload, 5% serial fraction, 10% serial fraction, Communication-heavy, Synchronization-heavy, Load-imbalanced, Weak scaling, Strong scaling. Sweep core counts starts off so the page opens at 16 cores."],
    procedure: [
      "Load 5% serial fraction. Leave communication and synchronization off. Read speedup at 16 cores and the 1/f limit.",
      "Turn Sweep core counts on, or press Play, and watch the curve flatten.",
      "Load Communication-heavy and compare the configured curve with pure Amdahl.",
      "Load Synchronization-heavy and change the barrier count.",
      "Switch to Weak scaling and compare efficiency with Strong scaling at 64 cores.",
      "Reset and confirm the view returns to 16 cores with the sweep off.",
    ],
    controls: ["Preset", "Strong and Weak", "Core count 1, 2, 4, 8, 16, 32, 64", "Serial fraction", "Communication overhead", "Synchronization cost", "Barrier count", "Load imbalance", "Show ideal", "Include communication", "Include synchronization", "Show work breakdown", "Sweep core counts", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Ideal, pure Amdahl, and configured curves", "Efficiency bars", "The 1/f limit", "Which slice of the critical path is largest"],
    formulas: [
      { name: "Amdahl", expression: "S = 1 / (f + (1 − f) / N)", note: "Overhead off." },
      { name: "With overhead", expression: "S = 1 / (f + (1 − f) / N + Ccomm + Csync)", note: "Ccomm and Csync are 0 at N = 1. Csync is cost per barrier times the barrier count." },
      { name: "Efficiency", expression: "E = S / N", note: "Ideal S is N, so ideal E is 1." },
    ],
    expectedBehavior: ["Five percent serial cannot exceed 20×.", "Communication and barriers pull the configured curve below pure Amdahl.", "Efficiency falls as N rises under strong scaling."],
    resultInterpretation: ["A speedup below N with overhead off is the serial fraction, not a bug.", "A further drop when Include communication is on is the extra term, not a change in f."],
    misconceptions: ["More cores do not give linear speedup once f is nonzero.", "Weak scaling is not a larger strong-scaling speedup on the same work.", "The overhead terms are a teaching model."],
    variations: ["Set f to 0 and to 0.2 with overhead off.", "Turn synchronization on and sweep barriers from 0 to 8."],
    learningOutcomes: ["Calculate 1/f", "Separate the three curves", "State what strong and weak scaling hold constant"],
    viva: [
      { question: "What is the speedup limit if 5% is serial?", answer: "20×, because 1 / 0.05 = 20." },
      { question: "What is efficiency?", answer: "Speedup divided by core count." },
      { question: "Why is overhead zero at one core?", answer: "There is nobody else to communicate or synchronize with." },
      { question: "What does strong scaling keep fixed?", answer: "Total work." },
      { question: "What does weak scaling keep fixed?", answer: "Work per core." },
    ],
    selfCheck: [
      { prompt: "f = 0.25, overhead off, infinite cores. Limit is:", choices: ["4×", "25×", "Unlimited"], answer: 0, why: "1 / 0.25 = 4." },
      { prompt: "Efficiency uses:", choices: ["S / N", "N / S", "f × N"], answer: 0, why: "Speedup per core." },
      { prompt: "Communication is added at N = 1.", choices: ["True", "False"], answer: 1, why: "The term is zero on one core." },
    ],
    summary: "Read ideal, pure Amdahl, and configured speedup as three different claims. The serial fraction sets the ceiling. Overhead lowers the curve you actually get.",
  },
];
