import type { LabGuideContent } from "./types";

export const LABS_13: LabGuideContent[] = [
  {
    id: "physical-register-file",
    labNumber: 13,
    title: "Physical Register File & Rename Map",
    aim: "Rename a short program, then watch commit reclaim the old physical destination.",
    purpose: "The physical register file is the storage. The rename map is the current name. Commit is what makes a mapping architectural and frees the previous one.",
    prerequisites: ["Architectural versus physical registers", "RAW, WAR, and WAW", "In-order commit"],
    learningObjectives: ["Read the RAT before and after an instruction", "Identify the old destination that commit can reclaim", "Explain free-list exhaustion"],
    theory: [
      "A write allocates a physical register and points the speculative map at it. Sources read the map.",
      "The commit map updates only when the instruction retires. Until then the old physical register must stay live for older readers and for recovery.",
      "Presets include mixed hazards, a RAW chain, WAR removed by renaming, WAW removed by renaming, free-list exhaustion, and commit-map recovery.",
    ],
    keyTerms: [
      { term: "Speculative map", meaning: "The RAT used at rename, including not-yet-committed writes." },
      { term: "Commit map", meaning: "The architectural mapping, updated at retire." },
      { term: "Reclaim", meaning: "Returning the previous physical destination to the free list at commit." },
    ],
    assumptions: ["Toggles for values, RAT updates, free-list changes, and dependency highlights do not change allocation.", "Free-list exhaustion stalls rename rather than aliasing a live register."],
    setup: ["Choose a preset, then Step. Auto Run to Next Step is a playback convenience."],
    procedure: [
      "Load WAR removed by renaming. Reset and Step. Record the physical register the earlier reader keeps.",
      "Load WAW removed by renaming. Confirm two physical destinations for one architectural register.",
      "Load RAW chain. Confirm the consumer’s source tag is the producer’s destination.",
      "Load Free-list exhaustion. Watch rename stop when no register is free.",
      "Load Commit-map recovery. Step through commit and see the old destination return to the free list.",
      "Turn Show Free List Changes and Show RAT Updates on while repeating one of those presets.",
    ],
    controls: ["Preset selector", "Show Register Values", "Show RAT Updates", "Show Free List Changes", "Highlight Dependencies", "Auto Run to Next Step", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Physical destination", "Old destination", "Free-register count", "Whether a source is ready"],
    formulas: [{ name: "Live range", expression: "A physical register is busy from rename until the overwriting instruction commits", note: "That is why the free list does not refill at writeback." }],
    expectedBehavior: ["WAR and WAW presets allocate a new destination.", "The RAW chain links source to that destination.", "Exhaustion blocks rename. Commit frees the old register."],
    resultInterpretation: ["If the free list grows at commit and not at execute, reclamation follows the commit map.", "If a RAW still waits, renaming did not create the value early."],
    misconceptions: ["Physical registers are not programmer-visible.", "Writeback does not by itself free the old mapping.", "Running out of physical registers is a structural stall, not a RAW."],
    variations: ["Compare free-list size on the mixed preset with and without stepping all the way to commit.", "Use Highlight Dependencies on the RAW chain only."],
    learningOutcomes: ["Update a speculative map by hand", "State when a physical register returns to the free list", "Recognize exhaustion"],
    viva: [
      { question: "When is the old destination freed?", answer: "When the instruction that overwrote it commits." },
      { question: "What does the consumer record?", answer: "The physical register mapped to its architectural source at rename." },
      { question: "Why can the free list stall a machine that has no RAW?", answer: "Every new write needs a free physical register." },
      { question: "How does recovery use the commit map?", answer: "It restores the last committed mapping and discards speculative allocations." },
      { question: "Are architectural names changed in the program?", answer: "No. Only the map changes." },
    ],
    selfCheck: [
      { prompt: "Commit reclaims:", choices: ["The new destination", "The previous physical destination", "The ROB index"], answer: 1, why: "The new one is now architectural. The old one is free if nobody older needs it." },
      { prompt: "Free-list exhaustion stops:", choices: ["Rename of a new write", "A BTB lookup", "Commit of an empty ROB"], answer: 0, why: "There is no physical register to allocate." },
      { prompt: "A RAW uses the producer’s physical register.", choices: ["True", "False"], answer: 0, why: "The source lookup captured that mapping." },
    ],
    summary: "The map is the name. The free list is the budget. Commit is the moment an old name can be recycled.",
  },
  {
    id: "load-store-queue",
    labNumber: 14,
    title: "Load / Store Queue Simulator",
    aim: "Step loads and stores through the queues, including forwarding, unknown older stores, and a memory-order replay.",
    purpose: "Memory instructions cannot be ordered by register renaming alone. The queues track addresses and age.",
    prerequisites: ["Program order", "Store data versus store address", "What a replay is"],
    learningObjectives: ["Find a store-to-load forward", "Explain a wait on an unknown older store", "Identify a violation under the bypass preset"],
    theory: [
      "The load queue and store queue hold memory operations in program order. A load may forward from the youngest older store to the same address.",
      "If an older store’s address is unknown, a conservative machine does not let a later load finish.",
      "If a load bypasses and the older store later matches its address, the load is a violation and replays. Presets include Independent load, Independent store, Store-to-load forwarding, Two stores same address, Unknown older store, Memory violation and replay, and Non-conflicting out-of-order load.",
    ],
    keyTerms: [
      { term: "Forwarding", meaning: "The load takes data from an older store in the queue instead of the cache." },
      { term: "Violation", meaning: "A load observed memory before an older store to the same address." },
      { term: "Replay", meaning: "The violating load is executed again after the store is known." },
    ],
    assumptions: ["Enable Store-to-Load Forwarding, Check for Matching Addresses, and the ordering toggles change the run. Partial-match forwarding is a display and policy option as labeled.", "Play, Step, and Reset use the same trace."],
    setup: ["Pick the instruction in the selector to focus one queue entry.", "Auto Advance Cycle steps playback."],
    procedure: [
      "Load Independent load. Step and confirm it does not wait on a store.",
      "Load Store-to-load forwarding. Enable forwarding and matching. Confirm the load sees the store data.",
      "Load Two stores, same address. Confirm the load sees the younger store.",
      "Load Unknown older store. Watch the later load wait.",
      "Load Memory violation and replay. Step until the replay is marked.",
      "Turn Detect Load-Store Violations off and on and compare the event list.",
    ],
    controls: ["Preset", "Queue-entry selector", "Enable Store-to-Load Forwarding", "Check for Matching Addresses", "Forward on Partial Match", "Show Forwarding Events", "Enable Memory Ordering Checks", "Detect Load-Store Violations", "Show Violation Events", "Auto Advance Cycle", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Addresses in each queue", "Which store forwards", "Whether a load is waiting, complete, or replaying", "Violation events"],
    formulas: [{ name: "Forwarding choice", expression: "Youngest older store with the same address", note: "An older store with an unknown address blocks a conservative load." }],
    expectedBehavior: ["The two-store preset forwards the younger value.", "Unknown older store delays the later load.", "The violation preset replays the conflicting load."],
    resultInterpretation: ["If the load data equals the younger store, age was applied correctly.", "If disabling violation detection hides the replay, the load was allowed to keep a speculative result. Turn detection back on to see the correction."],
    misconceptions: ["Forwarding is not cache bypass of a different address.", "The younger store wins only if it is older than the load.", "A replay is a correction, not a second program instruction."],
    variations: ["Disable forwarding on the forwarding preset and see the load miss the queue data.", "Run Non-conflicting out-of-order load and confirm there is no replay."],
    learningOutcomes: ["Choose the correct forwarding store", "Explain an unknown-address wait", "Point to a replay on the violation preset"],
    viva: [
      { question: "Which store forwards?", answer: "The youngest store older than the load that matches the address." },
      { question: "Why wait on an unknown store address?", answer: "It might match the load. Letting the load finish could be a violation." },
      { question: "What is a memory-order violation?", answer: "A load completed before an older store to the same address was accounted for." },
      { question: "Does a replay add an instruction to the program?", answer: "No. It re-executes the same load." },
      { question: "What do ordering checks enforce?", answer: "That a load does not pass an older conflicting store." },
    ],
    selfCheck: [
      { prompt: "Two older stores, same address. The load should see:", choices: ["The older store", "The younger store", "Always memory"], answer: 1, why: "The younger older-store is the last write before the load." },
      { prompt: "An unknown older address under conservative checking:", choices: ["Lets the load finish", "Makes the load wait", "Deletes the store"], answer: 1, why: "The address might conflict." },
      { prompt: "A violation causes:", choices: ["A replay", "A BTB hit", "Register rename"], answer: 0, why: "The load must re-execute." },
    ],
    summary: "The queues are an age-ordered memory file. Forwarding is safe only when every older address is known and the youngest match is chosen.",
  },
  {
    id: "memory-disambiguation",
    labNumber: 15,
    title: "Memory Disambiguation",
    aim: "Compare conservative waiting, always-bypass, a store-set predictor, and a 2-bit counter on the same memory trace.",
    purpose: "When a store address is unknown, the machine either waits or predicts that a later load is independent. A wrong bypass becomes a replay.",
    prerequisites: ["Load and store queues", "Violations and replays", "2-bit counters"],
    learningObjectives: ["State the four policies", "Count violations versus cycles saved", "Explain predictor training on the repeating preset"],
    theory: [
      "Conservative never bypasses an unknown older store. Always Bypass does. Both ignore history.",
      "Store Set Predictor and the 2-bit saturating counter learn pairs that conflict. A trained predictor waits on a repeated dependence and bypasses a pair that has been safe.",
      "Presets: No memory conflicts, Frequent same-address dependence, Mixed conflicts, Repeating load-store relationship, Phase-changing workload, Conservative-policy stress, Predictor-learning case.",
    ],
    keyTerms: [
      { term: "Bypass", meaning: "Let the load execute before an older unknown store." },
      { term: "Store set", meaning: "A predicted group of stores that a load may depend on." },
    ],
    assumptions: ["The policy buttons select the model. The trace stays the one loaded.", "A violation is not a successful speedup."],
    setup: ["Choose the policy, then the trace, then Reset before comparing numbers."],
    procedure: [
      "Load No memory conflicts. Run Conservative and Always Bypass. Compare cycles and violations.",
      "Load Frequent same-address dependence. Confirm Always Bypass replays and Conservative does not.",
      "Run the Store Set Predictor and the 2-bit counter on Repeating load-store relationship. Step until the predictor becomes more cautious.",
      "Load Predictor-learning case and watch the second instance of the same load PC.",
      "Load Phase-changing workload and see a predictor that was right become wrong, or the reverse.",
    ],
    controls: ["Policy: Store Set Predictor, 2-bit Saturating Counter, Always Bypass, Conservative", "Trace presets", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Wait versus bypass decision", "Violations", "Predictor update", "Cycles relative to Conservative"],
    formulas: [{ name: "Useful bypass", expression: "A bypass that does not replay", note: "Cycles saved are meaningful only when the violation count stays zero, or after replays are included." }],
    expectedBehavior: ["Conservative has no dependence violations and may be slower.", "Always Bypass is fast on independent loads and replays on conflicts.", "The learning case is more cautious on the repeated PC."],
    resultInterpretation: ["If Always Bypass’s cycle count ignores replays, do not treat it as faster. Read the violation count.", "If the predictor waits on the second iteration, it traded a bypass for safety."],
    misconceptions: ["A predicted independence is not a proof.", "Store-set state is not a cache coherence state.", "Conservative is slower because it waits, not because it computes a different architectural result."],
    variations: ["Swap Conservative and Always Bypass on Mixed conflicts.", "Reset the Predictor-learning case and stop before the second iteration so the counter has not trained."],
    learningOutcomes: ["Predict which policy replays", "Explain training on a repeated PC", "Refuse a speedup that hides violations"],
    viva: [
      { question: "What does Conservative do with an unknown older store?", answer: "It waits." },
      { question: "What does Always Bypass risk?", answer: "A memory-order violation and a replay." },
      { question: "What does the predictor learn?", answer: "That a load PC and a store PC have conflicted before." },
      { question: "Why is a replay not free?", answer: "The load’s work and anything that used its value must be redone." },
      { question: "Does phase change defeat a trained predictor?", answer: "It can. A dependence that disappears, or appears, no longer matches the stored state." },
    ],
    selfCheck: [
      { prompt: "Always Bypass on a true dependence should:", choices: ["Replay", "Be identical to Conservative", "Rename the store"], answer: 0, why: "The load went too early." },
      { prompt: "The store-set predictor is a coherence protocol.", choices: ["True", "False"], answer: 1, why: "It predicts memory dependences inside one core’s queues." },
      { prompt: "A fair cycle comparison includes:", choices: ["Replays", "Only the first attempt", "Only hits"], answer: 0, why: "Replays are part of the execution." },
    ],
    summary: "Disambiguation is a bet that an unknown store does not match. The policies differ in who is allowed to make that bet and how they learn.",
  },
  {
    id: "execution-ports",
    labNumber: 16,
    title: "Execution Port & Functional Unit Scheduler",
    aim: "Schedule mixed operations onto ports and see contention, latency, and the selected scheduling policy.",
    purpose: "Issue width is useless if every ready operation needs the same port.",
    prerequisites: ["Functional-unit classes", "Latency versus throughput", "Ready instructions"],
    learningObjectives: ["Read the port map", "Explain a stall when the only multiplier is busy", "Compare the scheduling policies on one preset"],
    theory: [
      "Ports are bundles of units. Integer ALU, multiply and divide, floating-point, load, store, and branch do not all share one port.",
      "A pipelined unit can start a new operation each cycle. A non-pipelined divide holds its port for its latency.",
      "Policies choose among legal ports. The page’s policy list is the one in the scheduler selector. Presets include independent ALU, multiply-heavy, load-heavy, mixed ALU and load, port contention, flexible versus constrained, dependency-limited, and non-pipelined divide.",
    ],
    keyTerms: [
      { term: "Port", meaning: "An issue slot wired to particular unit types." },
      { term: "Contention", meaning: "More ready operations of a class than ports that accept that class." },
      { term: "Throughput", meaning: "How often a new operation can start, not how long one operation takes." },
    ],
    assumptions: ["Enable Port Scheduling off stops the assignment the page is demonstrating.", "Highlight Stalls and Show Port Contention are visual.", "The first-available policy does not reorder ports to the lowest index if a later legal port is already the one the scheduler picks."],
    setup: ["Read the matrix of which instruction types each port accepts before running a preset."],
    procedure: [
      "Load Independent integer ALU. Step and record which ports accept the adds.",
      "Load Multiply-heavy. Watch later multiplies stall on the multiply port.",
      "Load Port contention. Change the scheduling policy, Reset, and compare port choices.",
      "Load Non-pipelined divide. See the divide occupy its port while a multiply or add uses another.",
      "Load Dependency-limited. Confirm empty ports while the chain waits.",
      "Turn Show Port Contention on and match the heat to the stall count.",
    ],
    controls: ["Preset", "Scheduling policy", "Enable Port Scheduling", "Show Port Contention", "Highlight Stalls", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Port selected", "Busy units", "Stall cycles", "IPC or throughput shown on the page", "Operations that have no legal port free"],
    formulas: [{ name: "Start condition", expression: "Operation issues only to a free port that lists its class", note: "Latency is how long the result waits. Throughput is how soon the next operation of that class can start." }],
    expectedBehavior: ["Independent adds spread across ALU ports.", "Multiple multiplies queue behind the multiply-capable port.", "A dependence chain leaves ports idle."],
    resultInterpretation: ["If a policy change moves an add but does not reduce stalls, both policies had a legal port and the bottleneck was elsewhere.", "If the divide blocks a following multiply on the same port, that is structural, not a RAW."],
    misconceptions: ["A free port of the wrong class does not help.", "Latency and throughput are different. A pipelined multiplier can have long latency and start every cycle.", "More ports do not help a dependence chain."],
    variations: ["Run Flexible versus constrained under two policies.", "Compare Load-heavy with Port contention and name the scarce class."],
    learningOutcomes: ["Assign an operation to a legal port", "Distinguish structural contention from a dependence", "Read a stall as a port conflict"],
    viva: [
      { question: "Why can an add and a load issue together?", answer: "They use different port classes, so both can find a free port." },
      { question: "Why do three multiplies not start together?", answer: "Only the ports that list integer multiply can take them." },
      { question: "What is a non-pipelined divide doing to the port?", answer: "It holds the port until the divide finishes." },
      { question: "Does an idle port mean the scheduler failed?", answer: "Not if no ready operation has that port’s class." },
      { question: "What does the policy choose?", answer: "Which legal free port an operation takes when several match." },
    ],
    selfCheck: [
      { prompt: "A multiply can issue to an ALU-only port.", choices: ["True", "False"], answer: 1, why: "The class must be listed on the port." },
      { prompt: "A dependence chain with free ports is limited by:", choices: ["Operands", "The BTB", "Cache coherence"], answer: 0, why: "The consumers are not ready." },
      { prompt: "Throughput answers:", choices: ["How soon the next operation can start", "Only the latency of one operation", "The ROB size"], answer: 0, why: "Latency is the wait for one result." },
    ],
    summary: "Ports are typed slots. Contention is several ready operations of one class. A dependence can idle every port without a scheduling bug.",
  },
];
