import type { LabGuideContent } from "./types";

export const LABS_01: LabGuideContent[] = [
  {
    id: "data-hazards",
    labNumber: 1,
    title: "Data Hazards & Instruction Scheduling",
    aim: "Identify RAW, WAR, and WAW dependences in a five-stage pipeline and measure how forwarding and a legal schedule change stall cycles.",
    purpose: "Pipeline overlap is useful only when a consumer does not read a value before the producer writes it. This experiment separates true data dependences from name dependences.",
    prerequisites: ["Five-stage pipeline: IF, ID, EX, MEM, WB", "Register reads in ID and writes in WB", "What a stall bubble is"],
    learningObjectives: ["Classify a dependence as RAW, WAR, or WAW", "Explain why forwarding removes most ALU-to-ALU RAW stalls", "Explain why a load-use pair still needs one bubble", "Compute CPI from the timeline"],
    theory: [
      "A RAW dependence is a true data dependence: the consumer reads a register the producer has not yet written.",
      "WAR and WAW are name dependences. They matter when instructions can pass each other. This in-order pipeline does not stall for them.",
      "Forwarding supplies an ALU result from the EX/MEM latch so the next instruction can use it in EX. A load result is valid only after MEM, so the very next instruction still stalls once.",
    ],
    keyTerms: [
      { term: "RAW", meaning: "Read after write. The consumer needs the producer’s result." },
      { term: "WAR / WAW", meaning: "Write after read, and write after write. The name is reused; the values are not a producer-consumer pair." },
      { term: "Forwarding", meaning: "Bypassing a result from a later pipeline latch to an earlier stage." },
    ],
    assumptions: ["In-order, single-issue, five-stage RISC-V pipeline.", "Forwarding, when enabled, covers ALU results but not a load used in the next instruction.", "Auto Schedule moves an instruction forward only when no unfinished RAW, WAR, WAW, or memory edge remains."],
    setup: ["The default program is the RAW chain of six instructions.", "Forwarding and stall insertion start enabled.", "Play, Step, and Reset sit under Simulation Controls. Speed runs from 0.25× to 4×."],
    procedure: [
      "Leave Load Example on the default RAW chain. Press Reset, then Step until the timeline finishes.",
      "Record cycles, stall cycles, and CPI in Results & Insights. With forwarding on, this chain takes 10 cycles and 0 stalls, so CPI is 10/6 = 1.67.",
      "Turn Enable Data Forwarding off and Step again. Count the new stall cells in the timeline.",
      "Turn forwarding back on. Choose Load-use from Load Example. Find the one remaining bubble between the load and the instruction that reads the loaded register.",
      "Choose WAR and WAW. Select the WAR and WAW pills in Hazard Types and confirm those edges are listed without stall cells.",
      "Return to the RAW chain. Use the row arrows or drag to try another order, then press Auto Schedule and compare cycles with the original.",
    ],
    controls: ["Load Example: RAW chain, Load-use, WAR and WAW", "Edit Instructions, Add instruction, Remove last, move-up and move-down arrows, row drag", "Hazard type pills: RAW, WAR, WAW", "Enable Data Forwarding, Auto Insert Stalls, Show Dependency Edges, Highlight Hazards", "Auto Schedule and Reset Order", "Play, Pause, Previous, Step, Reset, Simulation Speed"],
    observations: ["Which register each edge names", "Which timeline cells are stalls", "Whether the forwarding note names an EX/MEM path", "CPI = cycles / 6 for the default chain"],
    formulas: [{ name: "CPI", expression: "CPI = cycles / instructions", note: "The default chain has 6 instructions. 10 cycles and 0 stalls give CPI 1.67." }],
    expectedBehavior: ["Forwarding removes ALU-to-ALU RAW stalls.", "A load feeding the next instruction still inserts one bubble.", "WAR and WAW stay visible in the detector and do not stall this pipeline."],
    resultInterpretation: ["If disabling forwarding increases stall cycles while the architectural writes stay the same, the extra cycles are the cost of waiting for WB.", "If Auto Schedule cannot shorten the RAW chain, the dependences are true and reordering is not legal."],
    misconceptions: ["WAR and WAW are not ordinary stall hazards in this fixed-order pipeline.", "Forwarding does not remove a load-use hazard.", "A lower cycle count is meaningful only when the final register and memory results are unchanged."],
    variations: ["Edit one instruction so a later independent ADD can move ahead of a load-use pair, then compare cycles.", "Turn Auto Insert Stalls off and see unresolved hazards left in the detector."],
    learningOutcomes: ["Identify a RAW edge from producer and consumer registers", "Predict when forwarding is enough", "Read a pipeline timeline and compute CPI"],
    viva: [
      { question: "Why can register renaming not remove a RAW dependence?", answer: "The consumer needs the value, not merely a different name. Renaming removes WAR and WAW." },
      { question: "Why does a load-use pair still stall with forwarding?", answer: "The loaded word is not valid until the end of MEM, so the next EX cannot receive it from EX/MEM." },
      { question: "What does CPI mean on this timeline?", answer: "Total cycles divided by the number of instructions in the sequence." },
      { question: "When is Auto Schedule allowed to move an instruction?", answer: "Only when no unfinished RAW, WAR, WAW, or memory edge would be broken." },
      { question: "What is a name dependence?", answer: "WAR or WAW: two instructions share a register name but the later one does not need the earlier value." },
    ],
    selfCheck: [
      { prompt: "Which dependence forces a value to be produced before it is consumed?", choices: ["RAW", "WAR", "WAW"], answer: 0, why: "RAW is the true data dependence." },
      { prompt: "With forwarding on, the default six-instruction chain reports how many stall cycles?", choices: ["0", "5", "11"], answer: 0, why: "Forwarding removes the ALU stalls. The run is 10 cycles and 0 stalls." },
      { prompt: "A load immediately followed by a use of the loaded register needs:", choices: ["No bubble if forwarding is on", "One bubble", "A WAR stall"], answer: 1, why: "The load result is ready after MEM." },
    ],
    summary: "True RAW dependences limit overlap. Forwarding hides ALU latency. A load used at once still costs one stall. Name dependences do not stall this in-order pipeline.",
  },
  {
    id: "scoreboard",
    labNumber: 2,
    title: "Dynamic Scheduling with Scoreboard",
    aim: "Step a classic scoreboard through Issue, Read operands, Execute, and Write result, and name the hazard that blocks each instruction.",
    purpose: "A scoreboard issues instructions out of a simple lock-step pipeline when functional units and registers allow it, without renaming.",
    prerequisites: ["RAW, WAR, and WAW", "Structural hazards", "Functional-unit latency"],
    learningObjectives: ["Name the four scoreboard stages", "Read functional-unit status and register-result status", "Explain why a WAW blocks issue and a WAR delays the write"],
    theory: [
      "Issue checks that a functional unit is free and that no earlier instruction still has to write the same destination. That second check stops WAW.",
      "Read operands waits for source registers. That is the RAW check.",
      "Write result waits until no earlier instruction still has to read the destination. That is the WAR check. The scoreboard does not rename the register.",
    ],
    keyTerms: [
      { term: "Functional-unit status", meaning: "Busy, operation, destination, sources, and whether those sources are ready." },
      { term: "Register-result status", meaning: "Which unit, if any, will write each register." },
      { term: "Structural hazard", meaning: "The required unit is already busy, as in the one-multiplier example." },
    ],
    assumptions: ["One scoreboard, no register renaming, no reservation stations.", "The example latencies are the ones stored on each instruction.", "Play, Step, and Reset advance the same cycle model."],
    setup: ["Load Example starts empty until a preset is chosen, or the page opens on its built-in sequence.", "Presets are Load / multiply chain, WAW on x1, WAR on x8, and One multiplier."],
    procedure: [
      "Choose Load / multiply chain. Press Reset, then Step one cycle at a time.",
      "At each cycle, read the instruction table and the functional-unit status. Note which stage each instruction is in.",
      "Turn Show Data Hazards on and record which source is not ready.",
      "Load WAW on x1. Confirm the second write of x1 does not issue while the first writer is unfinished.",
      "Load WAR on x8. Watch the later write wait until the earlier reader has taken the old value.",
      "Load One multiplier. Turn Show Structural Conflicts on and see the second multiply wait for the unit.",
    ],
    controls: ["Integer units and multiply latency", "Edit, add, or remove instructions", "Load Example presets listed above", "Show Data Hazards", "Show Structural Conflicts"],
    observations: ["Which instruction is stuck in Issue versus Read operands versus Write result", "Which unit is busy", "Which register still lists a pending writer"],
    formulas: [{ name: "Stage order", expression: "Issue → Read operands → Execute → Write result", note: "An instruction leaves a stage only when that stage’s hazard check passes." }],
    expectedBehavior: ["A RAW holds the consumer in Read operands.", "A WAW holds the second writer in Issue.", "A WAR holds the writer in Write result.", "A second multiply waits when only one multiplier exists."],
    resultInterpretation: ["If the second writer of the same register issues only after the first writer completes, the scoreboard is enforcing WAW without renaming.", "If two multiplies overlap, the structural check was not the limit; look for a free unit."],
    misconceptions: ["Scoreboarding does not rename registers. WAR and WAW are stalled, not eliminated.", "Issue is not the same as execution. A issued instruction may still wait for operands.", "Out-of-order execution here is limited to the functional units the scoreboard actually has."],
    variations: ["Repeat the multiply chain with Show Structural Conflicts off and on, and compare which stall text appears.", "Step the WAR example and write down the cycle when x8 is finally written."],
    learningOutcomes: ["Map a stall to Issue, Read operands, or Write result", "Distinguish a structural stall from a data stall", "State that this scoreboard has no rename map"],
    viva: [
      { question: "Which stage catches a RAW hazard?", answer: "Read operands. The instruction has issued, but a source is not ready." },
      { question: "Which stage catches a WAW hazard?", answer: "Issue. A second writer cannot issue while the destination is still claimed." },
      { question: "Why does a WAR delay Write result?", answer: "An earlier instruction must still read the old destination value." },
      { question: "Does this lab rename registers?", answer: "No. False dependences are detected and stalled." },
      { question: "What is a structural hazard in the one-multiplier preset?", answer: "The second MUL needs the only multiplier, which is still busy." },
    ],
    selfCheck: [
      { prompt: "Scoreboarding removes WAR by renaming.", choices: ["True", "False"], answer: 1, why: "It stalls the write until earlier readers finish." },
      { prompt: "A second write of a busy destination is blocked at:", choices: ["Issue", "Execute", "Write result"], answer: 0, why: "WAW is an issue check." },
      { prompt: "Read operands waits for:", choices: ["A free functional unit only", "Source operands", "The CDB"], answer: 1, why: "That is the RAW check. There is no CDB in this lab." },
    ],
    summary: "The scoreboard overlaps independent work and stalls the rest. It never renames, so WAR and WAW remain hazards with specific stages.",
  },
  {
    id: "tomasulo",
    labNumber: 3,
    title: "Tomasulo Algorithm Simulator",
    aim: "Watch reservation stations capture values or tags, and watch one common data bus wake dependent instructions.",
    purpose: "Tomasulo removes WAR and WAW by tagging the register file, while a RAW still waits for the producer’s tag to broadcast.",
    prerequisites: ["RAW versus name dependences", "The scoreboard’s lack of renaming", "Functional-unit latency"],
    learningObjectives: ["Read Vj/Vk and Qj/Qk", "Explain a CDB broadcast", "Show that a later write replaces a register tag"],
    theory: [
      "At issue, a ready source is copied into Vj or Vk. A busy source stores the producer’s reservation-station tag in Qj or Qk.",
      "The register result status holds that tag, which is implicit renaming. A later writer replaces the tag, so an earlier reader keeps the value it already captured.",
      "One CDB broadcasts one result per cycle. Two stations that finish together cannot both write in that cycle. Latencies in this lab: add/sub 2, multiply 6, divide 12, load 2.",
    ],
    keyTerms: [
      { term: "Reservation station", meaning: "Holds the opcode, source values or tags, and the destination tag." },
      { term: "CDB", meaning: "Common data bus. One result and its tag per cycle." },
      { term: "Tag", meaning: "The station name a waiting instruction matches when the result is broadcast." },
    ],
    assumptions: ["Floating-point style opcodes in the example programs.", "A single CDB.", "No separate reorder buffer in this lab; completion updates the register file when the tag matches."],
    setup: ["Example Programs: Floating Point Chain, Dependent Chain, Independent Instructions, WAW Dependency, WAR Dependency, CDB Contention.", "Show Reservation Station Tags and Show CDB Broadcasts start available under Simulation Controls."],
    procedure: [
      "Select Dependent Chain. Reset and Step. Watch F4’s tag appear, then the multiply wait on that tag.",
      "Continue until the CDB broadcasts the add. Confirm the multiply’s Q field becomes a value.",
      "Select WAR Dependency. Step until the add has captured F2, then watch the multiply overwrite F2 without changing the add’s captured operand.",
      "Select WAW Dependency. Confirm the second write of F4 replaces the register tag.",
      "Select CDB Contention. Find the cycle where two short adds are ready and only one broadcasts.",
      "Select Independent Instructions and compare the timeline with the dependent chain.",
    ],
    controls: ["Custom instruction sequence", "Add / Sub station count", "Multiply latency", "Example Programs selector", "Show Reservation Station Tags"],
    observations: ["Which fields hold values and which hold tags", "Which station is named on the CDB", "Register-file tag before and after a second write", "Stations that finish but wait for the bus"],
    formulas: [{ name: "Issue rule", expression: "Ready source → V; busy source → Q", note: "A RAW remains until the matching tag appears on the CDB." }],
    expectedBehavior: ["Dependent Chain stays serial through the tags.", "WAR does not change an already captured source.", "CDB Contention serializes two results that finish together."],
    resultInterpretation: ["If a consumer starts only after its producer’s tag is broadcast, the wait is a RAW, not a structural stall.", "If two ready results take two cycles on the bus, the limit is the single CDB."],
    misconceptions: ["Tomasulo does not remove RAW dependences.", "Tags are not a reorder buffer and do not by themselves give precise exceptions.", "Capturing Vj is not the same as reading the architectural register later."],
    variations: ["Turn Show CDB Broadcasts off and use only the station table to infer the broadcast cycle.", "Compare Dependent Chain cycle count with Independent Instructions."],
    learningOutcomes: ["Fill V and Q for an instruction at issue", "Explain one-result-per-cycle CDB behavior", "Contrast this with a scoreboard that stalls WAR and WAW"],
    viva: [
      { question: "What does Qj mean?", answer: "The source is not ready. Qj is the reservation station that will produce it." },
      { question: "Why can two finished adds not both write this cycle?", answer: "This model has one CDB." },
      { question: "How is a WAR avoided?", answer: "The earlier instruction copies the old source value into V at issue." },
      { question: "Does a tag rename remove a RAW?", answer: "No. The consumer still waits for that tag on the bus." },
      { question: "What happens to the register tag on a WAW?", answer: "The later writer replaces it. Only instructions that still hold the old tag wait for the old producer." },
    ],
    selfCheck: [
      { prompt: "A busy source is stored as:", choices: ["Vj", "Qj", "The CDB data"], answer: 1, why: "Q holds the producer tag." },
      { prompt: "Tomasulo eliminates RAW hazards.", choices: ["True", "False"], answer: 1, why: "It only renames away WAR and WAW." },
      { prompt: "Add latency in this lab is:", choices: ["2 cycles", "6 cycles", "12 cycles"], answer: 0, why: "Multiply is 6 and divide is 12." },
    ],
    summary: "Stations and tags let independent work pass false dependences. A true RAW still waits for one CDB broadcast.",
  },
  {
    id: "register-renaming",
    labNumber: 4,
    title: "Scoreboarding with Register Renaming",
    aim: "Compare the same instruction sequence with and without explicit physical-register renaming.",
    purpose: "Renaming gives a later write a new physical register so WAR and WAW no longer block overlap. RAW still uses the producer’s physical register.",
    prerequisites: ["Scoreboard stages", "Architectural versus physical registers", "RAW, WAR, and WAW"],
    learningObjectives: ["Read a rename map", "Show a WAR or WAW disappearing when renaming is on", "Explain why a RAW mapping still waits"],
    theory: [
      "The architectural register is the name in the instruction. The physical register holds the value.",
      "The rename map records the current physical register for each architectural register. A write allocates a free physical register and updates the map.",
      "A read uses the map at rename time, so it keeps pointing at the old physical register after a later write.",
    ],
    keyTerms: [
      { term: "RAT", meaning: "Register alias table: architectural register to physical register." },
      { term: "Free list", meaning: "Physical registers not currently named by the map." },
      { term: "False dependence", meaning: "WAR or WAW, removed by a new physical destination." },
    ],
    assumptions: ["The toggle Enable Register Renaming switches the same program between the two models.", "If the free list is exhausted, allocation cannot invent a register.", "Show Rename Map displays the mapping used for the explanation."],
    setup: ["Use Load Example to restore the built-in sequence.", "Enable Register Renaming starts as the comparison switch."],
    procedure: [
      "Press Load Example. Turn Enable Register Renaming off. Reset and Step through the timeline.",
      "Record stalls that the panel attributes to WAR or WAW.",
      "Turn Enable Register Renaming on and Show Rename Map on. Reset and Step the same program.",
      "For each write, note the new physical destination and the old mapping.",
      "Confirm a RAW consumer still names the producer’s physical register.",
      "Compare cycle counts between the two runs.",
    ],
    controls: ["Physical register count", "Instruction text", "Enable Register Renaming", "Show Rename Map", "Play, Pause, Previous, Step, Reset, Simulation Speed"],
    observations: ["Physical destination of each write", "Whether a WAR edge remains when renaming is on", "Free-list size if it is shown", "Cycle difference between the two modes"],
    formulas: [{ name: "Rename", expression: "dest architectural → new physical; sources → current map", note: "Only the destination is allocated. Sources keep the mapping from before this instruction." }],
    expectedBehavior: ["Renaming off preserves scoreboard stalls on false dependences.", "Renaming on lets a later write proceed with a different physical register.", "A RAW consumer still waits for the physical register it was given."],
    resultInterpretation: ["A shorter timeline with the same architectural results means the removed stalls were name hazards.", "If the timeline does not shorten, the remaining edges are RAW or structural."],
    misconceptions: ["Renaming does not create a new value for a RAW consumer.", "The architectural register in the program text does not change.", "When the free list is empty the write is not given a new physical name. The lab reports a rename stall."],
    variations: ["Toggle Show Rename Map off and reconstruct one mapping from the instruction list.", "Run with renaming off, write the stall reason, then confirm that reason is absent with renaming on."],
    learningOutcomes: ["Draw a rename map before and after a write", "Separate RAW from WAR on a renamed sequence", "Compare cycle counts fairly"],
    viva: [
      { question: "What is allocated on a write?", answer: "A free physical register. The map then points the architectural destination at it." },
      { question: "What does a source lookup return?", answer: "The physical register currently mapped to that architectural source." },
      { question: "Which hazards survive renaming?", answer: "RAW, and any structural hazard. WAR and WAW on that destination do not." },
      { question: "Why keep the old physical register?", answer: "Earlier readers still need the old value." },
      { question: "Is the physical register visible to the program?", answer: "No. The instruction text still names architectural registers." },
    ],
    selfCheck: [
      { prompt: "Renaming removes which hazard?", choices: ["RAW", "WAR", "A cache miss"], answer: 1, why: "WAR and WAW are name hazards. RAW remains." },
      { prompt: "A source operand is renamed using:", choices: ["A newly allocated register", "The current map", "The free list head only"], answer: 1, why: "Sources are looked up. The destination is allocated." },
      { prompt: "The comparison that shows the benefit is:", choices: ["Renaming off versus on for the same program", "A different program with more instructions", "A wider cache"], answer: 0, why: "Only the renaming toggle should change." },
    ],
    summary: "Explicit renaming is the scoreboard plus a map. False dependences get new names. True dependences stay on the producer’s physical register.",
  },
];
