import type { LabGuideContent } from "./types";

export const LABS_09: LabGuideContent[] = [
  {
    id: "tournament-predictor",
    labNumber: 9,
    title: "Tournament & Hybrid Predictor",
    aim: "Watch a chooser select the local or global component, and compare both with a bimodal baseline.",
    purpose: "No single history works for every branch. A meta-predictor learns which component was right when they disagree.",
    prerequisites: ["Local history, GShare, and bimodal counters", "2-bit state updates", "Accuracy as correct over total"],
    learningObjectives: ["State when the chooser moves", "Read the final prediction", "Compare component accuracies without crowning a permanent winner"],
    theory: [
      "The chooser picks local or global before the branch resolves. It updates only when one of those two was right and the other was wrong.",
      "The chooser is not a taken/not-taken counter. Bimodal is the history-free baseline and is not one of the chooser’s options.",
      "Traces in this lab favor different components: locally predictable, globally correlated, mixed, loop, phase change, and aliasing-heavy.",
    ],
    keyTerms: [
      { term: "Chooser", meaning: "Meta-state that prefers local or global after they disagree." },
      { term: "Component", meaning: "Local or global predictor whose output the chooser may select." },
    ],
    assumptions: ["Show Local History, Show Global History, and Show Chooser hide panels. The final prediction still uses the chooser.", "Highlight Mispredictions does not change counts."],
    setup: ["Load example supplies the six traces.", "Accuracy Statistics names whoever is ahead on the branches seen so far."],
    procedure: [
      "Load Locally predictable. Reset and Step. Record local, global, chooser, and final prediction.",
      "Load Globally correlated and repeat. Watch the chooser move toward global when global is uniquely correct.",
      "Load Mixed workload and Phase change. Note that the leader in Accuracy Statistics can change.",
      "Hide the chooser and confirm the final prediction text still names the preferred component.",
      "Load Aliasing-heavy and see a component lose accuracy without that loss being the chooser’s fault.",
    ],
    controls: ["Load example", "Show Local History", "Show Global History", "Show Chooser", "Highlight Mispredictions", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Each component’s prediction", "Chooser state before and after a disagreement", "Final prediction", "Running accuracies"],
    formulas: [{ name: "Chooser update", expression: "Update only when exactly one of local or global is correct", note: "If both are right or both are wrong, the chooser has no new evidence." }],
    expectedBehavior: ["Local-friendly traces raise local accuracy.", "Global-friendly traces raise global accuracy and pull the chooser.", "Bimodal remains visible as a baseline, not as a chooser input."],
    resultInterpretation: ["If hybrid accuracy exceeds the weaker component, the chooser spent time on the better one.", "A tie or a loss to bimodal means this trace did not give the chooser a useful disagreement."],
    misconceptions: ["The accuracy table is not a fixed winner for all programs.", "Bimodal is not selected by the chooser.", "Hiding a panel does not disable the prediction."],
    variations: ["Run Phase change and write the cycle where the leading component switches.", "Turn Highlight Mispredictions on and count disagreements between local and global."],
    learningOutcomes: ["Explain a chooser update", "Compare three accuracies on one trace", "Avoid declaring a universal best predictor"],
    viva: [
      { question: "When does the chooser change?", answer: "Only when local and global disagree in correctness." },
      { question: "Is the chooser a taken counter?", answer: "No. It chooses a component." },
      { question: "What is bimodal’s role here?", answer: "A history-free baseline. The chooser does not pick it." },
      { question: "Why have both local and global?", answer: "Some branches repeat their own pattern. Others depend on neighboring branches." },
      { question: "Can the leader change mid-trace?", answer: "Yes. Accuracy Statistics is cumulative for the branches seen so far." },
    ],
    selfCheck: [
      { prompt: "The chooser selects between:", choices: ["Local and global", "Taken and not taken", "BTB ways"], answer: 0, why: "Direction bits belong to the components." },
      { prompt: "Both components wrong means the chooser:", choices: ["Flips anyway", "Has no new preference", "Clears the BTB"], answer: 1, why: "There is no winner to reinforce." },
      { prompt: "Bimodal is a chooser input.", choices: ["True", "False"], answer: 1, why: "It is only the baseline." },
    ],
    summary: "The hybrid wins only when the chooser can tell the components apart. Read the table for this trace, not for all programs.",
  },
  {
    id: "speculative-execution",
    labNumber: 10,
    title: "Speculative Execution & Recovery",
    aim: "Run a correct prediction and a misprediction, then watch the checkpoint squash only the wrong-path instructions.",
    purpose: "Fetch should not wait for every branch, but a wrong path must not become architectural state.",
    prerequisites: ["Taken and not-taken", "ROB or checkpointed registers", "What younger means"],
    learningObjectives: ["Identify speculative instructions", "State the recovery rule used here", "Relate the predictor choice to the squash"],
    theory: [
      "With prediction on, fetch continues down the predicted path. A not-taken prediction fetches fall-through instructions.",
      "If the branch is actually taken, those younger instructions are squashed. Older results stay.",
      "The predictor can be a 2-bit counter, a 1-bit predictor, Always Taken, or Always Not Taken. Enable Branch Prediction off makes fetch wait until the branch resolves.",
    ],
    keyTerms: [
      { term: "Checkpoint", meaning: "Saved architectural state at the branch, restored on a squash." },
      { term: "Wrong path", meaning: "Instructions fetched because the prediction did not match the outcome." },
      { term: "Recovery penalty", meaning: "Cycles spent on work that is squashed and refetched." },
    ],
    assumptions: ["Presets include Single misprediction, Correct speculation, Deep speculative window, Back-to-back branches, Nested unresolved branches, and Long-latency branch resolution.", "Show Register Changes displays the checkpoint. It does not alter the squash rule."],
    setup: ["Branch Predictor & Outcome selects the predictor.", "The pipeline timeline marks speculative and squashed instructions."],
    procedure: [
      "Load Correct speculation. Leave prediction enabled. Reset and Step. Confirm there is no squash.",
      "Load Single misprediction. Step until the branch resolves and read which instructions are squashed.",
      "Switch the predictor to Always Not Taken and repeat. Then try Always Taken.",
      "Turn Enable Branch Prediction off, Reset, and see fetch wait.",
      "Load Nested unresolved branches and note more than one checkpoint.",
      "Turn Show Register Changes on and compare the restored registers with the checkpoint.",
    ],
    controls: ["Preset selector", "Predictor: 2-bit, 1-bit, Always Taken, Always Not Taken", "Enable Branch Prediction", "Show Pipeline Bubbles", "Highlight Misprediction", "Show Register Changes", "Auto Reset on Completion", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Predicted direction", "Actual outcome", "Squashed instruction names", "Restored registers", "Cycles with prediction on versus off"],
    formulas: [{ name: "Recovery rule", expression: "Squash the branch’s younger wrong-path instructions", note: "Older committed results remain." }],
    expectedBehavior: ["A matching prediction keeps the speculative instructions.", "A mismatch flushes them and redirects fetch.", "Prediction off avoids the squash and also avoids the overlap."],
    resultInterpretation: ["If the checkpoint matches the registers after recovery, wrong-path writes did not stick.", "A longer timeline with prediction off can still be the correct comparison for overlap, not for the architectural result."],
    misconceptions: ["Speculative instructions are not committed.", "Always Taken is not a real tournament predictor.", "Nested branches need more than one checkpoint."],
    variations: ["Type a branch program and set Resolve branch after N cycles to 4 so several wrong-path instructions enter before the squash.", "Switch speculation off and compare wasted instructions with speculation on.", "Change the predictor to Always Taken, then Always Not Taken, on the same program."],
    learningOutcomes: ["Trace a misprediction to a squash", "Explain what the checkpoint restores", "Choose a predictor and predict whether this preset squashes"],
    viva: [
      { question: "What is fetched on a not-taken prediction?", answer: "The fall-through instructions." },
      { question: "What is squashed if that prediction was wrong?", answer: "Those younger instructions, not older committed work." },
      { question: "Why keep a checkpoint?", answer: "So recovery can restore architectural registers without replaying the whole program." },
      { question: "What does prediction off change?", answer: "Fetch waits for resolution, so there is no wrong path and no overlap past the branch." },
      { question: "Can two unresolved branches exist?", answer: "Yes. The nested preset keeps more than one checkpoint." },
    ],
    selfCheck: [
      { prompt: "Wrong-path instructions should:", choices: ["Commit", "Be squashed", "Update the cache permanently in this model"], answer: 1, why: "They are younger than a mispredicted branch." },
      { prompt: "Always Not Taken is:", choices: ["A chooser", "A fixed direction policy in this lab", "A BTB"], answer: 1, why: "The selector lists it beside the 1-bit and 2-bit machines." },
      { prompt: "Older committed results are restored away.", choices: ["True", "False"], answer: 1, why: "Recovery discards younger wrong-path state." },
    ],
    summary: "Speculation overlaps the predicted path. The checkpoint is what makes a wrong guess reversible.",
  },
  {
    id: "superscalar",
    labNumber: 11,
    title: "Superscalar Pipeline Explorer",
    aim: "Change fetch, decode, dispatch, execute, and retire widths and measure the IPC the program actually achieves.",
    purpose: "A wider machine raises the ceiling. Dependences and the narrowest stage decide how much of that width is used.",
    prerequisites: ["IPC and CPI", "Pipeline stages", "Data dependences"],
    learningObjectives: ["Set a width from 1 to 4", "Explain why IPC can exceed 1", "Find the stage that limits a preset"],
    theory: [
      "Scalar (1), Dual Issue (2), and Quad Issue (4) set every stage width together. Each stage also has its own + and − control, from 1 to 4.",
      "This model issues in order and retires in order. Width is a cap, not a guaranteed IPC.",
      "Presets: Independent instructions, Dependency chain, Mixed graph, Long-latency operation, Front-end bottleneck, Back-end bottleneck.",
    ],
    keyTerms: [
      { term: "Width", meaning: "Maximum instructions that stage accepts in one cycle." },
      { term: "IPC", meaning: "Instructions retired divided by cycles. It may exceed 1." },
      { term: "Utilization", meaning: "Slots used divided by cycles times width." },
    ],
    assumptions: ["In-order issue and in-order retire.", "Show Pipeline Bubbles, Highlight Active Lanes, and Show Instruction IDs are display options.", "Auto Reset on Completion restarts playback. It does not change the widths."],
    setup: ["Start from Quad Issue or the Mixed graph preset widths.", "The IPC Explorer shows retired instructions over the cycles stepped so far."],
    procedure: [
      "Load Independent instructions. Press Scalar (1), Reset, and Step to the end. Record IPC.",
      "Press Quad Issue (4), Reset, and repeat. IPC should rise if the instructions are independent.",
      "Load Dependency chain, keep width 4, and Reset. Explain why IPC stays near 1.",
      "Lower only Fetch width with the − control and reload Front-end bottleneck.",
      "Raise Execute width alone on Back-end bottleneck and compare utilization.",
      "Turn Highlight Active Lanes on and see empty lanes on the chain.",
    ],
    controls: ["Scalar (1), Dual Issue (2), Quad Issue (4)", "Per-stage + and − width", "Instruction stream preset", "Show Pipeline Bubbles", "Highlight Active Lanes", "Show Instruction IDs", "Auto Reset on Completion", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Instructions in each lane", "Fetch and execute utilization", "IPC", "Which stage width is smaller than the others"],
    formulas: [{ name: "IPC", expression: "IPC = instructions retired / cycles", note: "CPI = 1 / IPC for the same retired count and cycles. IPC can exceed 1." }],
    expectedBehavior: ["Independent instructions scale toward the width.", "A dependence chain does not fill four lanes.", "A front-end width of 1 caps the machine even if execute is 4."],
    resultInterpretation: ["If Quad Issue does not raise IPC, the limit is the program or a narrower stage, not the execute button.", "Utilization below 100% with a dependence chain is expected."],
    misconceptions: ["Width 4 does not mean IPC 4.", "IPC greater than 1 does not violate CPI = cycles / instructions. CPI is then below 1.", "In-order issue cannot pass a stalled producer."],
    variations: ["Set Fetch to 4 and Retire to 2 on Independent instructions, then name the bottleneck stage.", "Set fetch to 1 and retire to 4 on Independent instructions.", "Compare Long-latency operation at width 1 and width 4."],
    learningOutcomes: ["Compute IPC from the explorer", "Identify a front-end versus back-end limit", "State that width is a cap"],
    viva: [
      { question: "Can IPC exceed 1?", answer: "Yes, when more than one instruction retires per cycle on average." },
      { question: "Why does a chain stay near IPC 1?", answer: "Each instruction waits for the previous result, so extra lanes stay empty." },
      { question: "What does Scalar (1) set?", answer: "Every stage width to 1." },
      { question: "Does this model issue out of order?", answer: "No. Issue and retire are in order." },
      { question: "What is utilization?", answer: "Used slots divided by the slots the width could have provided." },
    ],
    selfCheck: [
      { prompt: "Quad Issue guarantees IPC 4.", choices: ["True", "False"], answer: 1, why: "Dependences and the narrowest stage still apply." },
      { prompt: "IPC is:", choices: ["Cycles / instructions", "Instructions retired / cycles", "Width times stalls"], answer: 1, why: "The reciprocal is CPI." },
      { prompt: "A fetch width of 1 with execute width 4 is limited by:", choices: ["The front end", "The BTB", "Rename only"], answer: 0, why: "Fetch cannot supply four instructions." },
    ],
    summary: "Superscalar width is an opportunity. The IPC Explorer shows how much of it the selected program used.",
  },
  {
    id: "issue-queue",
    labNumber: 12,
    title: "Instruction Window & Issue Queue",
    aim: "Watch wakeup and select issue the oldest ready instructions within the window and issue width.",
    purpose: "The window is where out-of-order issue becomes possible: an instruction leaves only when every source is ready and a unit is free.",
    prerequisites: ["RAW dependences", "Functional-unit types", "Issue versus commit"],
    learningObjectives: ["Read ready versus waiting", "Apply oldest-ready selection", "See a small window or a narrow issue width serialize work"],
    theory: [
      "Wakeup marks instructions whose producers have completed.",
      "Select uses Oldest Ready First. Up to the issue width instructions issue, and only one per free unit.",
      "Window sizes are 4, 8, 16, and 32. Issue width is 1, 2, or 4. Unit mixes are 1 Load/1 ALU/1 MUL, 1 Load/2 ALU/1 MUL, and 2 Load/2 ALU/1 MUL.",
    ],
    keyTerms: [
      { term: "Instruction window", meaning: "The set of dispatched instructions waiting to issue." },
      { term: "Wakeup", meaning: "A completed producer makes dependent sources ready." },
      { term: "Select", meaning: "Choosing which ready instructions take free units this cycle." },
    ],
    assumptions: ["Policy is fixed as Oldest Ready First.", "Show Operand Readiness, Highlight Selected Instructions, and Show Dependency Arrows are visual.", "Presets: Mixed dependency graph, Independent instructions, RAW chain, Competing ALU instructions, Long-latency producer, Small window."],
    setup: ["The status line reports occupied, free, ready, and waiting counts.", "The dependency graph matches the preset."],
    procedure: [
      "Load RAW chain. Set window 8 and issue width 2. Reset and Step.",
      "Confirm only the producer is ready, then watch wakeup of the consumer.",
      "Load Independent instructions and raise issue width to 4. Compare how many issue in one cycle.",
      "Load Competing ALU instructions with 1 ALU. Then switch to 2 ALU and Reset.",
      "Load Small window and set the window to 4. Note instructions that cannot enter.",
      "Turn Show Dependency Arrows on and match each wait to an edge.",
    ],
    controls: ["Preset", "Window size 4/8/16/32", "Issue width 1/2/4", "Functional-unit mix", "Show Operand Readiness", "Highlight Selected Instructions", "Show Dependency Arrows", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Ready queue membership", "Who is selected", "Occupancy versus window size", "Issue rate over the timeline"],
    formulas: [{ name: "Issue condition", expression: "Ready sources and a free unit, oldest first, up to issue width", note: "One instruction per free unit in a cycle." }],
    expectedBehavior: ["A RAW chain wakes one consumer after the producer.", "Independent instructions fill the issue width until units run out.", "A window of 4 on Small window blocks dispatch."],
    resultInterpretation: ["If widening the window does not raise issue rate, the limit is dependences or units.", "If adding an ALU removes stalls on Competing ALU instructions, the stall was structural."],
    misconceptions: ["Oldest ready is not oldest in program order if the oldest is still waiting.", "Issue is not commit.", "A larger window cannot create operand values."],
    variations: ["Raise issue width to 4 while the unit mix stays at one ALU. The issue rate should not scale past the free units.", "Hold the mixed graph and sweep issue width from 1 to 4.", "Compare 1 ALU and 2 ALU on Competing ALU instructions."],
    learningOutcomes: ["List the ready set after a wakeup", "Apply the issue-width cap", "Separate a full window from a data wait"],
    viva: [
      { question: "What makes an instruction ready?", answer: "Every source operand is ready and it is still in the window." },
      { question: "Who wins if two ALU ops are ready and one ALU is free?", answer: "The older ready instruction." },
      { question: "What does issue width limit?", answer: "How many selected instructions may leave in one cycle, still one per free unit." },
      { question: "Why can a small window hurt?", answer: "Later independent work cannot enter while older instructions occupy the slots." },
      { question: "Does wakeup rename the register?", answer: "No. It only marks the dependent source ready." },
    ],
    selfCheck: [
      { prompt: "The select policy is:", choices: ["Oldest Ready First", "Random", "Shortest latency always"], answer: 0, why: "The page states that policy." },
      { prompt: "A waiting instruction is one that:", choices: ["Has a producer still outstanding", "Has already committed", "Is a BTB miss"], answer: 0, why: "Waiting means a source is not ready." },
      { prompt: "Two ready ALU ops and one ALU issue:", choices: ["Both", "The older one", "Neither"], answer: 1, why: "One instruction per free unit." },
    ],
    summary: "Wakeup creates candidates. Select spends the issue width on the oldest ready ones that have a unit.",
  },
];
