import type { LabGuideContent } from "./types";

export const LABS_21: LabGuideContent[] = [
  {
    id: "coherence-traffic",
    labNumber: 21,
    title: "Cache-Coherence Traffic Analyzer",
    aim: "Count control and data messages for a coherence trace, and compare what a bus protocol records with what a directory records.",
    purpose: "State transitions are not the whole cost. Each invalidation, upgrade, and data movement has a size.",
    prerequisites: ["MSI, MESI, and MOESI transitions", "Write-back", "False sharing"],
    learningObjectives: ["Separate control bytes from data bytes", "Identify a hotspot line", "Explain a silent upgrade’s zero-byte case"],
    theory: [
      "Control messages are estimated at 8 bytes. A data payload is one 64-byte line. These are lab estimates, not a packet format from a chip.",
      "A silent Exclusive-to-Modified upgrade is 0 bytes unless silent upgrades are turned off. A clean eviction is not a write-back.",
      "Workloads include Private data, Read sharing, Producer / consumer, True sharing, False sharing, Ping-pong ownership, Read-mostly, and Write-intensive. Protocols are MSI, MESI, MOESI, and Directory.",
    ],
    keyTerms: [
      { term: "Upgrade", meaning: "A sharer becoming the writer and invalidating other copies." },
      { term: "Migration", meaning: "Exclusive ownership moving to another core." },
      { term: "Hotspot", meaning: "The line whose messages dominate the trace." },
    ],
    assumptions: ["Filtering changes what is drawn, not the underlying trace until you change protocol or workload.", "Shared reads that only drop exclusivity are not counted as migrations."],
    setup: ["Choose protocol, workload, and core count, then Step. Use the message filter to hide types you are not studying."],
    procedure: [
      "Select Private data and MESI. Step the trace. Record total bytes.",
      "Select False sharing and compare bytes and invalidations with Private data.",
      "Select Ping-pong ownership and find the line with the most traffic.",
      "Switch the protocol to Directory on the same workload and compare message recipients.",
      "Confirm a silent upgrade contributes no data bytes.",
      "Set Filter by message to Invalidations and recount. Turn Enable Silent Upgrades off and rerun Private data.",
    ],
    controls: ["Protocol MSI, MESI, MOESI, Directory", "Workload list", "Number of cores 2, 4, or 8", "Enable Write-Allocate", "Enable Silent Upgrades", "Filter by core", "Filter by message", "Show Coherence Messages", "Highlight Active Core", "Auto Scroll Event Log", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Messages by type", "Control versus data bytes", "Per-core counts", "Migrations", "The busiest line"],
    formulas: [{ name: "Traffic", expression: "bytes = 8 × control messages + 64 × data messages", note: "A silent upgrade adds neither, while silent upgrades remain enabled." }],
    expectedBehavior: ["Private data stays small.", "False sharing and ping-pong grow invalidations.", "Directory traffic tracks sharers rather than every core."],
    resultInterpretation: ["A byte increase with the same architectural values means the protocol moved the line more, not that the program result changed.", "Do not treat the 8-byte and 64-byte figures as a real interconnect."],
    misconceptions: ["More traffic is not automatically a wrong result.", "A clean eviction is not a write-back.", "Directory and snooping counts are comparable only on the same trace."],
    variations: ["Hold False sharing and switch MSI, MESI, and MOESI.", "Raise the core count on Read sharing and watch the sharer-related messages."],
    learningOutcomes: ["Compute bytes from the message mix", "Name the hotspot line", "Explain a zero-byte silent upgrade"],
    viva: [
      { question: "What is the lab’s control-message size?", answer: "8 bytes, a lab estimate rather than a chip packet." },
      { question: "What is the data payload?", answer: "One 64-byte line." },
      { question: "When is an upgrade silent?", answer: "Exclusive to Modified when no other cache holds the line, and silent upgrades are enabled." },
      { question: "Is a clean eviction a write-back?", answer: "No. A clean line matches memory, so eviction sends no data." },
      { question: "What is a migration?", answer: "Exclusive ownership of a line moving to another core." },
    ],
    selfCheck: [
      { prompt: "Two data messages cost:", choices: ["16 bytes", "128 bytes", "8 bytes"], answer: 1, why: "64 bytes each." },
      { prompt: "False sharing should:", choices: ["Raise invalidations", "Eliminate all traffic", "Change the C compiler"], answer: 0, why: "Writers bounce one line." },
      { prompt: "The byte sizes are a specific CPU’s packet format.", choices: ["True", "False"], answer: 1, why: "They are lab estimates." },
    ],
    summary: "Count messages, then multiply by the lab’s sizes. The hotspot line is where the protocol spent its bandwidth.",
  },
  {
    id: "snooping-vs-directory",
    labNumber: 22,
    title: "Snooping vs Directory Coherence",
    aim: "Run one trace through snooping and through a directory and compare recipients, messages, and the lab’s latency model.",
    purpose: "The architectural values match because both columns use the same coherence transitions. The interconnect accounting does not.",
    prerequisites: ["Broadcast versus targeted invalidation", "Sharer lists", "Why a lookup has a cost"],
    learningObjectives: ["Count probes versus directory messages", "State when the directory is not cheaper", "Read the scaling chart"],
    theory: [
      "Snooping probes the other caches on a miss or upgrade. Directory messages go to the owner or the sharers, plus the lookup.",
      "Latency numbers are lab assumptions: a bus probe costs 1 unit per other cache, and a directory lookup is a fixed cost that grows slowly with core count. They are not a chip’s cycle time.",
      "Presets include Private data, Read sharing, One writer many sharers, Ping-pong, Sparse sharing, and dense many-core sharing. Core count can be changed from the configuration.",
    ],
    keyTerms: [
      { term: "Probe", meaning: "A snoop sent to another cache." },
      { term: "Lookup", meaning: "The directory access that finds the sharer vector." },
    ],
    assumptions: ["Both columns share architectural values.", "Toggles for arrows, animation, and highlight do not change the counts.", "A design that is quiet at 4 cores can still flood a 32-core bus."],
    setup: ["Leave both Snooping and Directory-based enabled so the comparison stays visible."],
    procedure: [
      "Load Private data. Step. Compare probes with directory messages.",
      "Load One writer, many sharers. Count invalidations. Directory invalidations should match sharers. Snooping still probes the other cores.",
      "Increase the core count and rerun. Watch snoop traffic grow faster than directory traffic.",
      "Read Latency Comparison. Do not claim the directory is always lower latency. On a small machine the lookup can dominate.",
      "Load Ping-pong and see ownership move in both columns with different recipients.",
      "Turn Directory-based off and confirm that column is hidden. Use Issue Request to append one read or write, or Clear Log to empty the trace.",
    ],
    controls: ["Workload", "Number of cores", "Snooping (bus-based)", "Directory-based", "Issue Request", "Clear Log", "Show Message Arrows", "Animate Requests", "Highlight Active Core", "Auto Advance Requests", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Recipients of each request", "Probe count", "Directory message count", "Latency bars", "Scaling as cores increase"],
    formulas: [{ name: "Snoop probes", expression: "Other caches are probed on a broadcast", note: "Directory invalidations follow the sharer count. Latency adds the lab’s lookup and hop costs." }],
    expectedBehavior: ["Snoop traffic grows with core count.", "Directory invalidations stay tied to sharers.", "Directory latency is not automatically smaller at every size."],
    resultInterpretation: ["If values match and only the message columns differ, the comparison is fair.", "If directory latency is higher at 4 cores and lower at 32, both statements can be true under this cost model."],
    misconceptions: ["Directory coherence is not always fewer messages and always lower latency.", "Turning a protocol off does not change the other’s architecture.", "The latency unit is not a published bus cycle."],
    variations: ["Sweep core count on dense sharing.", "Issue one extra write and see who is added to the probe list."],
    learningOutcomes: ["Compare recipients on one request", "Explain a crossover in the latency chart", "Refuse a universal winner"],
    viva: [
      { question: "Why can the values match while the traffic does not?", answer: "Both use the same coherence transitions. Only the interconnect accounting changes." },
      { question: "Who does snooping contact?", answer: "The other caches, by broadcast or probe." },
      { question: "Who does the directory contact?", answer: "The owner or the recorded sharers, after a lookup." },
      { question: "Why might the directory be slower at 4 cores?", answer: "The lookup cost can exceed a short broadcast." },
      { question: "What grows with core count on a bus?", answer: "The number of probes." },
    ],
    selfCheck: [
      { prompt: "Directory invalidations track:", choices: ["Every core always", "Recorded sharers", "Only the BTB"], answer: 1, why: "Uninvolved cores are not on the vector." },
      { prompt: "The directory is always lower latency here.", choices: ["True", "False"], answer: 1, why: "The lookup can dominate on a small machine." },
      { prompt: "Architectural values in the two columns should:", choices: ["Match", "Diverge on every write", "Ignore memory"], answer: 0, why: "The comparison uses one transition model." },
    ],
    summary: "Same memory system, two interconnects. Read probes, messages, and latency separately, and do not crown a winner for every core count.",
  },
  {
    id: "mshr",
    labNumber: 23,
    title: "Non-Blocking Cache & MSHR Lab",
    aim: "Compare a blocking cache with a non-blocking cache that keeps misses in MSHRs, merges same-line misses, and stalls when the MSHRs are full.",
    purpose: "A miss does not have to freeze every later access. Hit-under-miss and miss-under-miss are limited by the number of miss-status holding registers.",
    prerequisites: ["Cache hits and misses", "Miss latency", "What an outstanding miss is"],
    learningObjectives: ["Define an MSHR", "Show a merged miss", "Explain a stall when no MSHR is free"],
    theory: [
      "A blocking cache handles one miss at a time. A non-blocking cache records each outstanding miss in an MSHR.",
      "Hit-under-miss serves a hit while a miss is outstanding. Miss-under-miss allows another miss. The Blocking button forces those capabilities off in the comparison.",
      "Two accesses to one line share an MSHR. A request that finds no free MSHR stalls. Presets: Single miss, Hit under miss, Two independent misses, Merged same-line misses, MSHR exhaustion, High memory-level parallelism, Blocking versus non-blocking.",
    ],
    keyTerms: [
      { term: "MSHR", meaning: "Miss-status holding register. Tracks one outstanding line fill." },
      { term: "Merge", meaning: "A second miss to a line that already has an MSHR joins that fill." },
      { term: "MLP", meaning: "Memory-level parallelism: how many misses are outstanding, not instruction-level parallelism." },
    ],
    assumptions: ["Default miss latency and cache size are the controls on the page, not a mockup’s decorative latency.", "MSHR counts are 1, 2, 4, or 8.", "Highlight Hits does not change status."],
    setup: ["Choose Blocking or Non-blocking, set MSHRs and the two enable toggles, then load a preset."],
    procedure: [
      "Load Hit under miss. Select Non-blocking, enable Hit-Under-Miss, and Step. A warm line should hit while the other miss is outstanding.",
      "Switch to Blocking, Reset, and compare total cycles.",
      "Load Merged same-line misses. Confirm one memory request for several addresses in that line.",
      "Load MSHR exhaustion with 1 MSHR. Step until a request stalls.",
      "Raise MSHRs to 4, load High memory-level parallelism, and compare peak outstanding misses.",
      "Turn Miss-Under-Miss off and rerun Two independent misses.",
    ],
    controls: ["Blocking and Non-blocking", "MSHR count 1/2/4/8", "Enable Hit-Under-Miss", "Enable Miss-Under-Miss", "Cache size, line size, replacement, miss latency", "Presets", "Show Cache Requests", "Show MSHR Activity", "Show Memory Accesses", "Highlight Hits", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["MSHR occupancy", "Hit under an outstanding miss", "Merged versus separate fills", "Stall cycles", "Total cycles versus the blocking run"],
    formulas: [{ name: "Outstanding misses", expression: "Occupied MSHRs ≤ configured MSHRs", note: "A same-line miss does not need a second MSHR." }],
    expectedBehavior: ["Non-blocking overlap finishes the hit-under-miss preset sooner than blocking.", "Same-line accesses merge.", "One MSHR stalls the exhaustion preset."],
    resultInterpretation: ["A lower cycle count with the same results is overlap, not a weaker correctness rule.", "A stall with free cache ports but zero free MSHRs is a structural miss limit."],
    misconceptions: ["MLP is not ILP.", "Merging is not a cache hit.", "Adding MSHRs does not remove miss latency. It removes the stall from running out of trackers."],
    variations: ["Sweep MSHRs from 1 to 8 on the parallelism preset.", "Increase miss latency and see overlap matter more."],
    learningOutcomes: ["Read an MSHR table", "Predict a merge", "Explain a full-MSHR stall"],
    viva: [
      { question: "What does an MSHR hold?", answer: "The status of one outstanding line fill." },
      { question: "What is hit-under-miss?", answer: "A later hit completes while a miss is still outstanding." },
      { question: "When do two misses merge?", answer: "When they reference a line that already has an MSHR." },
      { question: "What happens if every MSHR is busy?", answer: "A new miss stalls until one frees." },
      { question: "Why is blocking slower on the overlap preset?", answer: "It cannot serve the second access until the first miss returns." },
    ],
    selfCheck: [
      { prompt: "Same-line misses should use:", choices: ["One MSHR", "One MSHR per byte", "No memory request"], answer: 0, why: "They join the outstanding fill." },
      { prompt: "MLP counts:", choices: ["Outstanding misses", "Renamed registers", "BTB hits"], answer: 0, why: "It is memory-level parallelism." },
      { prompt: "Blocking mode allows miss-under-miss.", choices: ["True", "False"], answer: 1, why: "The blocking comparison turns that off." },
    ],
    summary: "MSHRs are the cache’s permission to have more than one miss in flight. The limit is the number of registers, and same-line misses share one.",
  },
  {
    id: "prefetching",
    labNumber: 24,
    title: "Hardware Prefetcher Laboratory",
    aim: "Compare next-line, stride, stream, and correlation prefetchers on one address trace, using accuracy, coverage, lateness, and pollution.",
    purpose: "A prefetch helps only when it arrives before the demand, is actually used, and does not throw out a line the program still needs.",
    prerequisites: ["Demand misses", "Cache replacement", "The difference between a hit and a late fill"],
    learningObjectives: ["Define accuracy and coverage", "Explain a useless prefetch", "Explain why a higher degree can hurt"],
    theory: [
      "Next-line fetches the following blocks. Stride learns a delta and issues only after confidence reaches the threshold. Stream looks both directions. Correlation repeats a successor it has seen enough times.",
      "Accuracy is useful prefetches divided by prefetches issued. Coverage is demand misses removed compared with a no-prefetch run of the same trace.",
      "Late means the demand arrives while the prefetch is still outstanding. Pollution is counted when a prefetch evicts a demand-installed line that is then missed again. This view uses miss latency 0, so a timely next-line request is not late.",
    ],
    keyTerms: [
      { term: "Degree", meaning: "How many blocks to fetch." },
      { term: "Distance", meaning: "How far ahead the first prefetched block starts." },
      { term: "Useful", meaning: "A demand hit on a line this prefetcher installed." },
    ],
    assumptions: ["Miss latency is 0 in this view, so late stays 0 until you reason about a longer latency.", "Enable Prefetch Filtering refuses a prefetch that would evict a demand line.", "The comparison does not crown a best prefetcher."],
    setup: ["Traces: Sequential, Fixed stride, Reverse stream, Multiple streams, Irregular, Correlated, Random seeded, Phase changing."],
    procedure: [
      "Load Sequential and select Next-line. Note issued, useful, useless, and coverage.",
      "Set degree to 2, Reset, and see coverage and useless prefetches move differently.",
      "Select Stride on Fixed stride. Confirm it waits for confidence.",
      "Select Stream on Reverse stream and Correlation on Correlated.",
      "Load Irregular with Next-line and watch useless prefetches.",
      "Turn Enable Prefetch Filtering on and compare pollution.",
    ],
    controls: ["Next-line, Stride, Stream, Correlation", "Degree", "Distance", "Confidence", "Queue size", "Enable Prefetch Filtering", "Trace preset", "Show Prefetch Requests", "Show Cache Line State", "Highlight Prefetch Hits", "Show Pollution Events", "Auto Advance", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Issued, useful, useless, late", "Accuracy and coverage", "Demand misses versus the no-prefetch baseline", "Pollution events", "Confidence on the stride prefetcher"],
    formulas: [
      { name: "Accuracy", expression: "useful / issued", note: "Zero issued yields no accuracy." },
      { name: "Coverage", expression: "(baseline misses − demand misses) / baseline misses", note: "Coverage can rise while accuracy falls if extra prefetches are unused." },
    ],
    expectedBehavior: ["Sequential next-line removes most misses and may leave one unused prefetch.", "Irregular traces waste next-line prefetches.", "Degree 2 can separate coverage from accuracy."],
    resultInterpretation: ["A high coverage with low accuracy means misses were removed and bandwidth was also spent on unused lines.", "Late would appear if memory latency exceeded the gap. It does not, at latency 0."],
    misconceptions: ["Accuracy and coverage are different ratios.", "A prefetch eviction is not automatically pollution. Pollution requires the evicted demand line to miss later.", "No prefetcher is marked best for every trace."],
    variations: ["Raise degree from 1 to 4 on Sequential.", "Run Phase changing and switch from Next-line to Stride at the conceptual break in the address pattern."],
    learningOutcomes: ["Compute accuracy and coverage from the counters", "Predict a useless next-line prefetch", "Explain filtering"],
    viva: [
      { question: "What is a useful prefetch?", answer: "One that installs a line a later demand hits." },
      { question: "What is coverage?", answer: "The fraction of baseline demand misses that no longer happen." },
      { question: "Why can prefetching reduce performance?", answer: "Useless fills consume bandwidth and can evict useful lines." },
      { question: "When does stride issue?", answer: "After the learned delta repeats enough for confidence to reach the threshold." },
      { question: "Why is late zero in this view?", answer: "Miss latency is 0, so the next-line fill is installed before the following demand." },
    ],
    selfCheck: [
      { prompt: "Accuracy’s denominator is:", choices: ["Prefetches issued", "Baseline misses", "Instructions"], answer: 0, why: "Useful divided by issued." },
      { prompt: "Coverage uses:", choices: ["A no-prefetch baseline", "Only useless prefetches", "BTB hits"], answer: 0, why: "It measures misses removed." },
      { prompt: "Degree 2 always raises accuracy.", choices: ["True", "False"], answer: 1, why: "Extra blocks can be unused." },
    ],
    summary: "Report useful, useless, late, and pollution separately. A prefetcher that covers misses can still waste bandwidth.",
  },
];
