import type { LabGuideContent } from "./types";

export const LABS_17: LabGuideContent[] = [
  {
    id: "mesi",
    labNumber: 17,
    title: "MSI & MESI Coherence Simulator",
    aim: "Step MSI and MESI on the same kind of trace and name each bus action that changes a cache line.",
    purpose: "Snooping protocols keep a single-writer rule. MESI adds Exclusive so a private line can be written without an upgrade bus transaction.",
    prerequisites: ["A cache line, not a byte, is the coherence unit", "Write-back caches", "Invalid, Shared, Modified, and Exclusive"],
    learningObjectives: ["Explain a cold read", "Contrast MSI and MESI on a private write", "List who goes Invalid on a write to a shared line"],
    theory: [
      "MSI uses Modified, Shared, and Invalid. A write to a shared line issues a bus read-for-ownership or upgrade and invalidates other copies.",
      "MESI adds Exclusive: a cold read that finds no other copy may return Exclusive. A later local write can move Exclusive to Modified with no bus traffic. That is the silent upgrade.",
      "A remote read of Modified writes the line back and leaves Shared copies. Presets and the core, operation, and line selectors build the trace. Core counts are 2 or 4.",
    ],
    keyTerms: [
      { term: "BusRd", meaning: "Read request. Other caches may supply or share the line." },
      { term: "BusRdX / BusUpgr", meaning: "Request for a writable copy, invalidating other sharers." },
      { term: "Silent upgrade", meaning: "Exclusive to Modified with no bus message, because no other cache holds the line." },
    ],
    assumptions: ["Shot 0 is the state before the first action.", "MSI never uses Exclusive.", "Show Coherence Traffic and Highlight Cache Line do not change the protocol."],
    setup: ["Choose MSI or MESI, a preset or Execute Operation, then Step. Reset System clears the trace."],
    procedure: [
      "Select MESI and load Private data. Step. The cold read should become Exclusive, and the following write should move to Modified without a bus upgrade.",
      "Switch to MSI, press Reset, and load Private data again. The cold read is Shared, and the write uses the bus.",
      "Load Producer / consumer under MESI. Step until the second core reads. Confirm write-back and Shared.",
      "Load Upgrade. The writer must invalidate the other reader.",
      "Load Write sharing and watch the line bounce between two writers.",
      "Use Execute Operation to add one more read or write and Step it.",
    ],
    controls: ["MSI and MESI", "Core count 2 or 4", "Presets", "Core, Read or Write, line address", "Execute Operation", "Reset System", "Show Coherence Traffic", "Highlight Cache Line", "Auto Advance Cycle", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["State of each core", "Bus message name", "Whether memory was updated", "Invalidations"],
    formulas: [{ name: "Single writer", expression: "Modified or Exclusive means no other cache holds a valid copy", note: "Shared means readers only, until a write invalidates them." }],
    expectedBehavior: ["MESI cold read of a quiet line is Exclusive.", "MSI cold read is Shared.", "A shared write invalidates other holders in both protocols."],
    resultInterpretation: ["If a private write in MESI adds no bus message, Exclusive made the upgrade silent.", "If MSI shows a bus transaction for that write, that is the cost of not having Exclusive."],
    misconceptions: ["Exclusive is not Modified. Memory may still be current in Exclusive.", "Shared does not allow a silent write.", "Coherence of one line is not a memory-consistency model."],
    variations: ["Repeat one preset at 2 cores and 4 cores and count invalidations.", "Add a second line with Execute Operation so two addresses do not share a state."],
    learningOutcomes: ["Draw the MESI silent upgrade", "State the MSI equivalent", "Read a bus trace against cache states"],
    viva: [
      { question: "Why does MESI add Exclusive?", answer: "So a privately read line can be written later without an upgrade transaction." },
      { question: "What happens on a remote read of Modified?", answer: "The owner supplies the line, memory is updated, and the copies become Shared." },
      { question: "Can two caches be Modified for one line?", answer: "No. Modified is exclusive, so the other copies are Invalid." },
      { question: "What does a write to Shared do?", answer: "It invalidates the other sharers and leaves the writer Modified." },
      { question: "Is MSI able to do a silent E to M?", answer: "No. MSI has no Exclusive state." },
    ],
    selfCheck: [
      { prompt: "A MESI cold read with no other copy is typically:", choices: ["Exclusive", "Shared", "Invalid"], answer: 0, why: "The lab’s MESI cold read returns Exclusive." },
      { prompt: "MSI’s corresponding cold read is:", choices: ["Exclusive", "Shared", "Owned"], answer: 1, why: "MSI has no Exclusive." },
      { prompt: "Silent upgrade is:", choices: ["E to M with no bus message", "I to S", "A directory lookup"], answer: 0, why: "Nobody else holds the line." },
    ],
    summary: "MSI and MESI agree on invalidation of sharers. They disagree on whether a private reader must talk to the bus before writing.",
  },
  {
    id: "moesi",
    labNumber: 18,
    title: "MOESI Coherence Simulator",
    aim: "Create a Modified line, share it, and see the owner stay in Owned while memory may remain stale.",
    purpose: "Owned lets a dirty line be shared from cache to cache without writing memory on every remote read.",
    prerequisites: ["MESI states", "Write-back", "Cache-to-cache transfer"],
    learningObjectives: ["Define Owned", "Explain why memory can be stale while O and S exist", "Show a later write taking ownership"],
    theory: [
      "Modified is dirty and exclusive. A remote read can move the owner from Modified to Owned and the reader to Shared.",
      "Owned is dirty and shared. The owner responds to further reads. Memory is not necessarily updated until eviction or an explicit write-back.",
      "A later write must invalidate the owner and the sharers and become the new Modified copy. Presets and Read, Write, and Evict build the trace. Cores are 0 through 3.",
    ],
    keyTerms: [
      { term: "Owned", meaning: "This cache is responsible for the dirty shared line." },
      { term: "Stale memory", meaning: "Memory still holds an older value while Owned is the current one." },
    ],
    assumptions: ["MOESI only. There is no MSI toggle on this page.", "Show Cache-to-Cache Arrows and Highlight MOESI Transitions are visual.", "Clear Log empties the trace."],
    setup: ["The M, O, E, S, and I buttons highlight the legend. They do not change the trace. Quick Examples load a preset."],
    procedure: [
      "Load M to O remote read. Step through the write so one core is Modified, and note the memory value.",
      "Step the remote Read. Confirm Modified becomes Owned and the reader is Shared.",
      "Compare the cache value with memory. Memory can still show the old value.",
      "Load O plus multiple sharers. The owner should remain the supplier for the extra reader.",
      "Load Write takeover. The old owner and sharers invalidate, and the writer becomes Modified.",
      "Load Owner eviction and see whether memory is updated when the owner leaves.",
    ],
    controls: ["State focus buttons", "Read, Write, Evict", "Core selector", "Add to Trace", "Presets", "Clear Log", "Show Cache-to-Cache Arrows", "Highlight MOESI Transitions", "Auto Execute Next", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Which core is O", "Which cores are S", "Memory value versus cache value", "Cache-to-cache transfers", "Invalidations on the write takeover"],
    formulas: [{ name: "Dirty sharing", expression: "Owner holds the newest data; memory may lag", note: "A read of Owned is satisfied by the owner, not by stale memory." }],
    expectedBehavior: ["Remote read of Modified yields Owned plus Shared.", "Memory can stay stale in that state.", "A new writer invalidates the previous owner."],
    resultInterpretation: ["If memory matches the cache immediately on that remote read, the model wrote back. In this lab’s MOESI, the M to O transition leaves memory stale.", "If a second reader gets the new value, the owner supplied it."],
    misconceptions: ["Owned is not Exclusive. Other caches may be Shared.", "Owned is not a clean state.", "Coherence still does not define store-buffer reorderings. That is consistency."],
    variations: ["Evict an Owned line and record whether memory updates.", "Write from the owner instead of from a sharer and compare the bus actions."],
    learningOutcomes: ["Place M, O, E, S, and I on a timeline", "Explain a stale memory value", "Predict the next owner after a write"],
    viva: [
      { question: "How does O differ from M?", answer: "Both are dirty. M is exclusive. O has sharers." },
      { question: "How does O differ from S?", answer: "S may be clean. O is the dirty owner responsible for the data." },
      { question: "Why skip the memory write on a remote read?", answer: "The owner can supply the line. Memory is updated later, for example on eviction." },
      { question: "Who may write next?", answer: "A core that obtains ownership and invalidates the others." },
      { question: "Can memory be read to satisfy a request while O exists?", answer: "Not for the current value. Memory may be stale." },
    ],
    selfCheck: [
      { prompt: "After a remote read of M, the old owner is:", choices: ["Owned", "Invalid", "Exclusive"], answer: 0, why: "This MOESI model moves M to O and leaves memory stale." },
      { prompt: "Owned means the line is clean.", choices: ["True", "False"], answer: 1, why: "Owned is dirty and shared." },
      { prompt: "A new writer must:", choices: ["Invalidate the owner and sharers", "Only update memory", "Stay in Shared"], answer: 0, why: "There can be one writer." },
    ],
    summary: "Owned is dirty sharing. The owner, not memory, is the source of the current line until a write-back happens.",
  },
  {
    id: "directory-coherence",
    labNumber: 19,
    title: "Directory-Based Cache Coherence",
    aim: "Use a directory’s owner and sharer list to send a request only to the caches that hold the line.",
    purpose: "Snooping asks everyone. A directory stores who has the line so invalidations and data requests are targeted.",
    prerequisites: ["MSI-style single-writer rule", "Sharers versus owner", "Why broadcast does not scale"],
    learningObjectives: ["Read a sharer vector", "Explain GetS and GetM", "Count targeted invalidations"],
    theory: [
      "The directory states used here are Uncached, Shared, and Modified. Cache copies are Modified, Shared, or Invalid. There is no Exclusive state in this lab.",
      "A cold read returns Shared from memory and records the reader. A write invalidates only the recorded sharers.",
      "A remote read of Modified gets the value from the owner, updates memory, and leaves both Shared. A remote write transfers ownership and can leave memory stale. Presets: Cold read, Multiple readers, Shared line then a writer, Modified owner then a reader, Modified owner then a new writer, plus the wider few-sharer and migration cases.",
    ],
    keyTerms: [
      { term: "GetS", meaning: "Request a shared copy." },
      { term: "GetM", meaning: "Request ownership for a write." },
      { term: "Sharer vector", meaning: "The directory’s list of readers." },
    ],
    assumptions: ["Core counts on the control are 4 or 8.", "Message, animation, and highlight toggles do not change who is invalidated.", "Issue Request appends one read or write."],
    setup: ["Select a preset or build a trace with core, Read or Write, and Issue Request."],
    procedure: [
      "Load Cold read. Step. The directory should list that core as a sharer and the cache as Shared.",
      "Load Multiple readers. After each step, write down the sharer list.",
      "Load Shared line, then a writer. Count invalidations. They should match the sharers, not every core in the machine.",
      "Load Modified owner, then a reader. Confirm both end Shared and memory is updated.",
      "Load Modified owner, then a new writer. Confirm ownership moves and memory can stay stale.",
      "Switch to 8 cores and Issue Request from a core that was not a sharer.",
    ],
    controls: ["Preset", "Core count 4 or 8", "Core selector", "Read and Write", "Issue Request", "Show Coherence Messages", "Animate Invalidation Flow", "Highlight Directory Updates", "Auto Advance Requests", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Directory state", "Owner", "Sharer list", "Who receives an invalidation", "Memory value"],
    formulas: [{ name: "Targeted invalidation", expression: "Invalidations = number of recorded sharers", note: "Cores that are not in the vector are not sent an invalidation." }],
    expectedBehavior: ["Cold read does not broadcast to every core.", "A writer invalidates only the vector.", "Remote read of Modified updates memory. Remote write of Modified transfers ownership."],
    resultInterpretation: ["If an 8-core machine invalidates two sharers, the directory saved six probes compared with a broadcast.", "If memory is stale after an ownership transfer, the new owner holds the only current copy."],
    misconceptions: ["The directory is not a cache of the data line’s payload only. It is the sharing metadata.", "This lab’s directory does not implement Exclusive.", "Fewer messages does not mean lower latency on a tiny machine. The lookup has a cost, compared in the snooping lab."],
    variations: ["Repeat the writer preset at 4 and 8 cores with the same sharers.", "Issue a write with an empty sharer list and count invalidations."],
    learningOutcomes: ["Update a sharer vector by hand", "Distinguish GetS from GetM", "Explain targeted invalidation"],
    viva: [
      { question: "Who is invalidated on a write?", answer: "Only the sharers the directory has recorded." },
      { question: "What does a cold read return?", answer: "Shared, filled from memory, with that core added to the vector." },
      { question: "What happens when someone reads a Modified line?", answer: "The owner supplies data, memory is written, and both caches become Shared." },
      { question: "Why can memory stay stale after a remote write of Modified?", answer: "Ownership moved to the new writer. The directory does not have to write memory on that transfer." },
      { question: "Is Exclusive present here?", answer: "No. This directory uses Uncached, Shared, and Modified only." },
    ],
    selfCheck: [
      { prompt: "Invalidations go to:", choices: ["Every core", "Recorded sharers", "Only memory"], answer: 1, why: "That is the directory’s point." },
      { prompt: "This directory has an Exclusive state.", choices: ["True", "False"], answer: 1, why: "States are Uncached, Shared, and Modified." },
      { prompt: "A remote read of Modified:", choices: ["Updates memory and leaves Shared", "Leaves memory stale and both Modified", "Deletes the directory"], answer: 0, why: "The owner write-back is part of that transition." },
    ],
    summary: "The directory replaces a broadcast with a lookup. The sharer vector is the list of caches that must hear about a write.",
  },
  {
    id: "false-sharing",
    labNumber: 20,
    title: "False Sharing Visualizer",
    aim: "Measure extra invalidations when independent variables sit on one cache line, and remove them with padding.",
    purpose: "Coherence tracks lines, not program variables. Two counters in one line bounce the line even though the threads never share a variable.",
    prerequisites: ["Cache-line size", "Invalidation on a write", "The difference between a variable and a line"],
    learningObjectives: ["Define false sharing", "Contrast it with true sharing", "Predict the effect of padding"],
    theory: [
      "False sharing: different variables, same line, different writers. Each write invalidates the other core’s copy.",
      "True sharing: the same variable is read or written by more than one thread. Invalidations are required for correctness.",
      "Padding or alignment puts the variables on different lines. The line-size control is 32, 64, or 128 bytes. Presets include Separate cache lines, Two counters, same line, True-sharing counter, Padded counters, Three-thread false sharing, Array of counters, and Packed structure.",
    ],
    keyTerms: [
      { term: "Line", meaning: "The coherence granule. A write claims the whole line." },
      { term: "Padding", meaning: "Unused bytes that push the next variable onto another line." },
    ],
    assumptions: ["Costs in the model are local hit, miss, and transfer as implemented by the engine, not a vendor cycle table.", "Add cache-line padding between variables changes placement.", "Show Memory Addresses, Show Invalidations, and Show Cache Line State are visual."],
    setup: ["False sharing and True sharing buttons load those presets. The example list has the rest."],
    procedure: [
      "Load Separate cache lines. Step and record invalidations or transfers.",
      "Load Two counters, same line. Leave padding off. Step the same number of rounds and compare traffic.",
      "Turn Add cache-line padding between variables on, Reset, and rerun. The ping-pong should drop.",
      "Press True sharing and explain why invalidations remain after padding would not be the right fix.",
      "Load Three-thread false sharing and watch more than two cores bounce one line.",
      "Change the line size and see whether two offsets still collide.",
    ],
    controls: ["Line size 32/64/128", "False sharing and True sharing buttons", "Preset list", "Add cache-line padding between variables", "Show Memory Addresses", "Show Invalidations", "Show Cache Line State", "Auto Replay", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Addresses and line numbers", "Ownership changes", "Invalidations", "The performance estimate before and after padding"],
    formulas: [{ name: "Same line", expression: "floor(address / line size) is equal", note: "Different variables still share coherence state when that quotient matches." }],
    expectedBehavior: ["Separate lines stay quiet.", "Same-line counters ping-pong.", "Padding restores the quiet case.", "True sharing still invalidates."],
    resultInterpretation: ["If padding cuts transfers to the separate-line case, the loss was false sharing.", "If traffic remains on the true-sharing preset, the threads really share a variable."],
    misconceptions: ["False sharing is not a race on the same variable.", "Padding does not fix true sharing.", "A larger line can create false sharing that a smaller line avoided."],
    variations: ["Set line size to 32 and 128 on the packed structure.", "Run the array-of-counters preset and count distinct lines."],
    learningOutcomes: ["Classify a pair of addresses as the same line or not", "Explain a ping-pong", "Choose padding only for false sharing"],
    viva: [
      { question: "Why do different variables invalidate each other?", answer: "They occupy one cache line, and coherence writes operate on the line." },
      { question: "What is true sharing?", answer: "Two threads actually use the same data." },
      { question: "What does padding change?", answer: "Addresses. It moves the next variable to another line." },
      { question: "Does a bigger line always help?", answer: "No. It can merge variables that used to be apart." },
      { question: "Is the performance number a real CPU’s cycle time?", answer: "No. It is this lab’s hit, miss, and transfer cost model." },
    ],
    selfCheck: [
      { prompt: "False sharing requires:", choices: ["The same variable", "The same line and different variables", "A directory always"], answer: 1, why: "The variables are independent. The line is not." },
      { prompt: "Padding should remove traffic in:", choices: ["The same-line counters", "True sharing of one counter", "A single-thread program with no writes"], answer: 0, why: "True sharing still needs the invalidations." },
      { prompt: "Line identity uses:", choices: ["The variable name", "Address divided by line size", "The core id only"], answer: 1, why: "Offsets that fall in one line share coherence state." },
    ],
    summary: "The protocol is correct and still slow when independent writes share a line. Padding changes the addresses, not the protocol.",
  },
];
