import type { LabGuideContent } from "./types";

export const LABS_29: LabGuideContent[] = [
  {
    id: "roofline",
    labNumber: 29,
    title: "Roofline Analysis",
    aim: "Place a workload on the roofline and decide whether its ceiling is the compute roof or the memory roof.",
    purpose: "Arithmetic intensity says how many operations are performed per byte moved. The lower roof is the one the machine can actually deliver.",
    prerequisites: ["FLOPs and bytes", "Peak throughput and bandwidth", "A log-log plot"],
    learningObjectives: ["Compute arithmetic intensity", "Locate the ridge point", "Predict the effect of cache blocking"],
    theory: [
      "The ceiling is the minimum of peak compute and arithmetic intensity times bandwidth.",
      "The ridge is peak divided by bandwidth. Left of the ridge the memory roof is lower. Right of the ridge the compute roof is lower.",
      "One FLOP per byte at 1 GB/s is 1 GFLOP/s in this unit system. Cache blocking halves the bytes. Extra reuse multiplies bytes by 0.8. An observed point above the roof is inconsistent with the current assumptions.",
    ],
    keyTerms: [
      { term: "Arithmetic intensity", meaning: "Operations divided by bytes transferred." },
      { term: "Ridge", meaning: "The intensity where the two roofs meet." },
      { term: "Headroom", meaning: "How far the point sits below its ceiling." },
    ],
    assumptions: ["Presets supply operations and bytes. User defined lets you type them.", "There is no cache-line-size slider and no vectorization toggle.", "Optional observed performance is compared with the ceiling. It does not move the roof."],
    setup: ["Presets: Vector add, SAXPY, Dense matrix multiply, Sparse matrix-vector, Stencil, Reduction, User defined."],
    procedure: [
      "Enter peak compute and bandwidth, or keep the defaults, and read the ridge.",
      "Load Vector add and record intensity and which roof is lower.",
      "Load Dense matrix multiply and compare its intensity with the ridge.",
      "Turn Cache blocking on. Bytes halve, intensity doubles, and the point moves right.",
      "Turn Extra reuse on and see the further 20% byte reduction.",
      "Type an observed performance above the ceiling and read the inconsistency note.",
    ],
    controls: ["Preset", "Peak compute", "Memory bandwidth", "Operations", "Bytes transferred", "Observed performance", "Cache blocking", "Extra reuse", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Intensity", "Ridge", "Which roof is active", "Headroom", "Whether the observed point is above the roof"],
    formulas: [
      { name: "Intensity", expression: "AI = operations / bytes", note: "Bytes already include the blocking or reuse factor when those toggles are on." },
      { name: "Ceiling", expression: "P = min(Ppeak, AI × BW)", note: "1 FLOP/byte × 1 GB/s = 1 GFLOP/s." },
      { name: "Ridge", expression: "AI_ridge = Ppeak / BW", note: "Default 1000 GFLOP/s and 100 GB/s meet at 10 FLOP/byte." },
    ],
    expectedBehavior: ["A low-intensity preset sits under the memory roof.", "Blocking moves the point right and can raise its ceiling.", "A point above the roof is flagged."],
    resultInterpretation: ["If the memory roof is lower, more reuse or less traffic raises the ceiling. More peak compute does not, until the point crosses the ridge.", "If the compute roof is lower, bandwidth is not the next knob."],
    misconceptions: ["The ridge is not a measured runtime.", "Cache blocking in this lab is a byte factor, not a cache simulator.", "An observed point above the roof means the inputs disagree, not that the machine exceeded physics."],
    variations: ["Double bandwidth and watch the ridge move left.", "Set operations and bytes so intensity equals the ridge."],
    learningOutcomes: ["Compute AI and the ceiling", "Name the active roof", "Explain a rightward move from blocking"],
    viva: [
      { question: "What is arithmetic intensity?", answer: "Operations divided by bytes transferred." },
      { question: "Which roof applies left of the ridge?", answer: "The memory roof, AI times bandwidth." },
      { question: "What does cache blocking change here?", answer: "It halves the bytes, which doubles intensity." },
      { question: "What does a point above the roof mean?", answer: "The observed number is inconsistent with the current peak and bandwidth." },
      { question: "Where is the default ridge?", answer: "10 FLOP/byte when peak is 1000 GFLOP/s and bandwidth is 100 GB/s." },
    ],
    selfCheck: [
      { prompt: "AI = 2, bandwidth = 100 GB/s, peak = 1000. Ceiling is:", choices: ["200 GFLOP/s", "1000 GFLOP/s", "2 GFLOP/s"], answer: 0, why: "2 × 100 = 200, which is below the peak." },
      { prompt: "Cache blocking:", choices: ["Halves bytes", "Doubles peak", "Removes the ridge"], answer: 0, why: "Intensity doubles because the denominator halves." },
      { prompt: "Above the roof means the model was exceeded.", choices: ["The inputs are inconsistent", "The machine is faster than the peak", "Bandwidth is zero"], answer: 0, why: "The note says the observation disagrees with the roof." },
    ],
    summary: "Compute intensity, mark the ridge, and read the lower roof. Blocking moves bytes, not the peak.",
  },
  {
    id: "cpi-ipc",
    labNumber: 30,
    title: "CPI - IPC Bottleneck Analyzer",
    aim: "Build a CPI stack from front-end, branch, execution, cache, and memory terms, then cut one term with the what-if sliders.",
    purpose: "A single CPI hides which stall dominates. The stack says where a change can still help.",
    prerequisites: ["CPI and IPC", "A branch misprediction penalty", "A cache miss penalty"],
    learningObjectives: ["Compute CPI and IPC", "Name the largest exclusive component", "Predict the new bottleneck after a 100% cut"],
    theory: [
      "CPI is cycles divided by instructions retired. IPC is the reciprocal.",
      "Branch stall cycles are instructions times branch frequency times misprediction rate times the penalty. Cache stall cycles use the L1 miss rate and the L1 penalty. Memory stall cycles use memory accesses per instruction times the memory penalty.",
      "The stack is exclusive: each cycle is in one bucket. What-if sliders scale memory stalls and branch stalls from 0% to 100% removed. There is no separate toggle for a larger instruction cache or a prefetcher.",
    ],
    keyTerms: [
      { term: "CPI stack", meaning: "A partition of cycles into base and stall classes." },
      { term: "What-if", meaning: "A slider that removes a fraction of one stall class." },
    ],
    assumptions: ["Presets: Compute bound, Branch heavy, Front-end limited, Cache sensitive, Memory bound, Balanced workload, User defined.", "Play sweeps the memory-reduction slider.", "IPC can exceed 1 when base CPI is below 1."],
    setup: ["Load a preset, read the stack, then move one what-if slider. Reset restores the preset’s stalls."],
    procedure: [
      "Load Balanced workload. Record cycles, CPI, IPC, and the largest stack slice.",
      "Set Memory stall reduction to 100%. Record the new cycles and the new largest slice.",
      "Return memory reduction to 0 and set Branch stall reduction to 100%. Compare the speedup with the memory cut.",
      "Load Branch heavy and confirm the branch term leads before any cut.",
      "Load Memory bound and confirm the memory term leads.",
      "Set base CPI below 1 on User defined and read an IPC above 1.",
    ],
    controls: ["Preset", "Instructions retired", "Base CPI", "Front-end stalls", "Branch frequency", "Misprediction rate", "Branch penalty", "L1 miss rate", "Memory accesses per instruction", "Memory stall reduction", "Branch stall reduction", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["Cycles", "CPI", "IPC", "Which slice is largest", "Speedup after a cut", "The slice that becomes largest next"],
    formulas: [
      { name: "CPI", expression: "CPI = cycles / instructions", note: "IPC = instructions / cycles." },
      { name: "Branch stalls", expression: "instructions × branch frequency × mispredict rate × penalty", note: "The what-if slider scales this term." },
      { name: "Speedup", expression: "old cycles / new cycles", note: "A 100% cut removes that class only." },
    ],
    expectedBehavior: ["On the balanced preset the memory slice is the largest.", "Removing all memory stalls leaves the cache slice as the next largest and produces a speedup above 1.", "A full branch cut helps less when branches are not the largest term."],
    resultInterpretation: ["If CPI falls and the architectural instruction count stays the same, the removed stalls were real time, not a change in the program result.", "If another slice becomes largest, the next optimization is a different class."],
    misconceptions: ["IPC above 1 does not require a bug. Base CPI can be below 1.", "The stack buckets do not overlap.", "The sliders are not implementations of prefetch or a bigger cache."],
    variations: ["Sweep memory reduction from 0 to 100 on Memory bound.", "Raise the misprediction rate on Compute bound until the branch slice leads."],
    learningOutcomes: ["Compute CPI and IPC from the totals", "Identify the leading stall", "State the speedup of a what-if cut"],
    viva: [
      { question: "How is CPI related to IPC?", answer: "Each is the reciprocal of the other when both use the same cycles and instructions." },
      { question: "What does a 100% memory cut remove?", answer: "The memory stall term, not the cache or branch terms." },
      { question: "Why can IPC exceed 1?", answer: "Base CPI can be below 1, so more than one instruction retires per cycle in the model." },
      { question: "Are the stack slices overlapping?", answer: "No. They partition cycles." },
      { question: "What should you optimize first?", answer: "The largest slice. A cut to a small slice cannot exceed that slice’s share of cycles." },
    ],
    selfCheck: [
      { prompt: "200 cycles and 100 instructions give CPI:", choices: ["2", "0.5", "200"], answer: 0, why: "Cycles divided by instructions." },
      { prompt: "The same run has IPC:", choices: ["0.5", "2", "100"], answer: 0, why: "IPC is 1/CPI." },
      { prompt: "A memory cut removes branch stalls.", choices: ["True", "False"], answer: 1, why: "Each slider scales one class." },
    ],
    summary: "Read the largest exclusive slice, cut that class, and look at what becomes largest next. CPI and IPC are reciprocals of the same totals.",
  },
  {
    id: "performance-counters",
    labNumber: 31,
    title: "CPU Performance Counter Laboratory",
    aim: "Sample cycles, retired instructions, branches, cache and TLB events, and stalls, then derive IPC, MPKI, and bandwidth.",
    purpose: "A counter is evidence for a hypothesis. IPC by itself does not name the cause.",
    prerequisites: ["CPI and IPC", "Misses per kilo-instruction", "The difference between a cumulative counter and an interval delta"],
    learningObjectives: ["Compute IPC from retired instructions and cycles", "Compute MPKI", "Separate a plausible contributor from a conclusion"],
    theory: [
      "Time is cycles divided by frequency. Bandwidth is bytes moved in that time, reported in GB/s.",
      "Interval rates use the delta between samples, not the cumulative total. Misses cannot exceed accesses.",
      "The evidence panel names a plausible contributor when a threshold is crossed. It does not rank a winning optimization. Per-core bandwidth uses each core’s bytes over the same wall time. Stall shares are exclusive slices of stall cycles in this lab model.",
    ],
    keyTerms: [
      { term: "MPKI", meaning: "Misses per thousand retired instructions." },
      { term: "Delta", meaning: "The change in a counter between two samples." },
      { term: "Retired", meaning: "Instructions that completed architecturally, not instructions fetched." },
    ],
    assumptions: ["Presets: Compute heavy, Branch heavy, Streaming memory, Random memory, Cache friendly, TLB stress, Front-end heavy, Mixed workload.", "Threads are 1, 2, 4, or 8. Frequency is 0.5 to 6 GHz.", "Save run stores a local snapshot. Export CSV and Export JSON download that snapshot. Comparison after two saves does not rank a winner."],
    setup: ["Choose a preset and a thread count. Step moves one sample. Play walks the sample list."],
    procedure: [
      "Load Streaming memory. Step through the samples. Record IPC, bandwidth, and the evidence sentence.",
      "Switch the table between cumulative values and deltas. Confirm an interval rate uses the delta.",
      "Load Branch heavy and compare branch misses with the streaming run.",
      "Load TLB stress and read the TLB counters before concluding the cache is the cause.",
      "Save two runs and open the comparison. Confirm it does not declare a winner.",
      "Export CSV and check that the counters match the screen.",
    ],
    controls: ["Preset", "Threads", "Frequency", "Save run", "Export CSV", "Export JSON", "Comparison selector", "Play, Pause, Step, Reset, Simulation Speed"],
    observations: ["IPC and CPI", "MPKI", "Miss rates", "Stall shares", "Bandwidth", "Per-core instructions", "The evidence wording"],
    formulas: [
      { name: "IPC", expression: "instructions retired / cycles", note: "CPI is the reciprocal." },
      { name: "MPKI", expression: "1000 × misses / instructions retired", note: "Use the same interval for both numbers." },
      { name: "Bandwidth", expression: "bytes / (cycles / frequency)", note: "Displayed in GB/s. Per-core figures share one wall-clock interval." },
    ],
    expectedBehavior: ["Streaming memory shows bandwidth as a plausible contributor and a modest IPC.", "A mixed preset can keep a steady interval IPC while cumulative counters grow.", "Two saved runs are listed without a ranking."],
    resultInterpretation: ["If the evidence says memory is a plausible contributor, the supporting counters are bandwidth, miss rate, or memory stalls, not IPC alone.", "A high branch-miss count supports a branch hypothesis only on the branch-heavy preset’s counters."],
    misconceptions: ["IPC is not a cause.", "A cumulative counter is not an interval rate.", "The comparison does not crown a workload."],
    variations: ["Change frequency and watch bandwidth move while IPC stays tied to instructions and cycles.", "Set threads to 1 and to 8 on Streaming memory and compare per-core bandwidth."],
    learningOutcomes: ["Derive IPC, CPI, and MPKI", "Read a delta", "Match an evidence sentence to the counters that support it"],
    viva: [
      { question: "Why is IPC not a diagnosis?", answer: "It says how many instructions retired per cycle, not which stall produced that rate." },
      { question: "What is MPKI?", answer: "Misses per thousand retired instructions." },
      { question: "Which numbers form an interval rate?", answer: "The deltas between samples." },
      { question: "How is bandwidth obtained?", answer: "Bytes divided by time, and time is cycles divided by frequency." },
      { question: "What does the comparison refuse to do?", answer: "It does not rank a winning run." },
    ],
    selfCheck: [
      { prompt: "1000 misses and 1,000,000 retired instructions give MPKI:", choices: ["1", "1000", "0.001"], answer: 0, why: "1000 × 1000 / 1,000,000 = 1." },
      { prompt: "Interval IPC should use:", choices: ["Deltas", "Only the final cumulative total", "Frequency alone"], answer: 0, why: "The rate is the change over that sample." },
      { prompt: "The panel’s phrase is:", choices: ["A plausible contributor", "The proven single cause", "A ranked winner"], answer: 0, why: "IPC alone is not treated as a cause." },
    ],
    summary: "Sample the counters, derive the rates from deltas, and keep the evidence sentence tied to the counters that support it.",
  },
];
