/** Values sampled from the LogicLab target screens: cool page, white panels, blue actions. */
export const colors = {
  page: "#F4F7FB",
  panel: "#FFFFFF",
  card: "#FFFFFF",
  elevated: "#FFFFFF",
  inset: "#F8FAFC",
  primary: "#2F6FED",
  primaryStrong: "#1D4ED8",
  primarySoft: "#E8F0FE",
  text: "#122033",
  textSecondary: "#5C6B82",
  textMuted: "#8B9BB0",
  border: "#E5EDF5",
  borderActive: "#2F6FED",
  signalHigh: "#2F6FED",
  signalLow: "#94A3B8",
  signalFloat: "#F59E0B",
  signalInvalid: "#E11D48",
  success: "#12B76A",
  successSoft: "#ECFDF3",
  danger: "#F04438",
  dangerSoft: "#FEF3F2",
} as const;
