import type { ProjectId } from "./projectData";
import type { Runtime } from "./projectEngine";

const n = (v: unknown) => typeof v === "number" ? v : 0;
const text = (v: unknown) => typeof v === "boolean" ? v ? "ON" : "OFF" : String(v ?? "—");
const Row = ({ name, value, good }: { name: string; value: unknown; good?: boolean }) => <div className="mcu-readout-row"><span>{name}</span><strong className={good === undefined ? "" : good ? "good" : "bad"}>{text(value)}</strong></div>;
const Bar = ({ label, value, max = 100, unit = "%" }: { label: string; value: number; max?: number; unit?: string }) => <div className="mcu-readout-bar"><div><span>{label}</span><strong>{Math.round(value)}{unit}</strong></div><meter min="0" max={max} value={Math.max(0, Math.min(max, value))} /></div>;

export function ProjectReadout({ id, state }: { id: ProjectId; state: Runtime }) {
  const o = state.outputs, i = state.inputs;
  if (id === "traffic") return <><div className="mcu-readout-sequence">{["NS_GREEN", "NS_YELLOW", "ALL_RED_NS", "EW_GREEN", "EW_YELLOW", "ALL_RED_EW"].map((step, index) => <div key={step} className={o.state === step ? "current" : ""}><span className={`lamp ${step.includes("GREEN") ? "green" : step.includes("YELLOW") ? "yellow" : "red"}`} /><small>{index + 1}. {step.replaceAll("_", " ")}</small></div>)}</div><Row name="Current state" value={text(o.state).replaceAll("_", " ")} /><Row name="Time remaining" value={`${text(o.remaining)} s`} /><Row name="Next state" value={text(o.next).replaceAll("_", " ")} /><Row name="Safety interlock" value={o.safety} good={!i.detectorFault} /></>;
  if (id === "street") return <><div className="mcu-readout-large">{text(i.ambient)} <small>lux</small></div><Bar label="Ambient light" value={n(i.ambient)} max={1000} unit=" lux" /><Row name="Lamp status" value={o.lampHealth} good={o.lampHealth === "Operating"} /><Row name="Actual brightness" value={`${text(o.brightness)}%`} /><Row name="Power consumption" value={`${text(o.power)} W`} /><Row name="LDR ADC" value={`${text(o.ldr)} / 4095`} /></>;
  if (id === "thermometer") return <><div className="mcu-readout-temperature"><div className="mcu-readout-thermo"><i style={{ height: `${Math.max(5, Math.min(100, (n(o.celsius) + 10) / 60 * 100))}%` }} /></div><div><div className="mcu-readout-large">{text(o.temperature)}<small>{text(i.unit)}</small></div><span>{text(o.alarmState)}</span></div></div><Row name="Sensor" value={i.sensor} /><Row name="ADC reading" value={o.adc} /><Row name="Input voltage" value={`${text(o.voltage)} V`} /><Row name="Min / Max" value={`${text(state.memory.min)} / ${text(state.memory.max)} °C`} /></>;
  if (id === "ultrasonic") return <><div className="mcu-readout-large">{text(o.distance)} <small>cm</small></div><Row name="Trigger pulse" value={`${text(o.triggerUs)} µs`} /><Row name="Echo pulse width" value={`${text(o.echoUs)} µs`} /><Row name="Echo quality" value={o.echoQuality} good={o.echoQuality === "Valid"} /><Row name="Obstacle alert" value={o.alert ? "Obstacle" : "Clear"} good={!o.alert} /><Row name="Buzzer" value={o.buzzer} /></>;
  if (id === "irrigation") return <>{text(o.zones).split(",").map((v, index) => <Bar key={index} label={`${["Vegetables", "Herbs", "Flowers"][index]} moisture`} value={Number(v)} />)}<Row name="Water pump" value={o.pump} good={o.pump === true} /><Row name="Flow rate" value={`${text(o.flow)} L/min`} /><Row name="Water today" value={`${text(o.usedToday)} L`} /><Row name="Tank remaining" value={`${text(o.tankRemaining)}%`} /></>;
  if (id === "robot") return <><div className="mcu-readout-sensors">{text(o.sensors).split(" ").map((v, index) => <div key={index} className={v === "1" ? "detected" : ""}><span className="sensor-eye" /><strong>{v}</strong><small>{["Left", "Center", "Right"][index]}</small></div>)}</div><Bar label="Left wheel PWM" value={n(o.leftPWM)} max={255} unit="" /><Bar label="Right wheel PWM" value={n(o.rightPWM)} max={255} unit="" /><Row name="Line position" value={o.lost ? "Lost" : "Tracking"} good={!o.lost} /><Row name="Lap" value={o.lap} /><Row name="Recovery" value={o.recovery} /></>;
  if (id === "motor") return <><div className="mcu-rpm-gauge" style={{ background: `conic-gradient(#1769e0 ${Math.min(100, n(o.rpm) / 5000 * 100)}%, #dce5f0 0)` }}><div><strong>{text(o.rpm)}</strong><small>RPM</small></div></div><div className="mcu-readout-pair"><div><small>Target RPM</small><strong>{text(o.target)}</strong></div><div><small>Actual RPM</small><strong>{text(o.rpm)}</strong></div></div><Row name="Duty cycle" value={`${text(o.duty)}%`} /><Row name="Motor current" value={`${text(o.current)} A`} /><Row name="Driver protection" value={o.tripReason} good={o.tripReason === "Normal"} /></>;
  if (id === "arm") return <>{["base", "shoulder", "elbow", "wrist", "gripper"].map((joint) => <Bar key={joint} label={joint[0]!.toUpperCase() + joint.slice(1)} value={n(o[joint])} max={joint === "gripper" ? 100 : 180} unit={joint === "gripper" ? "%" : "°"} />)}<Row name="End effector" value={`X ${text(o.endX)} · Y ${text(o.endY)} cm`} /><Row name="Task" value={o.holding ? "Holding object" : o.placed ? "Placed object" : "Ready"} /></>;
  if (id === "weather") return <div className="mcu-readout-grid">{[["Temperature", "temperature", "°C"], ["Humidity", "humidity", "%"], ["Pressure", "pressure", "hPa"], ["Wind", "wind", "km/h"], ["Rainfall", "rain", "mm"], ["Light", "light", "lux"]].map(([label, key, unit]) => <div key={key}><small>{label}</small><strong>{text(o[key!])}</strong><span>{unit}</span></div>)}</div>;
  if (id === "home") return <><Row name="Total power usage" value={`${text(o.power)} W`} /><Row name="Active devices" value={`${text(o.active)} / 6`} /><Row name="Home mode" value={i.mode} /><Row name="Security" value={o.intrusion ? "Intrusion" : "Secure"} good={!o.intrusion} /><Row name="Motion sensor" value={i.motion ? "Motion" : "No motion"} /><Row name="Door lock" value={o.lock ? "Locked" : "Unlocked"} good={o.lock === true} /></>;
  if (id === "iot") return <div className="mcu-readout-grid">{[["Temperature", "temperature", "°C"], ["Humidity", "humidity", "%"], ["Soil moisture", "moisture", "%"], ["Light level", "light", "lux"], ["Battery", "battery", "V"], ["Signal", "rssi", "dBm"]].map(([label, key, unit]) => <div key={key}><small>{label}</small><strong>{text(o[key!])}</strong><span>{unit}</span></div>)}</div>;
  return <><Row name="Current mode" value={i.board} /><Row name="Active modules" value={o.activeModules} /><Row name="Green LED" value={o.green} good={o.green === true} /><Row name="Red LED" value={o.red} /><Row name="Buzzer" value={o.buzzer} /><Row name="Relay" value={o.relay} /><Row name="CPU loop" value={`${text(state.memory.firmwareTicks)} ticks`} /><Row name="Power state" value={o.warning ? "Check wiring" : "Powered"} good={!o.warning} /></>;
}
