import type { Control, ProjectId } from "./projectData";

export type Enhancement = { key: string; title: string; description: string; unit?: string; control?: Control & { initial: number | boolean | string } };
const range = (key: string, title: string, description: string, initial: number, min: number, max: number, unit = "", step = 1): Enhancement => ({ key, title, description, unit, control: { key, label: title, kind: "range", initial, min, max, unit, step } });
const toggle = (key: string, title: string, description: string, initial = false): Enhancement => ({ key, title, description, control: { key, label: title, kind: "toggle", initial } });
const select = (key: string, title: string, description: string, initial: string, options: string[]): Enhancement => ({ key, title, description, control: { key, label: title, kind: "select", initial, options } });
const metric = (key: string, title: string, description: string, unit = ""): Enhancement => ({ key, title, description, unit });

export const PROJECT_ENHANCEMENTS: Record<ProjectId, Enhancement[]> = {
  traffic: [
    toggle("adaptive", "Adaptive green", "Extend the green interval toward the busier queue."),
    range("nsDemand", "N/S arrivals", "Vehicles arriving from the north and south each minute.", 5, 0, 30, "/min"),
    range("ewDemand", "E/W arrivals", "Vehicles arriving from the east and west each minute.", 5, 0, 30, "/min"),
    toggle("nightFlash", "Night flash", "Flash yellow when traffic is very light."),
    toggle("detectorFault", "Detector fault", "Force a safe all-red state when a detector fails."),
    metric("nsQueue", "N/S queue", "Vehicles waiting on the north/south approach.", "cars"),
    metric("ewQueue", "E/W queue", "Vehicles waiting on the east/west approach.", "cars"),
    metric("throughput", "Vehicles passed", "Cumulative vehicles released by green signals.", "cars"),
    metric("walkCountdown", "Walk countdown", "Seconds remaining in an active pedestrian crossing.", "s"),
    metric("safety", "Safety interlock", "Shows normal, flashing, or fault-safe operation."),
  ],
  street: [
    range("hysteresis", "LDR hysteresis", "Prevent relay chatter near the light threshold.", 0, 0, 100, "lux"),
    toggle("occupancy", "Pedestrian occupancy", "Dim the lamps while no one is nearby.", true),
    range("dimLevel", "Idle dim level", "Brightness when occupancy dimming is active.", 35, 5, 100, "%"),
    toggle("lampFault", "Lamp failure", "Simulate a failed lamp while the relay still operates."),
    range("sensorBias", "LDR calibration", "Offset the measured light level before firmware reads it.", 0, -100, 100, "lux"),
    metric("brightness", "Actual brightness", "Delivered brightness after dimming and faults.", "%"),
    metric("energyWh", "Energy used", "Integrated electrical energy consumed by the lamp.", "Wh"),
    metric("relayCycles", "Relay cycles", "Number of relay transitions."),
    metric("ldrVoltage", "LDR voltage", "Approximate divider voltage presented to the ADC.", "V"),
    metric("lampHealth", "Lamp health", "Reports operating, dimmed, failed, or off."),
  ],
  thermometer: [
    range("calibration", "Calibration offset", "Correct a systematic temperature measurement error.", 0, -5, 5, "°C", .1),
    range("sensorNoise", "Sensor noise", "Inject deterministic measurement noise.", 0, 0, 3, "°C", .1),
    range("filterWindow", "Average window", "Smooth the latest sensor samples.", 1, 1, 10, "samples"),
    toggle("sensorDisconnected", "Sensor disconnected", "Test the display and alarm response to missing data."),
    range("lowAlarm", "Low alarm", "Trigger an alert below this temperature.", 0, -10, 30, "°C"),
    metric("filteredTemp", "Filtered reading", "Temperature delivered to firmware after calibration and filtering.", "°C"),
    metric("tempTrend", "Temperature trend", "Change since the previous sensor reading.", "°C"),
    metric("sampleCount", "Samples captured", "Number of temperature measurements."),
    metric("alarmState", "Alarm state", "High, low, sensor fault, or normal."),
    metric("sensorHealth", "Sensor health", "Connection and conversion status."),
  ],
  ultrasonic: [
    range("targetSpeed", "Target speed", "Move the target toward or away from the transducer.", 0, -30, 30, "cm/s"),
    range("echoDropout", "Echo dropout", "Chance that a pulse returns no usable echo.", 0, 0, 100, "%"),
    range("averaging", "Echo averaging", "Smooth recent distance measurements.", 1, 1, 8, "samples"),
    range("blindZone", "Blind zone", "Reject objects closer than the transducer can resolve.", 5, 2, 30, "cm"),
    range("alertHysteresis", "Alert hysteresis", "Hold the alert until the object moves clear.", 0, 0, 20, "cm"),
    metric("rawDistance", "Raw distance", "Unfiltered distance derived from echo time.", "cm"),
    metric("filteredDistance", "Filtered distance", "Distance after averaging valid echoes.", "cm"),
    metric("echoQuality", "Echo quality", "Valid, blind zone, dropped, or idle."),
    metric("timeoutCount", "Echo timeouts", "Cumulative missing echo pulses."),
    metric("closestSeen", "Closest object", "Minimum valid distance observed.", "cm"),
  ],
  irrigation: [
    range("reservoir", "Reservoir level", "Water available to the pump.", 100, 0, 100, "%"),
    range("rainChance", "Rain forecast", "Probability used by the irrigation rain lockout.", 0, 0, 100, "%"),
    range("zoneBias", "Soil sensor bias", "Calibration offset for moisture sensing.", 0, -20, 20, "%"),
    range("waterBudget", "Water budget", "Maximum simulated water consumption.", 10, 1, 50, "L"),
    toggle("leak", "Leak simulation", "Create flow even while the pump is off."),
    metric("activeValve", "Active valve", "Garden zone currently receiving water."),
    metric("tankRemaining", "Tank remaining", "Water left after consumption.", "%"),
    metric("usedToday", "Water used", "Cumulative water delivered or leaked.", "L"),
    metric("dryRun", "Dry-run alarm", "Pump blocked when the tank is empty."),
    metric("leakRate", "Leak rate", "Uncommanded water flow.", "L/min"),
  ],
  robot: [
    range("irNoise", "IR noise", "Add deterministic uncertainty to the line sensor.", 0, 0, 20, "%"),
    range("lineContrast", "Line contrast", "Change how easily the IR sensors distinguish the track.", 100, 10, 100, "%"),
    range("robotBattery", "Battery charge", "Limit wheel power as the battery empties.", 100, 0, 100, "%"),
    toggle("obstacle", "Obstacle", "Stop for an object blocking the track."),
    toggle("emergencyStop", "Emergency stop", "Immediately disable both wheel motors."),
    metric("velocity", "Ground speed", "Approximate travel speed along the track.", "cm/s"),
    metric("encoderTicks", "Encoder ticks", "Cumulative simulated wheel pulses."),
    metric("lapTime", "Lap time", "Elapsed time since the last completed lap.", "s"),
    metric("steering", "Steering demand", "Difference between right and left wheel PWM."),
    metric("recovery", "Recovery mode", "Tracking, searching, obstacle, or stopped."),
  ],
  motor: [
    range("ambientTemp", "Ambient temperature", "Surrounding air temperature for motor cooling.", 25, 0, 60, "°C"),
    range("currentLimit", "Current limit", "Maximum safe H-bridge current.", 2, .2, 5, "A", .1),
    range("thermalLimit", "Thermal limit", "Trip temperature for the motor winding.", 85, 40, 130, "°C"),
    toggle("brake", "Dynamic brake", "Short the motor terminals through the driver to stop quickly."),
    range("cooling", "Cooling airflow", "Increase heat removal from the motor.", 50, 0, 100, "%"),
    metric("motorTemp", "Motor temperature", "Estimated winding temperature.", "°C"),
    metric("backEmf", "Back EMF", "Voltage generated by the spinning motor.", "V"),
    metric("efficiency", "Efficiency", "Electrical-to-mechanical power estimate.", "%"),
    metric("energyWh", "Energy used", "Integrated motor energy consumption.", "Wh"),
    metric("tripReason", "Driver protection", "Normal, overcurrent, overheat, brake, or stall."),
  ],
  arm: [
    range("motionSpeed", "Motion speed", "Limit the rate at which joints approach a new pose.", 60, 10, 100, "%"),
    range("payload", "Payload mass", "Weight carried by the gripper.", 100, 0, 500, "g"),
    range("softLimit", "Joint soft limit", "Restrict maximum joint rotation.", 180, 90, 180, "°"),
    toggle("armStop", "Emergency stop", "Freeze all servo movement."),
    range("gripForce", "Gripper force", "Set the maximum force available to hold an object.", 100, 0, 200, "%"),
    metric("reach", "Arm reach", "Distance from base to end effector.", "cm"),
    metric("servoPulse", "Base pulse", "Commanded PWM pulse width for the base servo.", "ms"),
    metric("loadTorque", "Load torque", "Approximate payload torque at the arm joint.", "N·m"),
    metric("collision", "Collision check", "Reports a table collision or clear movement."),
    metric("pickCycles", "Pick/place cycles", "Completed object transfers."),
  ],
  weather: [
    range("seaPressure", "Sea-level pressure", "Reference pressure for the local weather model.", 1013, 960, 1040, "hPa"),
    range("uvIndex", "UV index", "Adjust solar exposure; high UV raises a weather alert.", 4, 0, 12),
    toggle("stormFront", "Storm front", "Lower pressure and raise gusts and rainfall."),
    range("alertTemp", "Heat alert", "Temperature threshold for weather warnings.", 38, 20, 50, "°C"),
    range("alertWind", "Wind alert", "Wind-speed threshold for weather warnings.", 45, 10, 80, "km/h"),
    metric("dewPoint", "Dew point", "Temperature where humidity would begin to condense.", "°C"),
    metric("heatIndex", "Heat index", "Approximate apparent heat in humid conditions.", "°C"),
    metric("windChill", "Wind chill", "Approximate apparent cold in windy conditions.", "°C"),
    metric("rainRate", "Rain rate", "Effective rainfall after storm-front effects.", "mm/h"),
    metric("weatherAlert", "Weather alerts", "Heat, wind, storm, high UV, or normal."),
  ],
  home: [
    toggle("doorOpen", "Door sensor", "Simulate an open front door."),
    range("indoorTemp", "Indoor temperature", "Room temperature used by thermostat control.", 27, 15, 40, "°C"),
    range("setpoint", "Thermostat setpoint", "Cooling threshold for the fan.", 26, 18, 32, "°C"),
    toggle("autoLock", "Auto-lock", "Lock the door when the house is in Away mode."),
    toggle("appliance", "Appliance outlet", "Switch an additional 120 W load."),
    metric("intrusion", "Intrusion alarm", "Door-open condition while Away mode is active."),
    metric("thermostat", "Thermostat demand", "Fan demand caused by indoor temperature."),
    metric("appliancePower", "Appliance draw", "Power of the switched outlet.", "W"),
    metric("energyWh", "House energy", "Integrated energy for active devices.", "Wh"),
    metric("occupied", "Occupancy", "Derived from mode and motion sensing."),
  ],
  iot: [
    range("retryLimit", "Retry limit", "Maximum retries for a lost telemetry packet.", 2, 0, 5),
    range("solarInput", "Solar charging", "Charging current supplied by an optional solar panel.", 0, 0, 100, "mA"),
    select("payloadMode", "Payload detail", "Choose compact or complete telemetry.", "Full", ["Full", "Compact"]),
    range("packetLoss", "Extra packet loss", "Inject network loss in addition to weak RSSI.", 0, 0, 100, "%"),
    range("lowBattery", "Low-battery threshold", "Voltage where the node enters conservation mode.", 3.5, 3.3, 4.1, "V", .1),
    metric("retryCount", "Retries", "Cumulative packet retry attempts."),
    metric("queueDepth", "Queued packets", "Messages waiting for connection recovery."),
    metric("payloadBytes", "Payload size", "Estimated bytes in the current MQTT payload.", "B"),
    metric("uptime", "Node uptime", "Elapsed powered-on time.", "s"),
    metric("powerMode", "Power mode", "Active, deep sleep, or low-battery conservation."),
  ],
  builder: [
    range("supplyVoltage", "Supply voltage", "Voltage available to the prototype rails.", 3.3, 0, 5, "V", .1),
    range("maxCurrent", "Current budget", "Maximum current the board supply can provide.", 500, 50, 1000, "mA", 10),
    toggle("analogFault", "Analog sensor fault", "Disconnect the analog temperature and distance sensors."),
    range("wireResistance", "Wire resistance", "Simulate voltage drop along the circuit wiring.", 0, 0, 20, "Ω", .5),
    toggle("debugBreak", "Debug breakpoint", "Pause the simulation after a firmware tick."),
    metric("estimatedCurrent", "Estimated current", "Current drawn by active components.", "mA"),
    metric("voltageDrop", "Voltage drop", "Loss across connected wiring.", "V"),
    metric("pinConflicts", "Pin conflicts", "Number of repeated GPIO assignments."),
    metric("connectedCount", "Connected modules", "Modules with an assigned GPIO pin."),
    metric("debugState", "Debugger state", "Running, paused, or halted at breakpoint."),
  ],
};

export const enhancementDefaults = (id: ProjectId) => Object.fromEntries(PROJECT_ENHANCEMENTS[id].flatMap((item) => item.control ? [[item.key, item.control.initial]] : []));
